### ISSUE TITLE
Problem with using .setLayer to replace image source

### ISSUE THREAD

**Issue by Dave-Edwards** [caleb531/jcanvas#137]
V 14.01.01

I am trying to replace an existing image with a new and resized image by changing the source via .setLayer()

Sometimes the old image is correctly replaced by the new image which is cropped and resized properly, but more often than not often the new image is displayed (cropped but not resized) over the old image.

Moving a mouse over the image will cause the old image to disappear, and the new to be resized.

Here is a fiddle which demonstrates what happens http://jsfiddle.net/ted_fiddle/4j27y/ 

Thanks

Dave

**Comment by dadixon** [comment]
I'm having the same kind of issue. I'm using a jQuery plugin called Cropper that crops my images and saves them. After they are cropped and saved, I use setLayer and change the source and also use the load: function() { this.drawlayer() method to ensure the layers are being drawn over but my image size gets messed up. I tried to follow along with this post to fix the issue but I got no luck.
