### ISSUE TITLE
Ellipse with equal width and height should be round...

### ISSUE THREAD

**Issue by rdpoor** [caleb531/jcanvas#141]
I don't consider this really urgent since there's a clear workaround (use drawArc instead), but normally, an ellipse with equal width and height is expected to be round. 

The following code shows such an ellipse overlaid with an arc -- the slight bulges are readily observed:

$('canvas').drawEllipse({
  fillStyle: '#0ff',
  x: 150, y: 150,
  width: 200, height: 200
}).drawArc({
  fillStyle: '#f88',
  strokeWidth: 5,
  x: 150, y: 150,
  radius: 100
});

![screen shot 2014-01-30 at 10 36 14 pm](https://f.cloud.github.com/assets/1796161/2048326/0805ecae-8a42-11e3-81c2-fd576f19840d.png)

**Comment by Avejack** [comment]
Wouldn't it be a better way to just use an Arc and set the width and height via scaleX and scaleY?
Example:

$('canvas').drawArx({
      fillStyle: '#F00',
      x: 150, x: 150,
      radius: 1,
      scaleX: 100,
      scaleY: 150
});#

Perfect Ellipses i guess...
What do you say?

**Comment by caleb531** [comment]
Drawing a shape with `scaleX` and `scaleY` actually has some unavoidable consequences. Consider the following example—notice how the pattern background and stroke of the shape are skewed when `scaleX`/`scaleY` are applied:

**Ellipse drawn with Bézier curves:**  
![screen shot 2017-02-02 at 10 33 05 am](https://cloud.githubusercontent.com/assets/872474/22562878/3745f6a0-e933-11e6-85cd-6495dfeaa411.png)

**Ellipse drawn with scaled arc:**  
![screen shot 2017-02-02 at 10 33 10 am](https://cloud.githubusercontent.com/assets/872474/22562881/39b27846-e933-11e6-8c04-98ba21275f21.png)

Therefore, I have no intention of rewriting `drawEllipse` to use the latter approach, but you're welcome to if you aren't using patterns or strokes for your purposes.

**Comment by Avejack** [comment]
Didn't think about that.

Sadly i'm going to use strokes on my arcs. But those 'unreal' ellipses aren't acceptable for me as well... Maybe i'm coming up with another "hack"... 

Thanks for your answer!

**Comment by caleb531** [comment]
Thanks. ^_^

If you aren't as concerned about browser support, there is now a native `ellipse()` method (for which it would be pretty easy to write a [jCanvas Plugin](https://projects.calebevans.me/jcanvas/docs/extending/):

https://www.rgraph.net/blog/html5-canvas-ellipse.html
