### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defaultView' of undefined 

### ISSUE THREAD

**Issue by jeremy-saidani** [caleb531/jcanvas#159]
Hi !

I try to animate layers by I get this javascript error : 
Uncaught TypeError: Cannot read property 'defaultView' of undefined. I can't get the line of code because it's in jquery-1.11.0.min.js:3 ...

It's happened randomly, I have a for loop to animate some layers. Sometimes it's works, sometimes not. I checked in printing the layer name to animate before $canvas.animateLayer(name, {}), and even by getting the layer with $canvas.getLayer(name) and do a animateLayer with it and every time the layer name is good.
I think it's happened when I try to animate layers I already animate few line of code before, but I'm not sure because sometimes yes, sometimes no ...

I spend to much time on it so if you have an idea where I can looking for that can be great !

PS : sorry for y english I'm french !

**Comment by chandana-iconma** [comment]
I have some issue that i am binding some latlongs using localstorage of IndexDB in ionic,
by that stored latlongs how can i open google maps

**Comment by chandana-iconma** [comment]
[
