### ISSUE TITLE
jcanvas handle plugin don't hold proportion.

### ISSUE THREAD

**Issue by Envo** [caleb531/jcanvas#176]
When the original Image resource changed, it's size setted to image 1:1 size. But when I want to resize it  with the handle plugin, it's doing to some kind reset, and the resource size is change.

![handle_bug](https://cloud.githubusercontent.com/assets/1453516/5804064/37b6f8da-a003-11e4-85c2-0ed75342947b.jpg)

**Comment by caleb531** [comment]
Could you please provide the code you are using so I can better pinpoint any potential issue?

Thanks,
Caleb

**Comment by Envo** [comment]
I just simply can't. The code is uncommented, and is also heavily in development. I solve this problem by save the main values, and after that remove and draw a new image by that values. However, i think when I change the resource (and the Image object's size), some other values need to be changed too, but i can't figure it out what are that values.
