### ISSUE TITLE
Hard to move arrows/pointers in a device or even PC

### ISSUE THREAD

**Issue by shubhankar** [caleb531/jcanvas#179]
The pointer should move very easily. But the area is very minimal which is getting difficult to move/drag the pointer

**Comment by caleb531** [comment]
Could you please provide a code sample which demonstrates what you are trying to describe?

**Comment by shubhankar** [comment]
// draw pointer on the canvas
function drawPointerInPicture() {
    $('#canvas').drawLine({
        strokeStyle: '#f00',
        strokeWidth: 5,
        rounded: true,
        startArrow: true,
        arrowRadius: 15,
        arrowAngle: 90,
        x1: 100, y1: 200,
        x2: 160, y2: 145,
        draggable: true,
        layer: true,
        name: 'pointer_' + createGuid(),
        handlePlacement: 'both',
        handle: {
            type: 'arc',
            fillStyle: '#f00',
            strokeStyle: '#c33',
            strokeWidth: 1,
            radius: 8
        }
    });
}

**Comment by caleb531** [comment]
I don't have any issue dragging the line's arrows or the line itself. If you'd like to expand the draggable area of the line, I recommend creating a [jCanvas drag group](http://calebevans.me/projects/jcanvas/docs/draggableLayers/#drag-groups).

Caleb

**Comment by shubhankar** [comment]
Yes it is draggable now. But the handle is still not moving. How to do that?

var guid = createGuid();
    $('#canvas').drawLine({
        strokeStyle: '#f00',
        strokeWidth: 5,
        rounded: true,
        startArrow: true,
        arrowRadius: 15,
        arrowAngle: 90,
        x1: 100, y1: 200,
        x2: 160, y2: 145,
        draggable: true,
        layer: true,
        name: 'pointer_' + guid,
        groups: ['pointers_' + guid],
        dragGroups: ['pointers_' + guid],
        handlePlacement: 'both',
        handle: {
            type: 'arc',
            fillStyle: '#f00',
            strokeStyle: '#c33',
            strokeWidth: 1,
            radius: 8
        }
    })
    .drawRect({
        layer: true,
        draggable: true,
        strokeStyle: '#f00',
        strokeWidth: 0,
        groups: ['pointers_' + guid],
        dragGroups: ['pointers_' + guid],        
        x: 130, y: 176,
        width: 68, height: 60
    });

**Comment by joshuapinter** [comment]
Just something I ran into that might be relevant to this. 

When I added a CSS border directly to my `<canvas>` object, it caused the dragging of layers to be difficult. By moving the CSS border to a parent canvas container DIV, the problem was solved.
