### ISSUE TITLE
Suggest for Event contextmenu.

### ISSUE THREAD

**Issue by Boxedsolutions** [caleb531/jcanvas#180]
Hi, I want to thank you for a wonderful plugin. I have added contextmenu in my file and it seems to working. 

If you want to be able to add a own contextmenu for items in the canvas. To get properties and such stuff

**Comment by caleb531** [comment]
Considering that this feature requires only one line of code on my part, I'd be happy to add it.

I've pushed up jCanvas v15.01.25 now. Let me know how it works for you. :)
