### ISSUE TITLE
Handles are not moved when dragged in groups

### ISSUE THREAD

**Issue by shubhankar** [caleb531/jcanvas#181]
var guid = createGuid();
    $('#canvas').drawLine({
        strokeStyle: '#f00',
        strokeWidth: 5,
        rounded: true,
        startArrow: true,
        arrowRadius: 15,
        arrowAngle: 90,
        x1: 100, y1: 200,
        x2: 160, y2: 145,
        draggable: true,
        layer: true,
        name: 'pointer_' + guid,
        groups: ['pointers_' + guid],
        dragGroups: ['pointers_' + guid],
        handlePlacement: 'both',
        handle: {
            type: 'arc',
            fillStyle: '#f00',
            strokeStyle: '#c33',
            strokeWidth: 1,
            radius: 8
        }
    })
    .drawRect({
        layer: true,
        draggable: true,
        strokeStyle: '#f00',
        strokeWidth: 0,
        groups: ['pointers_' + guid],
        dragGroups: ['pointers_' + guid],        
        x: 130, y: 176,
        width: 68, height: 60
    });

**Comment by caleb531** [comment]
This may not be possible considering how I've designed jCanvas Handles as a plugin apart from the core jCanvas library. If it were possible, then I think it would still be substantially inefficient. Therefore, I have no intention of adding this behavior.

Caleb
