### ISSUE TITLE
How to get resize image width and height ?

### ISSUE THREAD

**Issue by arifkhan2015** [caleb531/jcanvas#184]
I am newb to jcanvas. I am using handle plugin to resize the image.
$('canvas').addLayer({
   type:'image',
   name: 'resizeImage',
   source: 'index.png',
   x: 220, y: 180,
   width: 400, height: 300,
   draggable: true,
   handle: {
                type: 'arc',
		fillStyle: '#fff',
		strokeStyle: '#c33',
		strokeWidth: 2,
		radius: 10
	}
 }).drawLayers();

The image become resizable but now i want to get the height and width of the image. How do i get height and width of the resize image?

**Comment by caleb531** [comment]
First of all, set layer: true within the map of properties for your image. This is good practice in jCanvas land.

Now that you can be sure that your image is a jCanvas layer, the next step is to retrieve it. jCanvas has a built-in getLayer() jQuery method for retrieving layer objects.

var resizeImage = $('canvas').getLayer('resizeImage');

Now, because all jCanvas layers are just simple objects, you can access their properties like so:

resizeImage.width
resizeimage.height

I hope that makes sense. Let me know if you have any questions. :)

Caleb

**Comment by arifkhan2015** [comment]
It works. Thanx for the reply Caleb. 

$('#enableCropping').on('click', function () {

			if (this.checked) {
			  $('canvas').clearCanvas();
				$('canvas').removeLayers();
				$('canvas').drawImage({
					source : 'index.png',
					layer: true,
					name:'orignalImg',
					x: 220, y: 180,
					draggable: false,
					width: 400, height: 300,
				});
				$('canvas').addLayer({
						type: 'rectangle',
						name: 'cropRect',
						draggable: true,
						fillStyle: '#fff',
						opacity:0.1,
						strokeStyle: '#c33',
						strokeWidth: 2,
						x: 160, y: 100,
						width: 150, height: 80,
						handle: {
						  type: 'rectangle',
						  fillStyle: '#fff',
						  strokeStyle: '#c33',
						  strokeWidth: 2,
						  width: 5, height: 5,
						  cornerRadius: 1
						}
				}).drawLayer();
		    } else {
			  $('canvas').clearCanvas();
				$('canvas').removeLayers();
				$('canvas').drawImage({
					source : 'index.png',
					layer: true,
					name:'orignalImg',
					x: 220, y: 180,
					draggable: false,
					width: 400, height: 300,
				});
			
			}
		});

In above code i am using a check box to enable cropping area on image. And this code is working fine. 

Scenerio: when page load first time the image is drwan using simply drawImage() funciton. Now when i check the checkbox to enable cropping layer, i have to redraw the image again as i did in the above code in if case, and then draw a layer with handle on the image. And if i uncheck the box else part clear the canvas and then remove the layers and atlast redraw the image as a layer.

Confusion : 
1) Above code logic is correct or not?
2) If i redraw the image in else part with setting layer to true the image will be drawn but when i move the mouse over the canvas it will get disappeared. So i want to know why this is heppening. 

thanks

**Comment by caleb531** [comment]
You can't use `clearCanvas()` when working with jCanvas layers (that method is part of the basic API, but should not be used with layers). Removing layers and re-adding them is also considered bad practice.

If you need to change the properties of a layer, use [`setLayer()`](http://calebevans.me/projects/jcanvas/docs/manipulateLayers/#setting-layer-properties).
