### ISSUE TITLE
canvas and font size...

### ISSUE THREAD

**Issue by Mark-Mark** [caleb531/jcanvas#185]
Hi,

We have a Windows program that lets the user create graphics, rectangles, circles, text etc.. The user sets the text size for the font. For example, a 12pt Tahoma font is the same size in all other programs run on Windows.

We take the drawing and convert to Javascript so it can be viewed in a browser, a new feature for us. All the shapes are the correct size. The text is not.

I have searched and searched for a solution to the text size on Windows and the text size in the browser, how to make them match.

I cannot be the first to run into this issue and I assume it is something simple I am missing.

Ideas?

Thanks,

Mark

**Comment by Mark-Mark** [comment]
Hello,

Well, there seems to be no fixed conversion value. After much reading and measuring, it appears a Windows font size multiplied by 1.33 gives the best result.

Regards,

Mark

**Comment by caleb531** [comment]
In jCanvas, you can specify font sizes in a few ways. By default, as a string:

```
text: 16
```

Or as a string (with units):

```
text: '12pt'
```

Either way, I'm glad you found a solution.

**Comment by Mark-Mark** [comment]
Hello,

Thanks for the response 

I tired both size options and the size of the font was always the same. Maybe I missed something.

Mark

**Comment by caleb531** [comment]
Ah, you are correct. I can also confirm that this indeed a jCanvas bug. I'll work on pushing out a fix soon.

Caleb

**Comment by caleb531** [comment]
This should be fixed now with the latest commit. :)

**Comment by Mark-Mark** [comment]
Thanks Caleb.
