### ISSUE TITLE
adding and removing "draggable" from layers results in strange behavior

### ISSUE THREAD

**Issue by theOutLiar** [caleb531/jcanvas#187]
Using jcanvas installed from bower - "jcanvas": "~14.11.25"

HTML:

```
    <canvas width="800" height="600"></canvas>
    <button onclick="draw()">Draw</button>
    <button onclick="move()">Move</button>
```

JS:

```
    var _$canvas = $('canvas');
    var _lastX, _lastY;
    var _coords = {};

    var _numberOfPoints = 0;

    function _beginDraw(e) {
        e.preventDefault();

        _numberOfPoints = 0;
        _numberOfPoints++;

        _coords = {};
        _coords['x' + _numberOfPoints] = _lastX = e.offsetX;
        _coords['y' + _numberOfPoints] = _lastY = e.offsetY;

        _$canvas.unbind('mousedown touchstart', _beginDraw);
        _$canvas.on('mouseup touchend', _endDraw);
        _$canvas.on('mouseout touchcancel', _endDraw);
        _$canvas.on('mousemove touchmove', _update);
    }

    function _update(e) {
        e.preventDefault();

        _numberOfPoints++;

        _$canvas.draw({
            type: 'line',
            rounded: true,
            strokeStyle: 'black',
            strokeWidth: 20,
            x1: _lastX,
            y1: _lastY,
            x2: e.offsetX,
            y2: e.offsetY
        });

        _coords['x' + _numberOfPoints] = _lastX = e.offsetX;
        _coords['y' + _numberOfPoints] = _lastY = e.offsetY;
    }

    function _endDraw(e) {
        e.preventDefault();

        _numberOfPoints++;

        _coords['x' + _numberOfPoints] = e.offsetX;
        _coords['y' + _numberOfPoints] = e.offsetY;

        var newLayer = {
            type: 'line',
            rounded: true,
            strokeStyle: 'black',
            strokeWidth: 20,
        };

        for (var coord in _coords) {
            newLayer[coord] = _coords[coord];
        }

        _$canvas.addLayer(newLayer);

        _$canvas.drawLayers();

        _$canvas.unbind('mousemove touchmove', _update);
        _$canvas.unbind('mouseup touchend', _endDraw);
        _$canvas.unbind('mouseout touchcancel', _endDraw);
        _$canvas.on('mousedown touchstart', _beginDraw);
    }

    function _bindDrawEvents() {
        _$canvas.on('mousedown touchstart', _beginDraw);
    }

    function _unbindDrawEvents() {
        _$canvas.unbind('mousedown touchstart', _beginDraw);
        _$canvas.unbind('mousemove touchmove', _update);
        _$canvas.unbind('mouseup touchend', _endDraw);
        _$canvas.unbind('mouseout touchcancel', _endDraw);
    }

    function _disableMoving() {
        _$canvas.setLayers({
                draggable: false,
                bringToFront: false
            })
            .drawLayers();
    }

    function _enableMoving() {
        _$canvas.setLayers({
                draggable: true,
                bringToFront: true
            })
            .drawLayers();
    }

    function draw() {
        _disableMoving();
        _bindDrawEvents();
    }

    function move() {
        _unbindDrawEvents();
        _enableMoving();
    }

    draw();
```

I've got a canvas and two buttons - draw and move - in draw mode the user should be able to draw on the canvas, in move mode the user can move the drawn objects around.

While the user is inputing a stroke in drawing mode, it is drawn directly onto the canvas without a layer. This helps account for performance issues on the iPad. Updating a layer requires too many redraws and kills performance.

When the user finishes a stroke, the stroke is added to the canvas as a layer, and the entire canvas is redrawn. This works perfectly fine upon first load.

When the user switches to move mode, I set the layers' `draggable` property to `true`. Upon moving back from move mode to drawing mode, I set the layer's `draggable` property to `false`.

At this point I expect to be able to draw normally again.

Instead, with the exception of the most recent segment of the stroke, the temporary stroke is being erased - something appears to be triggering a canvas redraw upon mouse move, which is followed by the event I bound to draw the latest segment of the temporary stroke.

**Comment by theOutLiar** [comment]
I saw in the comments on #117  that layers are redrawn upon mousemove - is there a way to disable that when it's not necessary? I can't seem to figure out how the event is bound. The thing that seems odd to me about this is that the mousemove layer redrawing isn't enabled until I've set draggable to true, and then I can't turn it off.

I may have to resort to using a temporary canvas to draw the in-progress stroke, which isn't too bad, but is not ideal.

**Comment by caleb531** [comment]
I've explored the possibility of temporarily unbinding events (as appropriate) in the past, but the logic proved to be too tricky and unreliable.

Also, I *highly* advise *against* unbinding events that jCanvas has bound to the canvas. jCanvas events use the `.jCanvas` namespace,  so if you really needed to bind custom events to the canvas, then you really should be namespacing your events. I also advise against removing and re-adding layers to the canvas, as this is likely to cause all sorts of unforeseeable issues.

In addition, if you intend on using jCanvas layers, then you must set `layer: true` for everything that you draw. Otherwise, such drawings will be erased when jCanvas attempts to redraw the canvas as necessary.
