### ISSUE TITLE
Animated gif...

### ISSUE THREAD

**Issue by Mark-Mark** [caleb531/jcanvas#189]
Hello,

I can load an animated GIF via the drawImage function but, it will not animate/play. The first frame does appear on the canvas. Loading the animated GIF in the browser (drag and drop) and the animation is active/playing.

Ideas to get the GIF to start and stop playing would be ideal.

Regards,

Mark

**Comment by caleb531** [comment]
It's not easily accomplished in HTML5 canvas. See this post:
http://stackoverflow.com/questions/3062229/animated-gif-in-html5-canvas

**Comment by Mark-Mark** [comment]
Hi,

Thanks for the response.

After some testing it looks like I can position the image above the canvas (where it would have been positioned on the canvas) and the GIF will play. I was already using <img> as the source so adding the style values is workable.

Ciao,

Mark
