### ISSUE TITLE
positioning text...

### ISSUE THREAD

**Issue by Mark-Mark** [caleb531/jcanvas#190]
Hello,

I have been able to position text horizontal without issue. I have not been able to position text vertical properly.

Here is some code that shows the issue.

$('canvas').drawText({
  fillStyle: '#9cf',
  layer: true,
  name: 'myText',
  x: 10, y: 100,
  fontSize: 32,
  fromCenter: false,
  fontFamily: 'Verdana, sans-serif',
  text: 'WWW Hello Ê M'
})

.drawRect({
  layer: true,
  strokeStyle: '#000',
  strokeWidth: 1,
  x: 10, y: 100,
  fromCenter: false,
  width: $('canvas').measureText('myText').width,
  height: $('canvas').measureText('myText').height
});

$('canvas').drawLine({
  strokeStyle: '#000',
  strokeWidth: 1,
  x1: 10, y1: 100,
  x2: 300, y2: 100,
});

I really only care about the top position. The top of the text should be at pixel 100. MeasureText agrees but as you see the font extends above the line. And removing that one character, all the font tops are below 100. The Ê was just a test thinking maybe I needed to add an offset for whatever that extended part of the font is named but, the test showed it extending beyond the MeasureText result.

What am I doing wrong?

Cheers,

Mark

**Comment by caleb531** [comment]
Have you tried using the [`baseline` property](http://calebevans.me/projects/jcanvas/docs/properties/#baseline)? That should help you align vertically in the proper manner.

As for the diacritical marks, `drawText()` can't account for all of the subtle nuances in width/height that extended alphabets introduce. Since you are aware that the diacritical mark is present, I would suggest adding to your rectangle's `height` some percentage of the font size to compensate for the difference.

**Comment by Mark-Mark** [comment]
Hi,

Thanks for the response.

I just tried all of the baseline values and none would align to "Y" with fonts not containing diacritical marks. Middle seems to the default. Top moves the text down, that surprised me.

Baseline is affected by fromCenter.
Baseline, align, respectAlign and fromCenter have some conflicts.

So, what needs to be set to align the top/left? Where the top of the text is aligned to the same value returned from MeasureText function.

> can't account for all of the subtle nuances in width/height... 

Yeah, not really. All the data is in the font table.

One method used to return the 'actual' width/height of the exact text tested is to draw it to a 'path' then draw the path and return the resulting size of the canvas.

Did you know the word baseline is not used in the docs on the drawText page?

Mark

**Comment by caleb531** [comment]
Yes, I'm aware. But it's documented on the properties page. I suppose I never really got around to documenting it for the drawText() documentation. But, hey, it's still technically in the documentation. :P

The `baseline` property with a value of `top` implies that the text sits at the top of the invisible bounding box in which it is contained. It's doing exactly what it should.

Anyway, if you want to measure the (x, y) of your text from the top-left corner of the text, `fromCenter` should do just fine. See this code:

```
$('canvas').drawText({
  fillStyle: '#9cf',
  strokeStyle: '#25a',
  strokeWidth: 2,
  x: 0, y: 0,
  fontSize: 48,
  fromCenter: false,
  fontFamily: 'Helvetica, sans-serif',
  text: 'Hello'
});
```

Try viewing the above snippet in the [jCanvas sandbox](http://calebevans.me/projects/jcanvas/sandbox/?code=JCgnY2FudmFzJykuZHJhd1RleHQoewogIGZpbGxTdHlsZTogJyM5Y2YnLAogIHN0cm9rZVN0eWxlOiAnIzI1YScsCiAgc3Ryb2tlV2lkdGg6IDIsCiAgeDogMCwgeTogMCwKICBmb250U2l6ZTogNDgsCiAgZnJvbUNlbnRlcjogZmFsc2UsCiAgZm9udEZhbWlseTogJ0hlbHZldGljYSwgc2Fucy1zZXJpZicsCiAgdGV4dDogJ0hlbGxvJwp9KTs=)—it seems to work as intended.

**Comment by Mark-Mark** [comment]
Hi,

>it seems to work as intended.

Not sure what that means.

The text is not at 0,0. It is at 3,5.

I can see top being off because of diacritical marks but not left.

Try the permeations using Baseline, align, respectAlign and fromCenter and you will see oddities.

Maybe I am missing something.

Mark

**Comment by caleb531** [comment]
The text will not align perfectly with (0, 0) most of the time because most graphic designers don't design any of their font characters to rub against the edge of its invisible bounding box. I'm not sure it is possible to accomplish what you desire in jCanvas or any other canvas-based drawing library.

You shouldn't really need to combine `baseline`, etc. for this. As I see it, `fromCenter: false` is as close as you're going to get.

**Comment by Mark-Mark** [comment]
Yeah. It seems using  fromCenter: false will require some code changes for the X position.

Thanks for your time/help.
