### ISSUE TITLE
Animate everything at same time

### ISSUE THREAD

**Issue by paddotk** [caleb531/jcanvas#191]
Hey,

First of all, thanks for this cool and useful plugin.

I am trying to use jCanvas to create a nicely animated graph, but am having trouble with timing.
What I have right now, is a straight horizontal line, consiting of multiple line parts (x1:100, y1:100,
x2:150, y2:100, x3:200, y3:100, etc.). Upon page load, it animates the line parts one by one up or down, creating a line graph. This works well, except I want every part of it to animate at the same time, as if the line 'folds out' into a graph. Is there a way to do this aside from having to use many different lines? (Funny thing is, with ovals/drawArc everything will only animate at the same time, and not in a sequence..)

Here's what I have for now:
$('canvas#graph1')
.drawLine({
		strokeStyle:'white',
		strokeWidth:4,
		rounded:true,
		x1:100, y1:100,
		x2:150, y2:100,
		x3:200, y3:100,
		x4:250, y4:100,
		x5:300, y5:100,
		x6:350, y6:100,
		x7:400, y7:100,
		name:'l1',
		groups: ['circles'],
		layer:true
	});
$('canvas')
	.animateLayer('l1', { x2:150, y2:125 },300)
	.animateLayer('l1', { x3:200, y3:75 },300)
	.animateLayer('l1', { x4:250, y4:150 },300)
	.animateLayer('l1', { x5:300, y5:180 },300)
	.animateLayer('l1', { x6:350, y6:150 },300)
	.animateLayer('l1', { x7:400, y7:40 },300);

p.s. I don't know how to format this code into proper code markup, sorry.

**Comment by caleb531** [comment]
The path is not composed of separate layers; it's all one layer. Therefore, you can animate all pairs of coordinates at once with a single `animateLayer()` call:

```javascript
$('canvas').animateLayer({
	x2: 150, y2: 125,
	x3: 200, y3: 75,
	x4: 250, y4: 150,
	x5: 300, y5: 180,
	x6: 350, y6: 150,
	x7: 400, y7: 40
}, 300);
```

**Comment by paddotk** [comment]
I hadn't even thought of something so simple... Thanks man.
