### ISSUE TITLE
webkitImageSmoothingEnabled deprecated

### ISSUE THREAD

**Issue by ebigalee** [caleb531/jcanvas#192]
Get an error that says webkitImageSmoothingEnabled is deprecated. Replaced with imageSmoothingEnabled on about line 8 in the min version and no more error. Just FYI.

**Comment by caleb531** [comment]
Thanks, but I'm already aware of this. However, it is just a notice, and not an actual error. However, I will remove it in the next release.

Caleb

**Comment by ebigalee** [comment]
Figured you did. Using it in class tomorrow and I'm sure I will have students asking so figured I should let you know in case. 

  Erika Lee

**Comment by caleb531** [comment]
Oh, well, in that case, allow me to push the release that includes the fix. Stand by. ;)

Caleb
