### ISSUE TITLE
Refreshing image ...

### ISSUE THREAD

**Issue by mb-nrl** [caleb531/jcanvas#193]
I'm accessing an image that changes over time, but its URL does not (and cannot) change.  The site uses headers to request no-cache from the browser.

Before I switched to jcanvas I would simply repeatedly reset the src of the Image to the same URL, and then redraw the image on load, but with jcanvas it was a bit less obvious ...  I finally figured out that if I pass in an Image as a source to the layer I can still control its source value and achieve the desired effect ... 

The obvious manipulation of the source parameter of the layer did not produce the expected results; the image simply would not get reloaded (i.e. no HTTP request would not be made).  

<code>

	<body >
		<canvas id="imgD" width=150 height=150 ></canvas>

		<script type="text/javascript" type="text/javascript">
		var c=document.getElementById("imgD");
		var ctx=c.getContext("2d");
		var img = new Image();
		img.src = "../images/init-static-image.png";

				$("#imgD")
				.drawImage({
					layer: true,
					name: "feed",
					fromCenter: false,
					width: 128,
					height: 128,
					x: 0,
					y: 0,
					source: img,

					load: function (layer) {
						$(this).drawLayers();
					},

					click: function (layer){

								img.src = "http://localhost:9091/dynamic-img.jpg";

						}
					});

		</script>
	</body>

</code>

In addition, in some versions of this code I have to include .drawLayers() in the click function or the image is not redrawn on first click, which causes the image to flicker in and out on every click afterwards.

**Comment by caleb531** [comment]
You say you solved it but you... didn't? I'm a bit confused. Please clarify what the issue is.

Thanks,
Caleb

**Comment by mb-nrl** [comment]
The above code worked the way I wanted it as a standalone bit, but when I put it into a larger project, I had to add an extra drawLayers() call in click method which makes the image flicker on every click.  

I was simply trying to figure out how to implement the code below in jcanvas ...
<code>
	<body >
		<canvas id="imgD" width=150 height=150 ></canvas>

		<script type="text/javascript" type="text/javascript">
		var c=document.getElementById("imgD");
		var ctx=c.getContext("2d");
			var img = new Image();

			img.onload = function() {
				ctx.clearRect(0, 0, c.width, c.height);
				ctx.drawImage(this, 0, 0);
			};

			img.src = "../images/init-static-img.png";

			c.addEventListener('click', function()
				{
					img.src = "http://localhost:9091/dynamic-img.jpg";
				});

		</script>
	</body>
</code>

**Comment by caleb531** [comment]
Calling `drawLayers()` on `load`:

```
load: function (layer) {
    $(this).drawLayers();
},
```

should not be necessary, and is likely to be causing the extra flicker. You should remove that call and if you find it necessary, call `drawLayers()` after changing the `src`.

**Comment by mb-nrl** [comment]
Here is what I see ...

- Removing all drawLayers calls from above example does make it work without flicker, but ...  It is not very intuitive or consistent although cool.  But it does not work on the first click in my larger project so maybe it's just a lucky timing.  The larger project has more canvas and layers so image loading times could be affected.  

- drawLayers call in click, always makes it flicker.

I.e. it does look like the code in load is superfluous ...

**Comment by caleb531** [comment]
When does the flickering occur? Only when the image changes to the next source on click?

I might recommend you try converting your `drawImage` call to an `addLayer` call (with `type: 'image'`), so long as you call `drawLayers` afterwards at some point (whenever you're ready to draw the canvas.

Something like this:

```
$('#imgD').addLayer({
    type: 'image',
    ...
})
.drawLayers();
```

**Comment by jimd33463** [comment]
If you copy/paste the below into the 'sandbox' (the sandbox featured on the jcanvas website) the canvas flickers when you mouse over it.  What is the solution to correct this? I've tried removing the extra drawLayers calls, but it didn't help.  It seems like the problem is resolved when I remove all the mouse events.

$('canvas').addLayer({
  type: 'image',
  source: 'http://pngimg.com/uploads/koala/koala_PNG10.png?i=1',
  x: 150, y: 150,
  click: function(layer){
    console.log("click");
  },
  mouseover: function(layer){
    console.log("mouseover");
  },
  mouseout: function(layer){
    console.log("mouseout");
  }
}).drawLayers();

$('canvas')
.addLayer({
  type: 'rectangle',
  name: 'redBox',
  fillStyle: '#c99',
  x: 180, y: 150,
  width: 100, height: 100,
  click: function(layer){
    console.log("click");
  },
  mouseover: function(layer){
    console.log("mouseover");
  },
  mouseout: function(layer){
    console.log("mouseout");
  }
}).drawLayers();

$('canvas')
.addLayer({
  type: 'rectangle',
  name: 'greenBox',
  fillStyle: '#585',
  x: 150, y: 200,
  width: 100, height: 100,
  click: function(layer){
    console.log("click");
  },
  mouseover: function(layer){
    console.log("mouseover");
  },
  mouseout: function(layer){
    console.log("mouseout");
  }
}).drawLayers();

$('canvas')
.addLayer({
  type: 'rectangle',
  name: 'blueBox',
  fillStyle: '#36b',
  x: 230, y: 180,
  width: 100, height: 100,
  click: function(layer){
    console.log("click");
  },
  mouseover: function(layer){
    console.log("mouseover");
  },
  mouseout: function(layer){
    console.log("mouseout");
  }
}).drawLayers();

**Comment by caleb531** [comment]
Hey, @jimd33463. Sorry I've been so late in replying to your message, but rest assured that I haven't forgotten about it. I'll try to respond back with a solution on Saturday.

**Comment by caleb531** [comment]
@jimd33463 Alright, I see no flickering of the image on my end on any of the browsers I've tested (Chrome, Firefox, and Safari on macOS). What browser

Either way, you could try "preloading" the image by loading it as an external `<img>` element, then referencing that DOM element. This has been known to work for some jCanvas users who encountered similar flickering issues.

```html
<img src="http://pngimg.com/uploads/koala/koala_PNG10.png?i=1" alt="Koala" id="koala" />
```

```js
$('canvas').drawImage({
  source: $('#koala')[0],
  x: 50, y: 50,
  width: 100,
  fromCenter: false
});
```

**Comment by jimd33463** [comment]
Thanks Caleb, but I did already try that too.  I ended up solving it by moving the image out of the canvas and putting in a separate div positioned behind it.

On Dec 16, 2017, at 3:32 PM, Caleb Evans <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimd33463<https://github.com/jimd33463> Alright, I see no flickering of the image on my end on any of the browsers I've tested (Chrome, Firefox, and Safari on macOS). What browser

Either way, you could try "preloading" the image by loading it as an external <img> element, then referencing that DOM element. This has been known to work for some jCanvas users who encountered similar flickering issues.

<img src="http://pngimg.com/uploads/koala/koala_PNG10.png?i=1" alt="Koala" id="koala" />

$('canvas').drawImage({
  source: $('#koala')[0],
  x: 50, y: 50,
  width: 100,
  fromCenter: false
});
