### ISSUE TITLE
_scaleCanvas nukes ctx.setLineDash() in Chrome.

### ISSUE THREAD

**Issue by tdestro** [caleb531/jcanvas#194]
In chrome 43.0.2357.81 (64-bit), jcanvas.js, line 2546, function _scaleCanvas.  In firefox it actually works the way it is.

The line ctx.translate( params.x, params.y ); nukes the ctx.setLineDash() setting made in earlier in _setGlobalProps().

calling _setGlobalProps() again afterwards gives you the expected dashed border.

This is enough to do it, I end up with a solid border.

$('canvas').drawArc({
                strokeStyle: '#fb881b',
                strokeWidth: 1,
                strokeDash: [3,3],
                radius: 50,
                x: halfWidth,
                y: halfHeight,
                scale: holeScale
            });

**Comment by caleb531** [comment]
Hmm, how strange.

Anyway, pushed a potential fix to [feature/strokeDash](https://github.com/caleb531/jcanvas/pull/195). @tdestro: please test and let me know if it fixes the issue (and if it doesn't break anything else).

Caleb

**Comment by tdestro** [comment]
This works.

**Comment by caleb531** [comment]
Great! I'll merge it in now. :)
