### ISSUE TITLE
Limiting group drag

### ISSUE THREAD

**Issue by djnolder** [caleb531/jcanvas#196]
I've recently run into a problem. When I "dragGroups" layers together, they don't appear to fire each other's drag events. This is causing a problem for me, because I use some simple code to only allow dragging on the x axis .If you try to drag any layer from the group up or down, the other layers will move up or down (chaotically), even though they shouldn't.

Demo: https://jsfiddle.net/djnolder/w3f4s90d/4/

**Comment by caleb531** [comment]
I see. Well, I think it's about time that I add a new jCanvas property to solve your issue and add convenience to the lives of many other jCanvas programmers (it's not the first time I've seen jCanvas devs implement restricted drag behavior).

Therefore, behold! I give you the `restrictDragToAxis` property (possible values are `x` and `y`). I've [modified your fiddle](https://jsfiddle.net/w3f4s90d/5/) to utilize the new property. The updated jCanvas build (including source and minified) is available on `feature/restrict-drag` branch. Once I receive confirmation that the new property will solve this issue of yours, I can merge it in as an official jCanvas release.

**Comment by djnolder** [comment]
Works like a champ. Thanks for such a quick response.
