### ISSUE TITLE
Flipping canvas horizontally / vertically

### ISSUE THREAD

**Issue by bahriddin** [caleb531/jcanvas#197]
Please help me to flip canvas hor/vert. As I understood, I need to use setPixels() method and swap every pixel's r, g, b colors. But I need to get coordinates of each pixel to do such kind of manipulation.

**Comment by caleb531** [comment]
I propose a much easier solution. Use `scaleCanvas` alongside `restoreCanvas` to scale the entire canvas initially, and then restore the scaling after all layers has been drawn (this is necessary; it prevents the scaling from being compounded).

```javascript
var $canvas = $('canvas')

$canvas
.scaleCanvas({
  layer: true,
  // Change these values (1 or -1) according to your needs
  // A value of -1 flips that axis. A value of 1 doesn't do anything
  scaleX: -1,
  scaleY: 1,
  // The center of transformation must be at the center of the canvas
  x: $canvas.width() / 2,
  y: $canvas.height() / 2
})
.drawArc({
  layer: true,
  draggable: true,
  fillStyle: '#000',
  x: 100, y: 100,
  radius: 50
})
// Restore the transformation state of the canvas
.restoreCanvas({
  layer: true
});
```
