### ISSUE TITLE
Disappearing text when other shapes are on canvas

### ISSUE THREAD

**Issue by napcrisis** [caleb531/jcanvas#199]
Hi Caleb,

It seems that when i add text onto the canvas as well as a draggable shape, the text will disappear once my cursor goes into the canvas. Is there a way to change that?

Sample code
$('canvas').drawText({
  fillStyle: '#636363',
  x: 30, y:30,
  fontSize: 20,
  fontFamily: 'Verdana, sans-serif',
  text: 1
});
$('canvas').drawArc({
  draggable: true,
  fillStyle: '#000',
  x: 100, y: 100,
  radius: 50
});

Tommy

**Comment by caleb531** [comment]
You need to make both of your drawings jCanvas layers. For future reference, you should always specify `layer: true` when you specify `draggable: true`.

Here's the modified code that will work:

```
$('canvas').drawText({
layer: true,
fillStyle: '#636363',
x: 30, y:30,
fontSize: 20,
fontFamily: 'Verdana, sans-serif',
text: 1
});
$('canvas').drawArc({
layer: true,
draggable: true,
fillStyle: '#000',
x: 100, y: 100,
radius: 50
});

```

**Comment by napcrisis** [comment]
hey caleb, sorry i just saw your comment on https://github.com/caleb531/jcanvas/issues/103
=) thanks for your quick reply
