### ISSUE TITLE
is there an easy way to put text on drawn shapes?

### ISSUE THREAD

**Issue by napcrisis** [caleb531/jcanvas#200]
Hi caleb,

I have a need of labelling shapes which i think its a common use case but i can't find the example on your API. The only way i can think of is to programmatically create a text in the middle of the shape and create a onmove listener to move the text when shape is moved.

Do you have an alternate suggestion?

Tommy

**Comment by caleb531** [comment]
Nope—how you've described it is the best way to do create text labels at the moment. Also, I think you meant `ondrag`, not `onmove`.

Caleb

**Comment by napcrisis** [comment]
it works quite well =)

var name="nameOfDrawing";
$('canvas').drawArc({
	draggable:true,
	name:name,
	fillStyle: '#000',
	x: 100, y: 100,
	radius: 50,
	drag: function(layer) {
		var text = $('canvas').getLayer(layer.name+"_label");
		text.x = layer.x;
		text.y = layer.y;
	},
});
function createTextFor(text, name){
	var canvasObj = $('canvas').getLayer(name);
	$('canvas').drawText({
	  fillStyle: '#666',
	  layer:true,
	  name: name+"_label",
	  x: canvasObj.x, y: canvasObj.y,
	  fontSize: 12,
	  fontFamily: 'Verdana, sans-serif',
	  text: text
	});
}
createTextFor("something",name);
