### ISSUE TITLE
jhandles plugin clear handles?

### ISSUE THREAD

**Issue by kimfree** [caleb531/jcanvas#205]
Hello, I am interested in using the jHandles plugin for re-sizeable elements, but I was wondering if after the re-sizing is done is there a way to "clear" or remove the re-sizeable handles?

**Comment by caleb531** [comment]
It's not documented, but each parent layer (the layer you attach handles to) has a `_handles` property which is an array containing references to all of the handle layers. If you loop through that list, use `removeLayer` to remove each handle layer, then clear the list by setting its `length` to `0`, you're done.

```javascript
var $canvas, handle, h;
if ( layer._handles ) {
	$canvas = $( '#myCanvas' );
	// Remove handles from layer
	for ( h = 0; h < layer._handles.length; h += 1 ) {
		handle = layer._handles[h];
		$canvas.removeLayer( handle );
	}
        // Empty the list
	layer._handles.length = 0;
}
```

**Comment by kimfree** [comment]
what if i want to be able to "toggle" the handles for like an "edit" mode etc?

**Comment by caleb531** [comment]
Instead of using `removeLayer()`, toggle the `visible` property of each between `true` and `false` using the `setLayer()` method. See [the docs for details on setLayer].(http://projects.calebevans.me/jcanvas/docs/manipulateLayers/#setting-layer-properties).

However, an easier way would be to pass `layer._handles` as the first argument to `setLayerGroup`, which accepts an array of layers in addition to a group name as the method's first argument.

```javascript
$('#myCanvas').setLayerGroup(layer._handles, {
    visible: false
})
.drawLayers();
```

**Comment by kimfree** [comment]
worked like a charm, tyvm!

**Comment by gnetsys** [comment]
Hi, I am trying to show/hide handles on mouseOver/mouseOut.  (am working with jComponent.org)

   
            canvas.drawImage({

                source: source,
                draggable: true,
                x: width / 2, y: height / 2,
                width: width / 2,
                height: height / 2,

               mouseover: function () {
                    var handle = {
                        type: 'rectangle',
                        strokeStyle: '#777',
                        fillStyle: '#fff',
                        strokeWidth: 1,
                        width: 10, height: 10
                    };
                return handle;
                },

                mouseout: function handleHide(e) {
                    return canvas.setLayer(layer._handles, {
                        visible: false // set to true instead to show the layer again
                    }).drawLayers();
                },

                resizeFromCenter: false

            });

**Comment by caleb531** [comment]
I think you meant for your `handleHide` function to accept `layer` as a parameter (and not `e`), like so:

```js{
    mouseout: function handleHide(layer) {
        return canvas.setLayer(layer._handles, {
            visible: false // set to true instead to show the layer again
        }).drawLayers();
    }
}
```

**Comment by gnetsys** [comment]
My bad! I have updated my code to use animation: but the same issue exist..

            canvas.drawImage({

                source: source,
                draggable: true,

                x: width / 2, y: height / 2,
                width: width / 2,
                height: height / 2 - 100,
                layer: true,

                handle: {
                    type: 'rectangle',
                    strokeStyle: '#7CDC7C',
                    strokeWidth: 1,
                    width: 10, height: 10,
                },

                mouseover: function(layer) {
                    self.animateLayer(layer, {
                        fillStyle: '#000'
                    }, 500);
                },
                mouseout: function(layer) {
                    canvas.animateLayer(layer, {
                        fillStyle: '#dc3'
                    }, 500);
                },

                resizeFromCenter: false

            });

**Comment by gnetsys** [comment]
My bad ... its error. I have changed my approach for the mouseOver/ mouseOut methods

canvas.drawImage({

                layer: true,
                source: source,
                draggable: true,

                x: width / 2, y: height / 2,
                width: width / 2,
                height: height / 2 - 100,

                mouseover: function(layer) {
                    canvas.animateLayer(layer, {
                       fillStyle: '#000'
                    }, 500);
                },
                mouseout: function(layer) {
                    canvas.animateLayer(layer, {
                        fillStyle: 'transparent'
                    }, 500).drawLayers();
                },

                handle: {
                    type: 'rectangle',
                    fillStyle: '#ddd',
                    strokeWidth: 1,
                    width: 10, height: 10,
                },

                resizeFromCenter: true

            });

how do I set the colour or the handle ?

**Comment by caleb531** [comment]
If you want to set the color of all handles, use `setLayerGroup` ([docs here](http://projects.calebevans.localhost:8888/jcanvas/docs/manipulateLayers/#setting-layer-group-properties)) or `animateLayerGroup` ([docs here](http://projects.calebevans.localhost:8888/jcanvas/docs/animateLayers/#animating-layer-groups)) to animate the `fillStyle`/`strokeStyle` properties for `layer._handles`. The `*LayerGroup` methods are able to operate on any arbitrary array of layers, so passing `layer._handles` should work just fine.

**Comment by gnetsys** [comment]
It worked.... thanks!
