### ISSUE TITLE
click through transparency

### ISSUE THREAD

**Issue by kimfree** [caleb531/jcanvas#206]
Hi I am interested in drawing an overlaying rectangle on my canvas, I have tried using the rectangle method with a transparent fill, and also drawing a rectangle using lines but the layers underneath are visible but not realizable or draggable, how can I overcome this?

**Comment by caleb531** [comment]
I *think* I understand what you're asking for.

You can set `intangible: true` on any jCanvas layer (either when you create the layer or after the fact), and any mouse events targeted at that layer will pass through to any layer underneath (as though the former layer did not even exist).

**Comment by caleb531** [comment]
0

**Comment by kimfree** [comment]
Thank you, that is what I was looking for.
