### ISSUE TITLE
exporting canvas

### ISSUE THREAD

**Issue by rads17** [caleb531/jcanvas#207]
HI there,

I'm working on an application that lets users upload their own images and draw etc, and what I'm interested in doing is exporting a specific portion of that drawing space to an image.

So I look into using the toDataURL() method to take my larger, "workspace" canvas and convert it to an image and then draw that image on my specific size "ouputcanvas" so I have a canvas with only the correct section of the original canvas which I then want to convert to an image, again using toDataURL().

I'm having difficulty achieving this as nothing is appearing on the section canvas.

var workspaceImg = document.getElementById("workspaceCanvas").toDataURL("image/png");
        var $previewCanvas = $('#previewCanvas');
        $previewCanvas.insertImage(workspaceImg);
   
where insertImage is just a wrapper function for adding a layer and calling drawlayers (insertImage works fine for drawing on the main canvas)

I suspect it has to do with the interaction of toDataURL and a canvas with multiple layers?

**Comment by caleb531** [comment]
Hi, @rads17.

I'm not sure how I can help with what you've provided, as I feel that the problem is rooted in whatever code you have in your `insertImage()` method. If you could please share that here (or email me directly), I can further assist you. :)

Caleb

**Comment by rads17** [comment]
Here is a fiddle of what I'm trying to do : http://jsfiddle.net/eypj69ax/2/ 

Upload an image, put it on the canvas by clicking the thumbnail then press "Save" and I want to essentially "Crop" a section of the workspace canvas into an image, so I'm trying to do that by converting it to an image and redrawing on a smaller canvas which I will then convert to the "cropped image"

**Comment by caleb531** [comment]
Well, for one, you have an TypeError in your fiddle if I click the uploaded image twice:

```
Uncaught TypeError: $canvas.removeImage is not a function
```

Secondly, I believe I found the root of the issue. The HTML5 canvas `toDataURL()` method returns a data URL *image* representing the image; it is not an object. Furthermore, you are attempting to access the `src` property of that string—which is undefined—and pass it to the image layer's `source`. In other words, pass `img` instead of `img.src`.
