### ISSUE TITLE
rotating individual shape

### ISSUE THREAD

**Issue by kimfree** [caleb531/jcanvas#208]
Hi just a quick question about rotating an individual shape, I noticed on the docs it is done by adding the "rotate" parameter, but it was used inside of a drawRect method, what if I have already drawn something and want to rotate it?

**Comment by kimfree** [comment]
Also is it possible to implement a flip vertical/flip horizontal type functionality? I was thinking it might be possible by manually re-sizing from the left edge over past the right?

**Comment by caleb531** [comment]
You can use the built-in jCanvas method `setLayer()` ([documentation here](http://projects.calebevans.me/jcanvas/docs/manipulateLayers/)) for that.

Also, use `scaleX: -1` or `scaleY: -1` to flip horizontally or vertically, respectively.

**Comment by kimfree** [comment]
Thanks Caleb,

One more related question. I am trying to implement "selecting" a layer, so I added the click: 
```function(layer){
                	$canvas.selectedLayer = layer.name;			
                    console.log("You selected " + $canvas.selectedLayer);
            	}
```
function, (I'm using jhandles) so this prints out the correct info but when I later try to access the .selectedLayer using this 
```
$("#rotate45").click(function() {
        console.log("rotating " + $canvas.selectedLayer + " 45 degrees");
        $canvas.animateLayer($canvas.selectedLayer, {
  rotate: '+=45'},500);

    });
```

I get undefined as the selectedLayer?

Also is there a way to draw like an outline around the image/rect that is draw on the layer to show it as a selected state? All my layers just contain a single image so even just drawing an outline around the image contained on the layer?

**Comment by caleb531** [comment]
See jQuery's `data()` method, as it is the proper way to store data on jQuery elements:
https://api.jquery.com/data/

**Comment by kimfree** [comment]
hmm the shadow idea looks good, but when I try adding a shadow using `setLayers()` it doesn't seem to work?
here is a link to the sandbox:

http://projects.calebevans.me/jcanvas/sandbox/?code=JCgnY2FudmFzJykuZHJhd0FyYyh7CiAgZmlsbFN0eWxlOiAnIzU4ZCcsCiAgbmFtZToidGVzdCIsCiAgeDogNTAsIHk6IDUwLAogIHJhZGl1czogMzAKfSk7CgovLyBTZXQgcHJvcGVydGllcyBvZiBhbGwgbGF5ZXJzCiQoJ2NhbnZhcycpLnNldExheWVycyh7CiAgc2hhZG93Q29sb3I6ICcjMDAwJywKICBzaGFkb3dCbHVyOiAxMCwKfSkKLmRyYXdMYXllcnMoKTs=

**Comment by caleb531** [comment]
Set `layer: true` on the circle. Otherwise, it will not be treated as a jCanvas layer.

**Comment by kimfree** [comment]
Thank you!

**Comment by kimfree** [comment]
you know I just realized I'm using handles so I can just toggle the handles visible as a selected state.

**Comment by caleb531** [comment]
Yep, that'll work too. :)

**Comment by kimfree** [comment]
is there anyway I could "add" a 5th handle  (much like how powerpoint works) as a rotation handle?

**Comment by caleb531** [comment]
jCanvas Handles does not currently support rotation; implementing it would be tricky on my part, and so it is not a feature I plan to add in the near future.

**Comment by kimfree** [comment]
Is there anyway to merge two layers?

I want to have like [Icon] [Words].

I am making a Stats thing where the icon would be a symbol for the stat and the words would be a number.

So I can use drawImage and drawText but then when I move them around I want them to like be stuck together you know what I mean?

**Comment by kimfree** [comment]
here is what I have so far

http://projects.calebevans.me/jcanvas/sandbox/?code=dmFyICRjYW52YXMgPSAkKCdjYW52YXMnKTsKdmFyIHN0YXQgPSAiRml2ZSI7CnZhciBzdGF0SWNvbiA9IG5ldyBJbWFnZSgpOwpzdGF0SWNvbi5zcmMgPSAiaHR0cHM6Ly9wbGF5Zm91cnNxdWFyZS5zMy5hbWF6b25hd3MuY29tL3ByZXNzL2xvZ28vcG93ZXJlZEJ5Rm91cnNxdWFyZV8zNngzNi5wbmciOwpzdGF0SWNvbi53aWR0aCA9IDM2OwpzdGF0SWNvbi5oZWlnaHQgPSAzNjsKCiRjYW52YXMuYWRkTGF5ZXIoewogIHR5cGU6ICd0ZXh0JywKICBmaWxsU3R5bGU6ICIjMDAwIiwKICBmb250U2l6ZTogMzIsCiAgc3Ryb2tlU3R5bGU6ICcjMjVhJywKICBzdHJva2VXaWR0aDogMCwKCiAgeDogMTUwLAogIHk6IDEwMCwKICBmb250RmFtaWx5OiAiQXJpYWwiLAogIHRleHQ6IHN0YXQsCiAgbmFtZTogc3RhdAoKfSkKLmRyYXdMYXllcnMoKTsKCgp2YXIgbXl0ZXh0ID0gJGNhbnZhcy5nZXRMYXllcihzdGF0KTsKJGNhbnZhcy5tZWFzdXJlVGV4dChteXRleHQpOwoKdmFyIG9yaWdXaWR0aCA9IG15dGV4dC53aWR0aDsKdmFyIG9yaWdIZWlnaHQgPSBteXRleHQuaGVpZ2h0OwoKJGNhbnZhcy5hZGRMYXllcih7CiAgdHlwZTogJ2ltYWdlJywKICBkcmFnZ2FibGU6IHRydWUsCiAgbmFtZTpzdGF0SWNvbi5zcmMsCiAgc291cmNlOnN0YXRJY29uLnNyYywKICB4OiBteXRleHQueC1vcmlnV2lkdGgvMi1zdGF0SWNvbi53aWR0aC8yLAogIHk6IG15dGV4dC55LAogIHdpZHRoOiBzdGF0SWNvbi53aWR0aCwKICBoZWlnaHQ6IHN0YXRJY29uLmhlaWdodCwKCn0pLmRyYXdMYXllcnMoKTsKCnZhciBteUljb24gPSAkY2FudmFzLmdldExheWVyKHN0YXRJY29uLnNyYyk7Cgp2YXIgb3JpZ0ljb25XaWR0aCA9IG15SWNvbi53aWR0aDsKdmFyIG9yaWdJY29uSGVpZ2h0ID0gbXlJY29uLmhlaWdodDsKCiRjYW52YXMuYWRkTGF5ZXIoewogIHR5cGU6ICdyZWN0YW5nbGUnLAogIGRyYWdnYWJsZTogdHJ1ZSwKICBuYW1lOnN0YXQrImhhbmRsZXMiLAogIHN0cm9rZVN0eWxlOiAnI2MzMycsCiAgc3Ryb2tlV2lkdGg6IDAsCiAgeDogbXl0ZXh0Lngtc3RhdEljb24ud2lkdGgvMiwgCiAgeTogbXl0ZXh0LnksCiAgd2lkdGg6IHN0YXRJY29uLndpZHRoK29yaWdXaWR0aCwgaGVpZ2h0OiBzdGF0SWNvbi5oZWlnaHQsCiAgaGFuZGxlOiB7CiAgICB0eXBlOiAnYXJjJywKICAgIHN0cm9rZVN0eWxlOiAnI2MzMycsCiAgICBzdHJva2VXaWR0aDogMiwKICAgIHJhZGl1czogNQogIH0sCiAgaGFuZGxlbW92ZTogZnVuY3Rpb24obGF5ZXIpIHsKICAgICRjYW52YXMuc2V0TGF5ZXIobXl0ZXh0LCB7CiAgICAgIHNjYWxlWDogbGF5ZXIud2lkdGggLyBvcmlnV2lkdGgsCiAgICAgIHNjYWxlWTogbGF5ZXIuaGVpZ2h0IC8gb3JpZ0hlaWdodAogICAgfSk7CiAgICAkY2FudmFzLnNldExheWVyKG15SWNvbiwgewogICAgICBzY2FsZVg6IGxheWVyLndpZHRoIC8gb3JpZ1dpZHRoLAogICAgICBzY2FsZVk6IGxheWVyLmhlaWdodCAvIG9yaWdIZWlnaHQKICAgIH0pOwogICAgJGNhbnZhcy5kcmF3TGF5ZXJzKCk7CiAgfSwKICBkcmFnOiBmdW5jdGlvbihsYXllcikgewogICAgJGNhbnZhcy5zZXRMYXllcihteXRleHQsIHsKICAgICAgeDogbGF5ZXIueCtteUljb24ud2lkdGgvMiwKICAgICAgeTogbGF5ZXIueQogICAgfSk7CiAgICAkY2FudmFzLnNldExheWVyKG15SWNvbiwgewogICAgICB4OiBsYXllci54LW9yaWdXaWR0aC8yLAogICAgICB5OiBsYXllci55CiAgICB9KTsKICAgICRjYW52YXMuZHJhd0xheWVycygpOwogIH0KICAgICAgICAgICAgfSk7CiAgICAgICAgICAgICAgICAvLyBSZWRyYXcgbGF5ZXJzIHRvIGVuc3VyZSBoYW5kbGVzIGFyZSBvbiB0b3Agb2YgcmVjdGFuZ2xlCiAgICAgICAgICAgIAogICAgICAgICAgICAgICAgJGNhbnZhcy5kcmF3TGF5ZXJzKCk7

**Comment by caleb531** [comment]
A tricky problem indeed. You need to have the coordinates (`x`, `y`) for both the gear and text to be the same. Then, if you translate each layer by the necessary respective amounts (you might need to take into account the scale factor), *then* when you scale either of those layers, they will scale from that same center point (which should also be equal to the center of the rectangular bounding box).

**Comment by kimfree** [comment]
I'm not sure what you mean by having the same coordinates and then translating?

**Comment by caleb531** [comment]
See the below example (try it in the jCanvas Sandbox):

```javascript
$('canvas')
.drawArc({
  layer: true,
  name: 'circle',
  fillStyle: '#c33',
  x: 150,
  y: 150,
  translateX: -50,
  translateY: -50,
  radius: 30
})
.animateLayer('circle', {
  scale: 1.8
}, 3000);
```

By default, layer transformations (like `scale` or `rotate`) are performed relative to the center of the respective layer (which is usually `x`/`y`). You can offset this position of the layer without changing this center of transformation with `translateX` and `translateY`.

**Comment by kimfree** [comment]
Oh I see,

Thank you very much! The translateX helped a lot for the scaling, however now my "rectangle" handles don't follow the resized shape.

```
var $canvas = $('canvas');
var stat = "Five";
var statIcon = new Image();
statIcon.src = "https://playfoursquare.s3.amazonaws.com/press/logo/poweredByFoursquare_36x36.png";
statIcon.width = 36;
statIcon.height = 36;

$canvas.addLayer({
  type: 'text',
  fillStyle: "#000",
  fontSize: 32,
  strokeStyle: '#25a',
  strokeWidth: 0,

  x: 150,
  y: 100,
  fontFamily: "Arial",
  text: stat,
  name: stat

})
.drawLayers();


var mytext = $canvas.getLayer(stat);
$canvas.measureText(mytext);

var origWidth = mytext.width;
var origHeight = mytext.height;

$canvas.addLayer({
  type: 'image',
  name:statIcon.src,
  source:statIcon.src,
  x: mytext.x,
  y: mytext.y,
  translateX:-origWidth/2-statIcon.width/2,
  width: statIcon.width,
  height: statIcon.height,

}).drawLayers();

var myIcon = $canvas.getLayer(statIcon.src);

var origIconWidth = statIcon.width;
var origIconHeight = statIcon.height;

$canvas.addLayer({
  type: 'rectangle',
  draggable: true,
  name:stat+"handles",
  strokeStyle: '#c33',
  strokeWidth: 0,
  x: myIcon.x-myIcon.width/2,
  y: myIcon.y,
  width: myIcon.width+mytext.width, 
  height: myIcon.height,
  handle: {
    type: 'arc',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 5
  },
  handlemove: function(layer) {
    $canvas.setLayer(mytext, {
      scaleX: (layer.width-myIcon.width) / origWidth,
      scaleY: layer.height / origHeight
    });
    $canvas.setLayer(myIcon, {
      scaleX: (layer.width-myIcon.width) / origWidth,
      scaleY: layer.height / origHeight
    });
    $canvas.drawLayers();
  },
  drag: function(layer) {
    $canvas.setLayer(mytext, {
      x: layer.x+myIcon.width/2,
      y: layer.y
    });
    $canvas.setLayer(myIcon, {
      x: layer.x+myIcon.width/2,
      y: layer.y
    });
    $canvas.drawLayers();
  }
            });
// Redraw layers to ensure handles are on top of rectangle

$canvas.drawLayers();
```

**Comment by caleb531** [comment]
I see you are translating the image, but not the text. As I mentioned, the `x` and `y` of the text *and* the image should be the same initially (provided that you translate each respective layer to position them as you so desire). Because the `x` and `y` properties define where the center of transformation is, scaling either shape will scale them from the same point in space, thus making the math easier on your part.

**Comment by kimfree** [comment]
Hmmm, so I made the rectangle's x 150 and y 100, then set the text & the image to the same x,y and translated them but I still get the same behaviour where they scale outside of the rectangle, I think it has to do with how I am scaling them? 

```
var $canvas = $('canvas');
var stat = "Five";
var statIcon = new Image();
statIcon.src = "https://playfoursquare.s3.amazonaws.com/press/logo/poweredByFoursquare_36x36.png";
statIcon.width = 36;
statIcon.height = 36;


$canvas.addLayer({
  type: 'image',
  name:statIcon.src,
  source:statIcon.src,
  x: 150,
  y: 100,
  width: statIcon.width,
  height: statIcon.height,

}).drawLayers();

var myIcon = $canvas.getLayer(statIcon.src);

var origIconWidth = statIcon.width;
var origIconHeight = statIcon.height;


$canvas.addLayer({
  type: 'text',
  fillStyle: "#000",
  fontSize: 32,
  strokeStyle: '#25a',
  strokeWidth: 0,
  x: 150,
  y: 100,
  translateX:+statIcon.width/2,
  fontFamily: "Arial",
  text: stat,
  name: stat

})
.drawLayers();


var mytext = $canvas.getLayer(stat);
$canvas.measureText(mytext);

var origWidth = mytext.width;
var origHeight = mytext.height;


$canvas.setLayer(myIcon.name, {
    translateX:-myIcon.width
});

$canvas.setLayer(mytext.name, {
    translateX:+myIcon.width/2
});

$canvas.addLayer({
  type: 'rectangle',
  draggable: true,
  name:stat+"handles",
  strokeStyle: '#c33',
  strokeWidth: 0,
  x: 150,
  y: 100,
  width: myIcon.width+mytext.width, 
  height: myIcon.height,
  handle: {
    type: 'arc',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 5
  },
  handlemove: function(layer) {
    $canvas.setLayer(mytext, {
      scaleX: (layer.width-myIcon.width) / origWidth,
      scaleY: layer.height / origHeight
    });
    $canvas.setLayer(myIcon, {
      scaleX: (layer.width-myIcon.width) / origWidth,
      scaleY: layer.height / origHeight
    });
    $canvas.drawLayers();
  },
  drag: function(layer) {
    $canvas.setLayer(mytext, {
      x: layer.x,
      y: layer.y
    });
    $canvas.setLayer(myIcon, {
      x: layer.x,
      y: layer.y
    });
    $canvas.drawLayers();
  }
            });
// Redraw layers to ensure handles are on top of rectangle

$canvas.drawLayers();
```

**Comment by caleb531** [comment]
Ha—should've mentioned that you'll probably need to change the formula for computing the new `scaleX` and `scaleY` for each layer. This is where things get tricky—try your best. ;)

**Comment by kimfree** [comment]
scaleX: layer.width / (origWidth+origIconWidth),
      scaleY: layer.height / origHeight

works pretty good now.

**Comment by kimfree** [comment]
strangely when I copy and paste this perfectly functioning code from the sandbox to my program it starts thinking the text has a width of 384px and messes everything up
