### ISSUE TITLE
extending jcanvas drawText

### ISSUE THREAD

**Issue by rads17** [caleb531/jcanvas#209]
Hey, I would like to extend drawText so that I can specify a custom style to format the text.

I have found some cool canvas text formatting information here:
http://www.html5rocks.com/en/tutorials/canvas/texteffects/

With code on how to do the effects but I am unsure how to use these in combination with jcanvas?

**Comment by caleb531** [comment]
There is no available API in jCanvas which allows you to extend drawText. The only way to do so would be to modify the method definition in the jCanvas source.

The method starts on [line 3614](https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L3614).
