### ISSUE TITLE
Conditional Draws Not Erasing On Refresh

### ISSUE THREAD

**Issue by iprosites** [caleb531/jcanvas#211]
Hi Caleb, I love jCanvas but am banging my head over a bug where things do not erase. I've provided a simple script to replicate the bug. I've emailed it to you but posting here in case you check here more. 

I've created 3 extension functions for drawing complex groups of shapes (a-la your drawHeart function). Every time ANY input box is changed, the script calls a simple redraw() function, an extension of jCanvas, which calls other jCanvas extensions. 

The criteria for the attached form is this:
- If text in the Height OR Width input are missing, a Placeholder Textbox shows on the Left side.
- If text in the Height OR Depth input are missing, a Placeholder Textbox shows on the Right side.
- If Height AND Width both have values, 2 Columns  should be drawn, separated by distance "width".
- The Floor always shows.

TO REPRODUCE BUGS:
- Add values to Height, Width, and Depth fields, and remove one at a time in random combinations to see that what should be happening is not happening. For example, add Height and Width, (which should remove the Placeholder Text but does not, and only adds a single Column instead of 2 Columns -- unless one is on top of the other),
- Then erase the Width, which should add the Placeholder Text back (which is erroneously still already there) but just adds on top of the existing text. 

BUGS:
- Both Placeholder textboxes never erase when their cases do not apply, they multiply on top of each other, slightly darkening the previous image.
- When the Columns (rectangles) are added, the second column does not appear to be added at "width" distance from the first column.
- Columns should erase when any input field is empty, but they do not erase.

INTERESTING POINT TO MAKE PART OF IT WORK:
- If you delete line 25 ($('canvas').drawFloor();), delete all lines in the "else" block (lines 32-36), and delete the 'drawFloor' and 'drawColumn' extension definitions from the script, you will notice the 'drawPlaceholderTextbox' function starts working perfectly and erasing and adding as expected, but of course, this is the only thing that can be added or erased. I can't do this AND have the Floor and Columns added and erased conditionally.

Please let me know your thoughts on this issue. I love the script but, while the documentation has a lot of examples, there is no specific example of this case to clarify the issue at hand here.

Thank you!!!

**Comment by caleb531** [comment]
I receive an email for every issue posted in this repository, and I receive a notification for every email I receive, so you don't need to worry. However, because of the nature of this issue, I'd prefer to tackle it over email. I'll get back to you in a bit.

**Comment by iprosites** [comment]
Awesome, thank you!
