### ISSUE TITLE
setLayer converts string to number

### ISSUE THREAD

**Issue by BlackSyforce** [caleb531/jcanvas#213]
Hi,

I have an issue with the setLayer method when I try to update a text with a new value. If the new value I'm trying to set is a number, even if it's represented as a String (e.g. "123"), the setLayer method will convert it to a Float and later it will try to use split on a number thus throwing an error.

Line 899 in jcanvas.js

Can you fix this or should I find a workaround ?

Thanks,
Adrian

**Comment by caleb531** [comment]
Thanks for reporting this. I have confirmed the issue, and have released jCanvas v15.10.08 with a fix. :)

**Comment by trd** [comment]
Thanks! This is really a good one!
