### ISSUE TITLE
mouseover and click will be missed when using zoom

### ISSUE THREAD

**Issue by ansenzhong** [caleb531/jcanvas#214]
<div class="zoom:200%">
		<canvas width="500" height="500" ></canvas>
		</div>

**Comment by caleb531** [comment]
Simple solution: don't use `zoom`. It's [non-standard](https://css-tricks.com/almanac/properties/z/zoom/) anyway, so using it could produce inconsistent behavior. Because of that, it's not something I ever plan to support for jCanvas.
