### ISSUE TITLE
Load : function not working

### ISSUE THREAD

**Issue by coresoftlanka** [caleb531/jcanvas#215]
I'm using jcanvas to edit image with html canvas. So I have to use 'load: ' option few times. But it's working only for first time only. When I use it twise not going to second function. Please help.

**Comment by caleb531** [comment]
Could you please be more descriptive? What do you mean it's only working once? Please provide the code you are using, or if you can't, try to reproduce the issue in the [jCanvas Sandbox](http://projects.calebevans.me/jcanvas/sandbox/).

**Comment by coresoftlanka** [comment]
oh . it's working now. I think it's my mistake. Thanks.

**Comment by coresoftlanka** [comment]
oh . it's working now. I think it's my mistake. Thanks.

**Comment by coresoftlanka** [comment]
oh . it's working now. I think it's my mistake. Thanks.

**Comment by coresoftlanka** [comment]
oh . it's working now. I think it's my mistake. Thanks.
