### ISSUE TITLE
Canvas Compositing, Blending Modes, and Resizing

### ISSUE THREAD

**Issue by skibulk** [caleb531/jcanvas#216]
1) Does jCanvas support compositing (Within a layer) and blending (between layers)? Can custom blending functions be supplied (such as "Phoenix")? http://blogs.adobe.com/webplatforhttps://cdn.rawgit.com/caleb531/jcanvas/master/jcanvas.min.js#20151021m/2013/01/28/blending-features-in-canvas/

2) I'm building a drawing application with nw.js. The canvas needs to be resizable from any given anchor point (not just scaled). Is this supported using jcanvas?

3) My canvas could potentially become very, very large. I'm concerned about performance when multiple layers are added to a large canvas. How is the layer data stored? An array of pixels? An offscreen canvas sprite? Do empty pixels consume memory, or do you just cache real pixels?

Thanks!

**Comment by caleb531** [comment]
1. Yes, jCanvas supports compositing through the `compositing` property on layers ([see here for values and additional documentation](http://projects.calebevans.me/jcanvas/docs/properties/#compositing)).

2. jCanvas supports the interactive resizing of layers on the canvas through my [Handles plugin](http://projects.calebevans.me/jcanvas/plugins/handles/), but jCanvas does not support resizing the canvas interactively. You need to implement that logic and behavior yourself.

3. jCanvas is built on top of the HTML5 canvas API, which controls how everything is drawn internally. However, I *can* tell you that though jCanvas typically draws all layers on a single canvas, you *can* utilize multiple layers with jCanvas simply by selecting them individually via jQuery.

For example:

```javascript
$('#canvas1').drawRect({ ... });
$('#canvas2').drawRect({ ... });
```

**Comment by MonkP** [comment]
Handles plugin will add many empty layers ,which jammed my grouped-index-change method when I developing my fake-3D drawing functions.
Could I just us setLayerGroup method to change the index of an entire layer group?
Thanks!
