### ISSUE TITLE
font descent in measureText....

### ISSUE THREAD

**Issue by bstarynk** [caleb531/jcanvas#217]
Hello,

It would be nice first to document a bit more what `measureText` is giving, and then to have more information given by it, in particular font descent and ascent.

extended text metrics in canvases is tricky. See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1102584 and https://readable-email.org/list/whatwg/topic/adding-descent-to-textmetrics and http://stackoverflow.com/a/9847841/841108 
I am not familiar enough with `canvas` and `jcanvas` to propose a patch. But http://nodebox.github.io/opentype.js & more importantly https://github.com/danielearwicker/carota/blob/master/src/text.js could be quite inspirational.

Regards.

Basile Starynkevitch - http://starynkevitch.net/Basile/
France (`basile` at `starynkevitch` dot `net`)

**Comment by caleb531** [comment]
Frankly, I am not familiar enough with typography to understand font ascent/descent and implement them properly. Furthermore, I feel that the Text API in jCanvas is somewhat complicated, as there is so much logic required to make behaviors like text wrapping work properly (and, as you indicate, font ascent/descent would be intrinsically tricky to implement). Finally, as I implied, I feel that font ascent/descent are rather esoteric—that is, they wouldn't be useful to the majority of jCanvas developers using the Text API.

For all of these reasons, I don't intend on setting aside the time and effort required to implement font ascent/descent.
