### ISSUE TITLE
Increase hit area around text

### ISSUE THREAD

**Issue by abhinavsharma1710** [caleb531/jcanvas#218]
Hi,
I there any way to increase hit / touch area around text?

**Comment by caleb531** [comment]
Currently, there is no such way in jCanvas to extend the so-called hit boundary for text layers without modifying the source yourself. This is also not something I intend to implement.

The best you could do is place a rectangle layer on top of the text—a rectangle with the desired width/height. You may wish to use jCanvas [drag groups](http://projects.calebevans.me/jcanvas/docs/draggableLayers/#drag-groups) to bind the two layers if the text needs to be draggable.
