### ISSUE TITLE
documentation request :-)

### ISSUE THREAD

**Issue by Laro88** [caleb531/jcanvas#220]
I was going to write to you requesting end specifiers for lines  - but you did it allready :-) in lines 288-292
You should mention this in the documentation with the lines.

Additionally I would like you to clarify the layers a bit more - how to use it. I had some code just using drawLines and then wanting to do layers for dynamic code, however this breaks the graphics. Having every single line on unique layer names works fine.
It would be great to have this design feature highlighted for future users.

Great work!

**Comment by caleb531** [comment]
Are you referring to the accepted values for `strokeCap` and `strokeJoin`? They are, in fact, already documented in the [Properties section](http://projects.calebevans.me/jcanvas/docs/properties/) (both [`strokeCap`](http://projects.calebevans.me/jcanvas/docs/properties/#strokecap) and [`strokeJoin`](http://projects.calebevans.me/jcanvas/docs/properties/#strokejoin).

I'm not quite sure what you'd like me to clarify regarding layers. Could you be more specific?
