### ISSUE TITLE
How add filters in layers? 

### ISSUE THREAD

**Issue by GiseleLima** [caleb531/jcanvas#221]
How do I insert filters in each layer?
Examples:
hue-rotate
sepia
brightness
contrast etc.
And other effects if possible.

**Comment by caleb531** [comment]
The only means jCanvas provides of doing this is the `setPixels()` method, which doesn't work perfectly for layers, but nonetheless generally works. There are no preset filters for `setPixels()`, so you must determine what color transformations achieve sepia or contrast adjustment. However, this should also be feasible to achieve.

Here's a quick example:

```javascript
function invert(layer) {
  $(this).setPixels({
    x: layer.x, y: layer.y,
    width: layer.width, height: layer.height,
    // loop through each pixel
    each: function(px) {
      px.r = 255 - px.r;
      px.g = 255 - px.g;
      px.b = 255 - px.b;
    }
  });
}

$('canvas').drawImage({
  layer: true,
  draggable: true,
  source: 'images/fish.jpg',
  x: 150, y: 100,
  // Invert image color when image layer loads
  load: invert
});
```
