### ISSUE TITLE
Quality of image layers

### ISSUE THREAD

**Issue by GiseleLima** [caleb531/jcanvas#225]
How to improve the quality of images in layers?

The original image has a better look, but when inserted into the canvas loses quality

**Original images:**

![image quality 1] (http://i66.tinypic.com/2j4uahg.png)
![image quality 1] (http://i63.tinypic.com/vr4q4h.png)

**Image in canvas**
![image quality](http://i66.tinypic.com/nx84f7.png)

I tried in some proportions scales but in all proportions losing quality
Using plugin handle or pure scale losing quality

**Comment by caleb531** [comment]
jCanvas does apply some browser-supported image smoothing through the `imageSmoothing` property for images. Try setting it to `false` (yes, `false`) to see if there's any noticeable improvement.

**Comment by GiseleLima** [comment]
Perfect, it works :D 
Thank you
