### ISSUE TITLE
Open and edit existing canvas

### ISSUE THREAD

**Issue by GiseleLima** [caleb531/jcanvas#226]
What function can use to click a button and edit an existing canvas?

For example:
If click in botton customize I will be able to edit all layers

http://ecardcanvas.com/cards/friendship

Is there any way to create a json file and restore the layers in the positions?

**Comment by caleb531** [comment]
> What function can use to click a button and edit an existing canvas?

jCanvas has no built-in means of making layers "editable" as they are on the eCard site. You would need to implement the editing logic yourself (but you can utilize draggable layers and Handles and other jQuery methods).

> Is there any way to create a json file and restore the layers in the positions?

A jCanvas layer contains many properties, some of which are JSON-serializable (e.g. width and height) and some of which are not (e.g. any event callback). Therefore, you need to perform the serialization yourself by choosing which serializable data is necessary to recreate any given layer (and then store those properties into a new object to be serialized).

I would recommend creating four functions to perform the following tasks:

1. Serializing a single layer (accept a layer object as a parameter and pick out the properties to copy into a new object)
2. Serializing all layers (accept a list of layers as a parameter and produce a list of serialized objects using the above serialization function)
3. Deserializing a single layer (accept a serialized object as a parameter and copy those properties into a new layer object (using the jCanvas `addLayer()` or `setLayer()` methods)
4. Deserialize all layers (accept a list of serialized objects and use the above deserialization function to recreate all layers on the canvas using that serialized data)

**Comment by GiseleLima** [comment]
Are certainly very important functions for the project, unfortunately my level of knowledge with native canvas and jquery is down to contribute.

Fabris.js and Konvajs supports serialization, perhaps more esperientes contribuites can verify the code and have a starting point to implement serialization in jcanvas

**Comment by caleb531** [comment]
I do not intend on building any serialization/deserialization features into jCanvas because the everyone uses jCanvas differently, and so not all data needs to be serialized.

I recommend you consult any developers you know personally to help you to write these functions and help you with this project. Frankly, I do not wish to get tangled up in working on your project for you.
