### ISSUE TITLE
Caleb, remember me?

### ISSUE THREAD

**Issue by vrbvillor** [caleb531/jcanvas#228]
Does any changes written in jCanvase?   If so ,  please tell me and I'll change the translations.  ^3^

**Comment by caleb531** [comment]
Thanks, @vrbvillor.

I haven't made any changes since November, but if I do, I'll indeed push them to the [jcanvas-docs](https://github.com/caleb531/jcanvas-docs) repository. And, since you are watching that repository, you should be notified of any future changes. :)

**Comment by vrbvillor** [comment]
OK,I'm watching it, keep in touch  ^3^
