### ISSUE TITLE
_wrapText function fails with numeric parameter

### ISSUE THREAD

**Issue by lefou23** [caleb531/jcanvas#230]
**Version**:
jcanvas v15.12.12

**Error Triggering Code**:

// parameter text: 123456 // <- typeof 'number' is the root cause
```
var textWidth = $(canvasId).measureText({
  fillStyle: "black",
  strokeWidth: 1,
  fontSize: "8pt",
  fontFamily: "Consolas, Courier, sans-serif",
  fromCenter: false,
  text: 123456
}).width;

```
**Expected Results**:
params.width set to 1.

**Actual Results**:
TypeError: allText.split is not a function. (In 'allText.split( '\n' )', 'allText.split' is undefined)
function _wrapText

I normally don't debug when reporting issues, but this is simple enough I'll propose the following fix: 
~ line number 3548
change to: 
`var allText = "" + params.text,`

When I apply this fix, the problem goes away. I would have loved to submit the fix directly for review, but I have no experience on github, and don't know your preferences for such things. Let me know if you need more info, and thanks for sharing this project.

**Comment by caleb531** [comment]
Thanks for the report, @lefou23. I just pushed v16.02.08 which implements your suggested fix. :)
