### ISSUE TITLE
About document update

### ISSUE THREAD

**Issue by litao10422** [caleb531/jcanvas#231]
About the document, ‘a native JavaScript API’s URL should change to 
 https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes
from
 https://developer.mozilla.org/en-US/docs/Trash/Canvas_tutorial-broken/Drawing_shapes (deleted).

HTML5 provides **a native JavaScript API** for drawing on the canvas. However, we will be using jCanvas instead.

**Comment by caleb531** [comment]
Thanks for reporting this, @litao10422. I've fixed it now. :)

For future reference, you can submit documentation issues on the [jcanvas-docs](https://github.com/caleb531/jcanvas-docs) repository.

**Comment by litao10422** [comment]
I'm a newbie to GitHub. I'll submit on the docs repository if the issue is a document issue.
