### ISSUE TITLE
Smiley arc text

### ISSUE THREAD

**Issue by yesprasoon** [caleb531/jcanvas#232]
How do I write arc text on smiley arc? Is there any way?
I need same smiley as it generates. But text from left to right and straight. Possible? If it's not a feature yet, could you please add that? :-)

$('canvas').drawText({
  fillStyle: '#c33',
  fontFamily: 'Ubuntu, sans-serif',
  fontSize: 18,
  text: 'Some text over here',
  x: 160, y: 200,
  radius: 150,
  rotate:180
});

**Comment by caleb531** [comment]
Hi, @yesprasoon. It's not possible currently, however after some playing around on my part, I was pretty easily able to achieve the desired effect. Therefore, I have added a new `flipArcText` property; set it to `true` and the text will be flipped to be readable again.

```
$('canvas').drawText({
fillStyle: '#c33',
fontFamily: 'Ubuntu, sans-serif',
fontSize: 18,
text: 'Some text over here',
x: 160, y: 200,
radius: 150,
rotate:180,
flipArcText: true
});
```

![screen shot 2016-02-09 at 5 25 23 pm](https://cloud.githubusercontent.com/assets/872474/12936282/29d74e8e-cf52-11e5-9bea-188ffe56c38c.png)

To download the jCanvas build with the new property, check out the `feature-flip-arc-text` branch (`jcanvas.js` and `jcanvas.min.js` were both updated). Once I confirm that you are satisfied with the addition, I can merge this in and push a new jCanvas release.
https://github.com/caleb531/jcanvas/tree/feature-flip-arc-text

**Comment by yesprasoon** [comment]
Perfect! Many thanks!! It's a nice feature addition.
