### ISSUE TITLE
NOT AN ISSUE : Including bold text in drawText

### ISSUE THREAD

**Issue by yesprasoon** [caleb531/jcanvas#233]
I assume in general we can not write something like
This sentence uses **Bold** word
on Canvas. We will have to write 'This sentence uses', measure width, write '**Bold**', measure width and then write 'word'.
However, things can go awry if text uses MaximumWidth / BoxWidth to wrap the whole text. It will go worse if text is rotated by some degree.

Any way to handle that? I understand that it might not come under the scope of 'jCanvas' or here on 'GitHub', but in case you have any suggestions, please help me.

**Comment by caleb531** [comment]
jCanvas in this case is limited by the HTML5 canvas API, which requires that a string a text (drawn with `fillText` or `strokeText`) must be formatted the same way (font family, font size, font style like bold). As you have implied, drawing each character as a separate call to `fillText` or `strokeText` (or `drawText` in the context of jCanvas) can lead to any number of issues, from kerning to wrapping.

Therefore, I'm sorry to say that I don't have any suggestions for you. It's simply a limitation of the native API.
