### ISSUE TITLE
Global mousemove event not bubbling

### ISSUE THREAD

**Issue by Cliff904** [caleb531/jcanvas#234]
It seems as though for a layer to trigger a global mousemove event ($.jCanvas.eventHooks.mousemove) 
it's draggable property must be set to true. If so, why is this the case?

**Comment by caleb531** [comment]
jCanvas events like `mousemove` are *layer* events, meaning they only work on jCanvas layers. Setting `draggable: true` makes a jCanvas drawing a layer implicitly, however I exhort you to set `layer: true` for any jCanvas drawings that use events.

**Comment by Cliff904** [comment]
Well the thing is, I did have the `layer:true` setting. The thing I was doing improperly was I wasn't immediately calling `drawLayers()`. Thanks!
