### ISSUE TITLE
Viewing changes to jcanvas-docs

### ISSUE THREAD

**Issue by vrbvillor** [caleb531/jcanvas#238]
Sorry for my poor experience. I don't know how to compare the difference with the version before. If any method new or dropped , please tell me. I'll update the Chinese documetation.

**Comment by caleb531** [comment]
Hello again, @vrbvillor. :)

You can see my latest changes by viewing the [commit history](https://github.com/caleb531/jcanvas-docs/commits/master) for the jcanvas-docs repository. Just click each commit message to view what was added and removed.

Caleb
