### ISSUE TITLE
Is jCanvas supporting jQuery 3.x?

### ISSUE THREAD

**Issue by yumetodo** [caleb531/jcanvas#240]
jQuery 3.0.0-rc1 was released.
Is jCanvas supporting jQuery 3.x?
drawHeart sample seems work...

**Comment by caleb531** [comment]
According to the [jQuery 3.0 blog post](https://blog.jquery.com/2014/10/29/jquery-3-0-the-next-generations/):

> Both the 1.x and 2.x versions of jQuery have the same public APIs, even though they differ somewhat in their internal implementations.

> The successor to jQuery 2.1.1 will be jQuery 3.0. There are two different packages on npm and Bower, but they share the same version to indicate they have the same API behavior.

Therefore, I conclude that the core API has not changed from jQuery 1.x to jQuery 3.x (browser support aside), and so jCanvas should be entirely compatible with jQuery 3.0. :)

**Comment by yumetodo** [comment]
thank you.
