### ISSUE TITLE
Clickable path

### ISSUE THREAD

**Issue by thingNumber1** [caleb531/jcanvas#244]
Hi,

How can I make a cloced path and make the path covered by this path clickeable?

**Comment by caleb531** [comment]
You can use the `drawLine()` method to create a freeform polygon, like so:

```js
$('canvas').drawLine({
  layer: true,
  fillStyle: '#000',
  x1: 100, y1: 50,
  x2: 100, y2: 150,
  x3: 200, y3: 100,
  closed: true,
  click: function(layer) {
    $(this).setLayer(layer, {
      fillStyle: '#6c3'
    })
    .drawLayers();
  }
});
```

**Comment by thingNumber1** [comment]
Man, this looks to be be working well when I try it alone, but it does not seems to work in my code maybe beacuse the rest of the proyect is not with the API. I would like to pass all my project to use your API, but can you please make an example where I have a canvas with a background image that I can zoom an mouve with the mouse and with clickable objects on it?

Something like this (http://m-static.com/canvas/), here the objects (like are the colored palace) are dfferent images and should be clickable (with it shape not square like and image).
