### ISSUE TITLE
Limits on scale and drag

### ISSUE THREAD

**Issue by thingNumber1** [caleb531/jcanvas#245]
Hi, I am passing my app to this script and I need set some kind of limit to the scale. My script is similar to this one: http://jsfiddle.net/vpascoal/j9kja28L/ and in this example, I need the gray layer to not be visible, like no more zoom out if the picture is completely visible horizontally or vertically and not more zoom after certain point. 

**EDIT:**
And the same for Dragging, if I am dragging to the left and the picture end on this side (there is no more picture on the left and is going to start showing th gray area), don't drag anymore to this side.

**Comment by caleb531** [comment]
You can use the built-in `Math.min()` function to prevent any value from becoming greater than another:

```js
zoom = Math.min(zoom + 1, maxZoom)
```

Similarly, you can use the built-in `Math.max()` function to prevent any value from becoming less than another:


```js
zoom = Math.max(minZoom, zoom + 1)
```

**Comment by thingNumber1** [comment]
Thanks, It worked very well. I really like this library and I don't like to use libraries if is not completely nasesary =)

**Comment by caleb531** [comment]
`Math.min` and `Math.max` are built into the JavaScript standard, so they're universally available across all browsers.
