### ISSUE TITLE
Scale canvas of layers - restoreCanvas() doesn't restore the canvas.

### ISSUE THREAD

**Issue by jordan-enev** [caleb531/jcanvas#247]
Hello,

My goal is to scale a canvas on a button click.

For an example let's say that we have three buttons - Zoom in / reset / out.
On a button click the canvas has to scale only once - if Zoom in button is clicked two sequential times then the canvas has to scale only once. The same is valid for the rest buttons too.

The problem I have is that the canvas is scaled as many times the button is clicked. Also Zoom reset button doesn't work.

Here is my code:
```HTML
<button value="2">Zoom in</button>
<button value="1">Zoom reset</button>
<button value="0.5">Zoom out</button>

<canvas width="500" height="500"></canvas>
```

```Javascript
var canvas = $('canvas');

// Add rectangle layer
canvas.addLayer({
	type: 'rectangle',
	x: 0,
	y: 0,
	width: 100,
	height: 100,
	fillStyle: '#000099',
 	strokeStyle: '#000099'
});

// Draw the layers
canvas.drawLayers();

// On a button click scale the canvas
$('button').on('click', function() {
	var zoomLevel = $(this).val();
  
	canvas.scaleCanvas({
  		scale: zoomLevel
	}).drawLayers().restoreCanvas();
});
```

Here is [JSFiddle](https://jsfiddle.net/jordan_enev/vcvt9wdk/14/).

What do I miss?

Thank you!

**Comment by caleb531** [comment]
Try this: https://jsfiddle.net/vcvt9wdk/16/

The trick is to treat the scaling and restoring as actual layers (as unintuitive as that may seem). That way, jCanvas will automatically scale the canvas before redrawing layers, and reset the scaling after redrawing layers (to prevent the compounding effect you were experiencing).

**Comment by jordan-enev** [comment]
Thank you for the support. Now it works. :sunrise: 

For future reference, I'll paste your code here.

```Javascript
var canvas = $('canvas');

canvas.scaleCanvas({
  layer: true,
  name: 'scaleCanvas',
  scale: 1
});

// Add rectangle layer
canvas.addLayer({
	name: 'canvas',
	type: 'rectangle',
	x: 0,
	y: 0,
	width: 100,
	height: 100,
	fillStyle: '#000099',
 	strokeStyle: '#000099'
});

canvas.restoreCanvas({
  layer: true,
  name: 'restoreCanvas'
});

// Draw the layers
canvas.drawLayers();

// On a button click scale the canvas
$('button').on('click', function() {
	var zoomLevel = $(this).val();
  
	canvas.setLayer('scaleCanvas', {
    scale: zoomLevel
  }).drawLayers();
});

````
