### ISSUE TITLE
Handle plugins display wrong position when layer is rotate

### ISSUE THREAD

**Issue by NeoAquarius** [caleb531/jcanvas#250]
When I rotate layer with handle attached the handle mark still at the same position.

**Comment by caleb531** [comment]
Try downloading the jCanvas build on the [feature-handles-rotation](https://github.com/caleb531/jcanvas/tree/feature-handles-rotation) branch. It adds experimental rotation support to the Handles plugin, which is far from perfect but it might be sufficient for your needs.

**Comment by NeoAquarius** [comment]
Tried the new build. Handle now rotate with layer but position is not match with rotated layer and when resize using handle on rotated layer is malfunction, It's fine when not rotate.

**Comment by caleb531** [comment]
I'm sorry to hear that. In that case, I can't do anything more for you. Adding functional rotation to handles will be complicated to fully implement, and I cannot afford to implement support at this time. However, I will accept pull requests from you or anyone else who is up for the challenge.
