### ISSUE TITLE
Handle support for combined path shapes 

### ISSUE THREAD

**Issue by Samvherck** [caleb531/jcanvas#251]
Hello, it looks like the handle plugin is not working on a Path, am I doing something wrong is or it just not supported? If so, are there any alternative methods to accomplish this problem:

I'm trying to combine complex shapes like quadratic and lines, every shape should be able to get resized/reshaped separately using the handle-plugin. 

**Edited photo as example of what I'm trying to accomplish where both lines and the quadratic have the handle-plugin activated:**

![example](https://cloud.githubusercontent.com/assets/11502660/17698487/c29af4ec-63bb-11e6-99fa-8d071115b430.png)

```
$('canvas').drawPath({
  strokeStyle: '#000',
  strokeWidth: 4,
  p1: {
    type: 'line',
    x1: 200, y1: 50,
    x2: 100, y2: 150,
    x3: 200, y3: 150,
    x4: 120, y4: 200,
	handle: { // no handles added on lines
		type: 'arc',
		fillStyle: '#fff',
		strokeStyle: '#c33',
		strokeWidth: 2,
		radius: 10
	}
  },
  p2: {
    type: 'quadratic',
    x1: 120, y1: 200,
    cx1: 180, cy1: 250,
    x2: 225, y2: 200,
    handle: {  // no handles added on quadratic
		type: 'arc',
		fillStyle: '#fff',
		strokeStyle: '#c33',
		strokeWidth: 2,
		radius: 10
	}
  }
});
```

**Comment by caleb531** [comment]
I'm sorry to say that this is currently not supported, and adding support to the Handles plugin *directly* would be challenging. The jCanvas Handles plugin is quite complicated, consisting of a ton of logic that was written without `drawPath` in mind (as I believe Handles preceded `drawPath`).

However, I was (ironically) able to write a sophisticated (albeit hackish) solution which you should be able to use in your application. The only catch is that your path must be of `type: 'quadratic'` (and so you must initialize your curve with control points), but this function will attempt to simplify the curve by removing handles which intersect with the curve. This implies that when you define the curve, for every line you want to create, your control point for that "line" must be equal to the midpoint of the previous and next points. This is more obvious when you see the example:

```js
var $canvas = $('canvas');

$canvas.addLayer({
	layer: true,
	type: 'quadratic',
	name: 'myPath',
	strokeStyle: '#000',
	strokeWidth: 4,
	miterLimit: 1,
	x1: 200, y1: 50,
	cx1: 150, cy1: 100,
	x2: 100, y2: 150,
	cx2: 150, cy2: 150,
	x3: 200, y3: 150,
	cx3: 160, cy3: 175,
	x4: 120, y4: 200,
	cx4: 180, cy4: 250,
	x5: 225, y5: 200,
	handle: {
		type: 'arc',
		fillStyle: '#fff',
		strokeStyle: '#000',
		strokeWidth: 2,
		radius: 10
	},
	guide: {
		type: 'line',
		strokeStyle: '#000',
		strokeWidth: 1
	}
});

function simplifyHandlePath(parent) {
	parent = $canvas.getLayer(parent);
	var lineStartIndexes = [];
	for (var h = 0; h < parent._handles.length; h += 1) {
		var startHandle = parent._handles[h];
		var midHandle = parent._handles[h + 1];
		var endHandle = parent._handles[h + 2];
		if (endHandle !== undefined && startHandle._xProp.indexOf('c') === -1) {
			var slopeToMid = (midHandle.y - startHandle.y) / (midHandle.x - startHandle.x);
			var slopeToEnd = (endHandle.y - startHandle.y) / (endHandle.x - startHandle.x);
			if (slopeToMid === slopeToEnd) {
				lineStartIndexes.push(h);
				$canvas.removeLayer(midHandle);
			}
		}
	}
	$canvas.setLayer(parent, {
		handlemove: function (parent) {
			var $canvas = $(this);
			for (var p = 0; p < lineStartIndexes.length; p += 1) {
				var lineStartIndex = lineStartIndexes[p];
				var startHandle = parent._handles[lineStartIndex];
				var endHandle = parent._handles[lineStartIndex + 2];
				parent._guide['x' + (lineStartIndex + 2)] = (startHandle.x + endHandle.x) / 2;
				parent._guide['y' + (lineStartIndex + 2)] = (startHandle.y + endHandle.y) / 2;
				parent['cx' + ((lineStartIndex / 2) + 1)] = (startHandle.x + endHandle.x) / 2;
				parent['cy' + ((lineStartIndex / 2) + 1)] = (startHandle.y + endHandle.y) / 2;
			}
		}
	});
}

simplifyHandlePath('myPath');
$canvas.drawLayers();
```

I have only tested it on the path you gave me, but as far as I can tell, the function should work for other paths as well (so long as you rewrite them as quadratic curves, of course).

Caleb

**Comment by Samvherck** [comment]
Thank you Caleb, it is working perfectly except when the object is getting dragged.

When dragging (draggable: true) and than adjusting the handle positions the lines become curved. I'm trying to fix the problem but do you got any ideas/tips?

**Comment by caleb531** [comment]
Oh, my apologies. Fortunately, the fix is two lines:

Simply subtract off `parent.x` and `parent.y` respectively when setting the parent's `cx*` and `cy*` properties:

```js
				parent['cx' + ((lineStartIndex / 2) + 1)] = ((startHandle.x + endHandle.x) / 2) - parent.x;
				parent['cy' + ((lineStartIndex / 2) + 1)] = ((startHandle.y + endHandle.y) / 2) - parent.y;
```

**Comment by Samvherck** [comment]
Beautiful work, thanks Caleb!
