### ISSUE TITLE
Text Tooltip on mouseover

### ISSUE THREAD

**Issue by mlz1055** [caleb531/jcanvas#252]
Hi,
With below code the text appears only when the mouse just crosses the rectangle boundaries. I would expect that the text remains all the time the mouse is hovering the rectangle. Maybe my code is not the correct way to build a tooltip?

Code:
// Draw a green rectangle
$('canvas').drawRect({
  layer: true,
  fillStyle: '#6c0',
  x: 100, y: 100,
  width: 100, height: 80,
  mouseover: function(layer) {
    // code to run when square is hovered
	$('canvas').drawText({
	  fillStyle: '#9cf',
	  strokeStyle: '#25a',
	  strokeWidth: 1,
	  x: 50, y: 50,
	  fontSize: 10,
	  fontFamily: 'Verdana, sans-serif',
	  text: 'Hello'
	});
  }
});

**Comment by caleb531** [comment]
The reason the tooltip appears only for an instant is because it's not a jCanvas layer. In jCanvas, if you create a layer, then everything else must be a layer as well so that jCanvas knows to draw them when it redraws the canvas as needed.

Try this: it's a bit more sophisticated than your example., but it's more practical way of handling tooltips in jCanvas.

```js
var $canvas = $('canvas');

// Green rectangle
$canvas.drawRect({
  layer: true,
  name: 'rect-1',
  fillStyle: '#6c0',
  x: 100, y: 100,
  width: 100, height: 80,
  // Show tooltip when user mouses over rectangle
  mouseover: function(layer) {
    console.log(layer.eventX);
    $canvas.setLayer(layer.name + '-tooltip', {
      visible: true
    }).drawLayers();
  },
 // Hide tooltip when user mouses out of rectangle
  mouseout: function(layer) {
    $canvas.setLayer(layer.name + '-tooltip', {
      visible: false
    }).drawLayers();
  }
});

// Tooltip should be drawn above (i.e. after) rectangle
$canvas.drawText({
  layer: true,
  visible: false,
  name: 'rect-1-tooltip',
  fillStyle: '#9cf',
  strokeStyle: '#25a',
  strokeWidth: 1,
  x: 50, y: 50,
  fontSize: 10,
  fontFamily: 'Verdana, sans-serif',
  text: 'Hello'
});
```
