### ISSUE TITLE
Little suggestion

### ISSUE THREAD

**Issue by mtsee** [caleb531/jcanvas#253]
Each time a separate drawing, if only added to the memory, the last time the performance will be able to draw a lot of improvement

**Comment by caleb531** [comment]
Hi, @mtsee. I don't understand what you are suggesting. Could you please clarify?

Caleb

**Comment by mtsee** [comment]
objs add-to Memory many times，then render one times。just render  one times.

**Comment by mtsee** [comment]
eg：
$("canvas").drawArc({
  draggable: true,
  fillStyle: "green",
  x: 100, y: 100,
  radius: 50
});

=>

$("canvas").add({
  draggable: true,
  fillStyle: "green",
  x: 100, y: 100,
  radius: 50
}).add({
  draggable: true,
  fillStyle: "green",
  x: 200, y: 200,
  radius: 50
}).add({
  draggable: true,
  fillStyle: "green",
  x: 300, y: 300,
  radius: 50
}).drawArc();

like this. can't each do render, render just do once

**Comment by mtsee** [comment]
sorry! my English is bad~

**Comment by caleb531** [comment]
I believe I understand what you mean now. However, in jCanvas, each layer can only consist on a single drawing. For example, you cannot have multiple arcs drawn via a single `drawArc` call as you have shown above. I have considered the possibility of multiple drawings per layer, but it would complicate the API and therefore is not something that will be implemented in the foreseeable future.
