### ISSUE TITLE
Mouse event location on window resize

### ISSUE THREAD

**Issue by mlz1055** [caleb531/jcanvas#254]
Hi,
With below code the mouse over and mouse out sensitive location are not following the resize translation and stay at the same absolute (X,Y) whatever the window resize is. What could be wrong?
```html
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>jCanvas window resize</title>
<script type="text/javascript" src="/jqwidgets/scripts/jquery-1.11.1.min.js"></script>
<script src="/jCanvas/jcanvas-master/jcanvas.min.js"></script>

<script type="text/javascript">

$(window).resize(function() {
	doResize();
});

function doResize (e) {
	var canvasRatio = $('canvas').height() / $('canvas').width();
	var winRatio = window.innerHeight / window.innerWidth;
	var width;
	var height;

	if (winRatio < canvasRatio) {
		height = window.innerHeight;
		width = height / canvasRatio;
	} else {
		width = window.innerWidth;
		height = width * canvasRatio;
	}

	$('canvas').width(width + 'px');
	$('canvas').height(height + 'px');
}

$(function () {

	$('#myCanvas').drawRect({
		layer: true,
		name: 'Rect_1',
		fillStyle: '#f00',
		x: 20, y: 20,
		width: 30,
		height: 30,
		mouseover: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: true
			}).drawLayers();
		},
		mouseout: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: false
			}).drawLayers();
		}
	}).drawText({
		layer: true,
		visible: false,
		name: 'Rect_1-tooltip',
		x: 20, y: 20,
		fillStyle: '#000',
		fontSize: 18,
		fontFamily: 'Verdana, sans-serif',
		text: 'Rec-1'
	});

	$('#myCanvas').drawRect({
		layer: true,
		name: 'Rect_2',
		fillStyle: '#0f0',
		x: 400, y: 200,
		width: 50,
		height: 50,
		mouseover: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: true
			}).drawLayers();
		},
		mouseout: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: false
			}).drawLayers();
		}
	}).drawText({
		layer: true,
		visible: false,
		name: 'Rect_2-tooltip',
		x: 400, y: 200,
		fillStyle: '#000',
		fontSize: 18,
		fontFamily: 'Verdana, sans-serif',
		text: 'Rec-2'
	});
	$('#myCanvas').drawRect({
		layer: true,
		name: 'Rect_3',
		fillStyle: '#00f',
		x: 250, y: 500,
		width: 40,
		height: 40,
		mouseover: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: true
			}).drawLayers();
		},
		mouseout: function (layer) {
			$('#myCanvas').setLayer(layer.name + '-tooltip', {
				visible: false
			}).drawLayers();
		}
	}).drawText({
		layer: true,
		visible: false,
		name: 'Rect_3-tooltip',
		x: 250, y: 500,
		fillStyle: '#000',
		fontSize: 18,
		fontFamily: 'Verdana, sans-serif',
		text: 'Rec-3'
	});

	// Title
	$('#myCanvas').drawText({
	  layer: true,
	  name: 'title',
	  fillStyle: '#9cf',
	  strokeStyle: '#25a',
	  strokeWidth: 1,
	  x: 400, y: 10,
	  fontSize: 24,
	  fontFamily: 'Verdana, sans-serif',
	  text: 'TITLE'
	});

	// Subtitle
	$('#myCanvas').drawText({
	  layer: true,
	  name: 'subtitle',
	  fillStyle: '#9cf',
	  strokeStyle: '#25a',
	  strokeWidth: 1,
	  x: 400, y: 830,
	  fontSize: 18,
	  fontFamily: 'Verdana, sans-serif',
	  text: 'subtitle'
	});
	
	doResize ();

});
</script>
</head>
<body>
<div class="container" id="content">
	<div class="wrapper">
		<canvas id="myCanvas" width="1000" height="1000">Your browser doesnt support canvas tag</canvas>
	</div>
</div>
</body>
</html>
```

**Comment by caleb531** [comment]
You cannot use jQuery's `width()` and `height()` methods to set the physical width/height of the canvas, because those methods change the CSS width/height (which in turn scales the canvas). The correct way to change the physical dimensions of the canvas is to set the canvas's `width`/`height` attributes, which you can do via jQuery's `prop()` or `attr()` methods.

```js
$('canvas').prop({
  width: width,
  height: height
});
```

```js
$('canvas').attr({
  width: width,
  height: height
});
```

**Comment by mlz1055** [comment]
Hi Caleb,
Using  attr() or prop() do not resize the canvas when resizing the browser window. Using with() and height() jQuery methods do resize the canvas when the window is resized. The only issue is about the sensitive area of mouseover and mouseout which are not translated ( the tooltip is well translated). Hence my problem remains the same: how to make the canvas resize according to a window resize?

**Comment by caleb531** [comment]
Using `prop()` or `attr()` should definitely work, and I highly recommend it. Just be aware of a few caveats (assuming you use `prop()`, which is somewhat more reliable than `attr()`):

1. When you set the width/height using `prop()` or `attr()`, do not append any units to the values.

**Do:**
```js
$('#myCanvas').prop({
  width: 800,
  height: 300
});
```

**Don't:**
```js
$('#myCanvas').prop({
  width: 800 + 'px',
  height: 300 + 'px'
});
```

2. When you retrieve the width/height of the canvas, you also need to use `prop()` or `attr()` instead of `width()`/`height()`:

**Do:**
```js
$('#myCanvas').prop('width')
```

**Don't:**
```js
$('#myCanvas').width()
```

**Comment by mlz1055** [comment]
Hi Caleb,
Using prop() resizes the canvas bitmap drawing area as will do a crop function. This is not what I need. I need that the drawing and the tooltips are rescaled (up or down) following the browser window resizing.
Up to now, the rescaling of the drawing works when using $('canvas').width() and height() methods but the sensitive area of mouse events is not. The only way to have the mouseover sensitive area following the browser window resize is using the scaleCanvas method but the drawback is I cannot compute the scaling factor correctly (window.innerWidth / originalWidth) because scaleCanvas seems working on the actual sizes and not on the original ones and I don't know how to retrieve these "actual sizes". What method would you advice to rescale the canvas (drawing and tooltips) when the browser window is resized?
Many thanks.

**Comment by caleb531** [comment]
The "actual size" would be your preferred size of the canvas when all of the drawings on the canvas are the size you'd prefer them to be. In other words, when you are drawing squares or circles on the canvas, what dimensions are their coordinates relative to? The answer to that question is your original canvas size, which you can then use to compute the ratio for `scaleCanvas`.

Also, in order for scaling to work correctly across redraws, you should set `layer: true` on your `scaleCanvas` call and give it a `name` (as strange as that sounds). This call must appear before all other layer definitions, as this must be the very first layer.

```js
$('#myCanvas').scaleCanvas({
  layer: true,
  name: 'scaleLayer'
});
```

Then, add a `restoreCanvas` layer after all layer definitions, as this must be the very last layer.

```js
$('#myCanvas').restoreCanvas({
  layer: true,
  name: 'restoreLayer'
});
```

Then, whenever you need to redraw the canvas at a new scale, you can use the `setLayer` method to set the `scale` on your `scaleCanvas` layer.

```js
$('#myCanvas').setLayer('scaleCanvasLayer', {
  scale: window.innerWidth / originalWidth
}).drawLayers();
```

Finally, you need to update the canvas dimensions when the window is resized. I haven't tested the below code, but I believe the math works out. 

```js
var resizeTimeout;
$(window).on('resize', function() {
  // Ensure that the canvas is only scaled 100ms after the user stops resizing the window
  clearTimeout(resizeTimeout);
  setTimeout(function() {
    var currentWidth = window.innerWidth;
    var currentHeight = currentWidth * originalHeight / originalWidth;
    $('#myCanvas')
      .width(currentWidth)
      .height(currentHeight)
      .setLayer('scaleCanvasLayer', {
        scale: currentWidth / originalWidth
      })
      .drawLayers();
  }, 100);
});
```

Let me know how that works for you.

Caleb

**Comment by mlz1055** [comment]
Thanks a lot for the solution to my window resize issue. I just have to remove the setting of the canvas width and height to have all the elements re-positioned correctly (incl. the tooltips). Even if not all is crystal clear in my mind, I really appreciate your great library.
