### ISSUE TITLE
jCanvas with webpack

### ISSUE THREAD

**Issue by tate-u** [caleb531/jcanvas#255]
I'm trying to import 'jcanvas', installed from npm, into a typescript class and the factory function is never executed, so its never actually attached to window.jquery prototype. Anyone have a suggestion how to make this work? I haven't had any issues with any other jquery plugin on an Angular2/Typescript setup. Thanks!

**Comment by caleb531** [comment]
I've never used Webpack, so I am frankly not sure how to go about investigating this issue.

@robertjustjones, could you please help out with this? :)

**Comment by tate-u** [comment]
Ok....I think I'll keep plugging away at it then. Just thought I'd check in with you first.

**Comment by tate-u** [comment]
Just a note for anyone else....as a temporary fix, I changed the initializing to the following, basically just commenting out the module.exports portion and everything wires up...

`(function( jQuery, global, factory ) {

	//if ( typeof module === 'object' && typeof module.exports === 'object' ) {
	//	module.exports = function( jQuery, w ) {
	//		return factory( jQuery, w );
	//	};
	//} else {
	//	factory( jQuery, global );
    	//}
    	factory(jQuery, global);

// Pass this if window is not defined yet
}( typeof window !== 'undefined' ? window.jQuery : {}, typeof window !== 'undefined' ? window : this, function( $, window ) {`

**Comment by irobayna** [comment]
@tate-u any chance you can create a pull request with your changes?

**Comment by irobayna** [comment]
For anyone looking for webpack support, jCanvas does works out of the box.  The following works for me:

```javaScript
require('jcanvas')($, window);
```

@caleb531 @tate-u
