### ISSUE TITLE
 make rectangle with mouseover!

### ISSUE THREAD

**Issue by KonstantinKudelko** [caleb531/jcanvas#256]
Hello, I'm trying to make a rectangle with mouseover,
I had a few problems:
1) When I go beyond the canvas I have strange things happen, then all is lost, then painted over
2) How to keep, what I drew?

```js
$(document).ready(function() {
    var $canvas = $('canvas');
    var rect = {};
    var drawing = false;
    var box = $('.cub');

    $canvas.on('mousedown', _mousedown);
    $canvas.on('mouseup', _mouseup);
    $canvas.on('mousemove', _drawing);

    function _mousedown(e) {
        drawing = true;
        var startX = e.pageX - $canvas.offset().left;
        var startY = e.pageY - $canvas.offset().top;
        rect.x = startX;
        rect.y = startY;
    }

    function _mouseup(e) {
        drawing = false;
    }

    function _drawing(e) {
        var currentX = e.pageX - $canvas.offset().left;
        var currentY = e.pageY - $canvas.offset().top;
        if(drawing) {
            $canvas.clearCanvas();
            $canvas.drawRect({
                strokeStyle: '#000',
                layer: true,
                fromCenter: false,
                x: rect.x, y: rect.y,
                width: currentX - rect.x, height: currentY - rect.y
            });
        }
    }
});
```

**Comment by caleb531** [comment]
Don't use drawRect within your _drawing function. Instead, use setLayer() ([documentation here](http://projects.calebevans.me/jcanvas/docs/manipulateLayers/)) to update the position/size of your rectangle. (assuming that you initially create your rectangle layer, perhaps on `mousedown`).

I think that should help a bit, but let me know if you're still having trouble.

**Comment by KonstantinKudelko** [comment]
Yes, I have got, now it does not disappear when I leave for the canvas limits)
But how can I possibly keep what I have drawn?
I now draw a shape, and then when I start to draw another previous erased, how to change it?

**Comment by caleb531** [comment]
I apologize; I misinterpreted what you are trying to accomplish here, but I now have a better idea of what you are trying to do. Ironically, your first code snippet was actually pretty close—just remove `layer: true` from your `drawRect` call.

You mentioned you want to create a painting application, and I think you'll have an easier time if you don't use the jCanvas Layer API (*i.e.* if you omit `layer: true` from your drawings). Try this:

```js
$(document).ready(function() {
    var $canvas = $('canvas');
    var rect = {};
    var drawing = false;
    var box = $('.cub');

    $canvas.on('mousedown', _mousedown);
    $canvas.on('mouseup', _mouseup);
    $canvas.on('mousemove', _drawing);

    function _mousedown(e) {
        drawing = true;
        var startX = e.pageX - $canvas.offset().left;
        var startY = e.pageY - $canvas.offset().top;
        rect.x = startX;
        rect.y = startY;
    }

    function _mouseup(e) {
        drawing = false;
    }

    function _drawing(e) {
        var currentX = e.pageX - $canvas.offset().left;
        var currentY = e.pageY - $canvas.offset().top;
        if(drawing) {
            $canvas.clearCanvas();
            $canvas.drawRect({
                strokeStyle: '#000',
                fromCenter: false,
                x: rect.x, y: rect.y,
                width: currentX - rect.x, height: currentY - rect.y
            });
        }
    }
});
```

**Comment by KonstantinKudelko** [comment]
That is, now I am not of `layer `message is used, and I have worked all proekrasno, but I can rotate scale and translate these objects, unless you use a layer?

**Comment by caleb531** [comment]
Did that work for you, @KonstantinKudelko? :)

**Comment by KonstantinKudelko** [comment]
Yes, but how I can choose any shape? Like this http://fabricjs.com/intersection?

**Comment by KonstantinKudelko** [comment]
Yes, but I have one question.
I draw squares using mousemove. 
But when I add the name to the layer, I can not draw a lot of squares, how to fix it, because I want to refer to the layer to rotate it

**Comment by caleb531** [comment]
Hmm, then actually, you probably want to use the Layer API after all. To help you out based on everything I know now about what you want to do, I've crafted a brand new example:

In the example below, you are presented with a blank canvas. Dragging on any empty region of the canvas will create a new rectangle (note the four cases in the `mousemove` callback). However, if you attempt to drag an existing rectangle, it will be dragged around normally without creating any new rectangles (this is made possible by that background layer).

```js
// Draw background layer to help detect when user is not dragging rectangle
$canvas.drawRect({
	layer: true,
	name: 'background',
	x: 0, y: 0,
	fillStyle: '#9cf',
	width: $canvas.width(), height: $canvas.height(),
	fromCenter: false,
	// Drag on background to create new rectangles
	// Still allows for existing rectangles to be dragged
	mousedown: function() {
		canCreate = true;
	},
});
var background = $canvas.getLayer('background');

$canvas.on('mousedown', function (event) {
	if (canCreate) {
		$canvas.drawRect({
			layer: true,
			draggable: true,
			// Bring layer to front when dragged
			bringToFront: true,
			fillStyle: '#c33',
			strokeStyle: '#000',
			strokeWidth: 2,
			x: event.offsetX, y: event.offsetY,
			width: 0, height: 0,
			fromCenter: false
		});
		curRect = $canvas.getLayer(-1);
		startX = event.offsetX;
		startY = event.offsetY;
		dragging = true;
		event.preventDefault();
	}
});

$canvas.on('mousemove', function (event) {
	if (dragging) {
		var dx = event.offsetX - startX;
		var dy = event.offsetY - startY;
		if (dx > 0 && dy > 0) {
			// Bottom-right quadrant
			curRect.x = startX;
			curRect.y = startY;
		} else if (dx > 0 && dy < 0) {
			// Top-right quadrant
			curRect.x = startX;
			curRect.y = event.offsetY;
		} else if (dx < 0 && dy > 0) {
			// Bottom-left quadrant
			curRect.x = event.offsetX;
			curRect.y = startY;
		} else if (dx < 0 && dy < 0) {
			// Top-left quadrant
			curRect.x = event.offsetX;
			curRect.y = event.offsetY;
		}
		curRect.width = Math.abs(dx);
		curRect.height = Math.abs(dy);
		$canvas.drawLayers();
	}
	event.preventDefault();
});

$canvas.on('mouseup', function (event) {
	dragging = false;
	canCreate = false;
	event.preventDefault();
});
```

I hope this helps a bit more. Let me know how it works for you! :)
Caleb

**Comment by KonstantinKudelko** [comment]
yes thanks

**Comment by KonstantinKudelko** [comment]
thanks
