### ISSUE TITLE
Click eventCallback draws all layers

### ISSUE THREAD

**Issue by Steele1** [caleb531/jcanvas#257]
When a click event is triggered for a layer the eventCallback draws all the layers via $canvas.drawLayers. If you have a few thousand layers this becomes noticeably slow. Is there a way to only draw the layer for the layer being clicked on?

**Comment by caleb531** [comment]
Kinda, sorta.

jCanvas has adopted a single-canvas architecture, meaning all layers are drawn (and redrawn) on a single canvas. This makes the API very easy and flexible to work with, but it does have the potential of introducing performance problems for a large number of layers. However, jCanvas allows you to operate on multiple canvases, and so you could (in theory) superimpose one canvas on another, and split your layers across the two (thereby reducing the cost of redrawing layers on each canvas). You can target each canvas using jQuery like anything else (`$('#canvas1')` or `$('#canvas2')`).

The only issue you might run into is handling events on lower-level canvases. But according to StackOverflow, [this is indeed possible](http://stackoverflow.com/questions/12215128/stacked-canvas-event).

**Comment by caleb531** [comment]
I haven't heard any new responses in over a month, so I am decidedly closing this issue for now.
