### ISSUE TITLE
Draggable item issue

### ISSUE THREAD

**Issue by aeroreyna** [caleb531/jcanvas#258]
When the canvas is set in a scale = 2, the items drags out proportion. Is it jcanvas, or something from the canvas?

**Comment by caleb531** [comment]
Hi, @aeroreyna.

How are you scaling the canvas? There are many ways to scale the canvas—some methods being better than others.

Thanks,
Caleb

**Comment by aeroreyna** [comment]
Hello

```
$('canvas').scaleCanvas({
  scale: 0.5
})
```

**Comment by caleb531** [comment]
I see. The trick is to pass `layer: true` to `scaleCanvas`, and make sure that this `scaleCanvas` call comes before all other layers. If you do this, you must also have a `restoreCanvas` call (with `layer: true`) which comes *after* all other layers. See the example below; you can try it in the [jCanvas Sandbox](http://projects.calebevans.me/jcanvas/sandbox/):

```js
var $canvas = $('canvas');

// This must be the first layer
$canvas.scaleCanvas({
  layer: true,
  name: 'scale-canvas',
  scale: 2
});

$canvas.drawArc({
  layer: true,
  draggable: true,
  fillStyle: '#6c3',
  x: 100, y: 100,
  radius: 50
});

// This must be the last layer
$canvas.restoreCanvas({
  layer: true,
  name: 'restore-canvas'
});
```

**Comment by aeroreyna** [comment]
This work in the case you know the scale beforehand, but I'm trying to scale dynamically as the user needed.

I have not ready the example I'm making yet, I'll try different options.

I'm using your library for a personal project store in [MobileNetWeb](https://github.com/aeroreyna/MobileNetsWeb).

Thank you.

**Comment by caleb531** [comment]
Sorry @aeroreyna—I should have figured that was your goal. Fortunately, I designed my example above to be easy to enable scaling dynamically.

```js
var $canvas = $('canvas');

// This must be the first layer
$canvas.scaleCanvas({
  layer: true,
  name: 'scale-canvas',
  scale: 2
});

$canvas.drawArc({
  layer: true,
  draggable: true,
  fillStyle: '#6c3',
  x: 100, y: 100,
  radius: 50
});

// This must be the last layer
$canvas.restoreCanvas({
  layer: true,
  name: 'restore-canvas'
});

// Scale the canvas whenever you double-click it
$canvas.dblclick(function() {
  // The setLayer() method is the secret here
  $canvas.setLayer('scale-canvas', {
    // This increases the scale from the current value by 25%,
    // but you can still use numbers like 2 and 3 if that's what you want
    scale: '+=0.25'
  }).drawLayers();
});
```

**Comment by aeroreyna** [comment]
Thank you, I figured how to do it with your code, the explanation in [this issue](https://github.com/caleb531/jcanvas/issues/135) helps too.
