### ISSUE TITLE
Pointer Support for IE and Edge

### ISSUE THREAD

**Issue by bliet** [caleb531/jcanvas#259]
Hello,

the touchstart/move/end are not fired in IE and Edge. The most Android and iOS browser support touchstart, touchmove and touchend.

But the desktop browser IE and MS Edge only support pointerdown, pontermove and pointerup. Specification: http://www.w3.org/TR/pointerevents/ 

It would be great, if jcanvas supports this events.

have a nice day, benjamin

**Comment by caleb531** [comment]
Hi, Bejamin.

jCanvas already does support the `touchstart`, `touchmove`, and `touchend` events. In my experience, these events only work on touch-enabled devices, and because IE and Edge are generally desktop browsers, I would not expect these events to work there.

Perhaps I'm misunderstanding your question; feel free to clarify. :)
Caleb

**Comment by bliet** [comment]
[This example](http://projects.calebevans.me/jcanvas/sandbox/?code=Ly8gVGhpcyBkZW1vIHdpbGwgb25seSB3b3JrIG9uIGlPUyBhbmQgQW5kcm9pZAokKCdjYW52YXMnKS5kcmF3UmVjdCh7CiAgbGF5ZXI6IHRydWUsCiAgZmlsbFN0eWxlOiAnIzM2YycsCiAgeDogMTUwLCB5OiAxMDAsCiAgd2lkdGg6IDEyMCwgaGVpZ2h0OiA4MCwKICB0b3VjaHN0YXJ0OiBmdW5jdGlvbihsYXllcikgewogICAgLy8gQW5pbWF0ZSBsYXllciB3aGVuIHRvdWNoZWQKICAgICQodGhpcykuYW5pbWF0ZUxheWVyKDAsIHsKICAgICAgZmlsbFN0eWxlOiAnI2MzMycsCiAgICAgIHNjYWxlOiAxLjUKICAgIH0sIDI1MCk7CiAgfSwKICB0b3VjaGVuZDogZnVuY3Rpb24obGF5ZXIpIHsKICAgIC8vIFJldmVydCBsYXllciB3aGVuIHRvdWNoIGVuZHMKICAgICQodGhpcykuYW5pbWF0ZUxheWVyKDAsIHsKICAgICAgZmlsbFN0eWxlOiAnIzM2YycsCiAgICAgIHNjYWxlOiAxCiAgICB9LCAyNTApOwogIH0KfSk7) doens't work with IE and Edge. 
I tried it on a touch-enabled devices (Lenovo ThinkPad Yoga 460, Win10).

But if I'm using a pur javascript with pointerdown, pointermove and pointerup, it works.

**Comment by caleb531** [comment]
Hi, @bliet. I apologize in advance for the late response.

I modified the jCanvas source to add basic support for the `pointerdown`, `pointermove`, and `pointerup` events. Please try out the updated jcanvas.js on the [feature-pointer-events](https://github.com/caleb531/jcanvas/tree/feature-pointer-events) branch and let me know how it works for you.

**Comment by bliet** [comment]
Hi, very nice. I will try it next monday.

**Comment by caleb531** [comment]
@bliet, any update on how the jCanvas build from the `feature-pointer-events` branch is working for you?

**Comment by bliet** [comment]
I'm sorry for the late response. At the moment this part of our project has a less importance. But I will try the branch soon.
