### ISSUE TITLE
Drawing with mouse movement

### ISSUE THREAD

**Issue by dadixon** [caleb531/jcanvas#260]
I figured out how to draw lines with mouse movement but have an issue when the mouse leaves that canvas. Everything that I drew disappears. I'm redrawing everything on mouse out so I don't know why it doesn't work.

```js
var $canvas2 = $("#RCFT1");
var pts2 = [];
var lines2 = [];
var line_obj2 = {};
var isDown2 = false;

//Setup Drawing Surfaces for Actual Test
$canvas2.drawRect({
    layer: true,
    x: 0, y: 0,
    width: 460, height: 470,
    fromCenter: false,
    mousedown: function (layer) {
        line_obj2 = {
            strokeStyle: "#000",
            strokeWidth: 2,
            data: {
                joints: 1
            }
        };
        isDown2 = true;
        pts2.push([layer.eventX, layer.eventY]);
        redraw($(this), lines2);
    },
    mousemove: function (layer) {
        if (isDown2) {
            pts2.push([layer.eventX, layer.eventY]);
            for (var p = 0; p < pts2.length; p += 1) {
                line_obj2['x' + (p + 1)] = pts2[p][0];
                line_obj2['y' + (p + 1)] = pts2[p][1];
            }
            $(this).drawLine(line_obj2);
        }
        redraw($(this), lines2);
    },
    mouseup: function (layer) {
        lines2.push(line_obj2);

        redraw($(this), lines2);

        line_obj2 = {};
        pts2 = [];
        isDown2 = false;
    },
    mouseout: function (layer) {
        console.log(lines2);

        redraw($(this), lines2);
    }
});

function redraw($canvas, linesArray) {
	for (var i = 0; i < linesArray.length; i++) {
	    $canvas.drawLine(linesArray[i]);
	}
}
```

**Comment by caleb531** [comment]
The reason the lines are disappearing is because they aren't jCanvas layers. In jCanvas, layers and non-layer drawings cannot exist on the same canvas, because when jCanvas clears the canvas to redraw the layers it knows about, the non-layers will be erased. In other words, if you have at least one jCanvas layer on your canvas, then everything else you draw must be a jCanvas layer.

Therefore, you should be setting `layer: true` in the object you pass to `drawLine` (you should also specify a `name` so you can retrieve that layer later). Layers-redrawing will be done automatically by jCanvas as needed and whenever you call `$canvas.drawLayers()`. If you need to change the properties of any of your line layers, use the `setLayer()` method:

```js
$canvas.setLayer('myLayerName', {
  x2: 20, y2: 20
});
```

I hope that helps, @dadixon. Let me know if you have any questions on this. :)
Caleb

**Comment by dadixon** [comment]
That does help. I tried that before but I have another issue when I run with the different layers. On my mouse move, if I draw over another layer, it "hides in the background" kind of. Should I add an index to the layer also?

**Comment by caleb531** [comment]
I'm not exactly sure what you mean by the laying "hiding in the background." I don't think you need to set an index, but could you please provide some code to show how you are adding the layer?

**Comment by dadixon** [comment]
`var practice_name = 0;

            //Setup Drawing Surfaces for Test
            $canvasPractice.drawRect({
                layer: true,
                x: 0, y: 0,
                width: 800, height: 450,
                fromCenter: false,
                mousedown: function (layer) {
                    practice_name++;

                    line_objPractice = {
                        layer: true,
                        type: 'line',
                        name: "practice" + practice_name,
                        bringToFront: true,
                        strokeStyle: "#000",
                        strokeWidth: 2,
                        data: {
                            joints: 1
                        }
                    };

                    isDownPractice = true;
                    ptsPractice.push([layer.eventX, layer.eventY]);

                    $(this).addLayer(line_objPractice).drawLayers();
                },
                mousemove: function (layer) {
                    if (isDownPractice) {
                        ptsPractice.push([layer.eventX, layer.eventY]);
                        for (var p = 0; p < ptsPractice.length; p += 1) {
                            line_objPractice['x' + (p + 1)] = ptsPractice[p][0];
                            line_objPractice['y' + (p + 1)] = ptsPractice[p][1];
                        }
                        $(this).drawLine(line_objPractice);
//                        $(this).setLayer("practice" + practice_name, line_objPractice).drawLayers();
                    }
                },
                mouseup: function (layer) {
                    linesPractice.push(line_objPractice);
                    $(this).setLayer("practice" + practice_name, line_objPractice).drawLayers();

                    line_objPractice = {};
                    ptsPractice = [];
                    isDownPractice = false;
                }
            });`

When I try to draw a cross and I get to the part where the lines cross, the last layer disappears for a second.

**Comment by dadixon** [comment]
This helps out a TON.  Been on this for weeks

**Comment by dadixon** [comment]
I got it. I had to move the layer down to index 0. Works now. Thanks

**Comment by caleb531** [comment]
Works for me! :+1:
