### ISSUE TITLE
Click not working on rotate animation

### ISSUE THREAD

**Issue by Devintelligence** [caleb531/jcanvas#261]
I made an animate rotation right and left.

While the rotation animation the click function is not working

Any idea whats wrong?

[test.zip](https://github.com/caleb531/jcanvas/files/642449/test.zip)

**Comment by caleb531** [comment]
Hi, @Devintelligence. Could you please clarify what you mean, and where I should be looking in your code? Where should I be clicking in your demo?

Caleb

**Comment by caleb531** [comment]
@Devintelligence, any updates?
