### ISSUE TITLE
drag not working on FF mobile

### ISSUE THREAD

**Issue by mikegogulski** [caleb531/jcanvas#262]
Hi,

demo at http://gnar.gogulski.com/

I've got a transparent overlay layer which, on dragging, moves the inset layer, which is lower in the z-order.

Works on Chromium/desktop, FF/desktop, and Chrome/mobile but not in FF/mobile.

jcanvas.js at line 594 has
```
dragHelperEvents = [ 'mousedown', 'mousemove', 'mouseup' ];
```

This may need to be expanded to include touch events for platforms that don't fire mouse events for touch interactions.

**Comment by caleb531** [comment]
In reality, jCanvas is binding both mouse events and their corresponding touch events for dragging. Check out [jcanvas.js#2258](https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L2258) in the source (and the surrounding lines for context):

```js
helperEventName = ( eventName === 'mouseover' || eventName === 'mouseout' ) ? 'mousemove' : eventName;
touchEventName = _getTouchEventName( helperEventName );
// ...
// Bind one canvas event which handles all layer events of that type
if ( touchEventName !== helperEventName ) {
	$canvas.bind( helperEventName + '.jCanvas ' + touchEventName + '.jCanvas', eventCallback );
} else {
	$canvas.bind( helperEventName + '.jCanvas', eventCallback );
}
```

In effect, `mousedown` and `touchstart` are both bound to the canvas. I've tested this on Mobile Safari (and in your case, Chrome/mobile) without issue, so I have reasoned that binding both events is fine, as the touchstart will take precedence over the mousedown. However, I have two theories for why this doesn't work in FF/mobile:

1. The mousedown is actually interfering with the touchstart event. You should be able to test this by calling `$myCanvas.off('mousedown.jCanvas mousemove.jCanvas mouseup.jCanvas')` and seeing if touch events then work as expected on FF/mobile
2. FF/mobile doesn't support `touchstart`/`touchmove`/`touchend` events at all, which you can test by checking if `document.body.ontouchstart` is undefined (or not) on FF/mobile

**Comment by mikegogulski** [comment]
Hi Caleb, thanks for getting back to me.

`$myCanvas.off('mousedown.jCanvas mousemove.jCanvas mouseup.jCanvas')` doesn't produce any noticeable change in behavior for me, whether in FF mobile or elsewhere.

I don't know how to get to a JS console in FF mobile, so I changed an element's behavior depending on whether or not `document.body.ontouchstart` is defined:

```
  if (typeof(document.body.ontouchstart) != "object") {
    $('#scalereset').on('click', function(e) {alert('fnord');});
  }
```

The alert doesn't appear in FF mobile, so I assume that the event is there... but I'm sort of playing out of my depth here.

**Comment by caleb531** [comment]
Just to be sure, are you calling `$myCanvas.off` *after* you initialize your layers? (as the events are bound at the time you add your layers with `addLayer` or `draw*` with `layer: true`.

Also, don't rely on the `typeof` operator; it can lie to you:

```
typeof null // returns "object"
```

I would recommend that you instead check if `document.body.ontouchstart === undefined`. `document.body.ontouchstart` will be `null` or a function if the browser supports the event, otherwise `ontouchstart` will be `undefined`.

**Comment by mikegogulski** [comment]
1: Yes. I set up the jcanvas object, do a bunch of `addLayer()`s on it, `drawLayers()` and then the `.off(...)`. You can see it (commented out) at https://gnarlify.me/js/script.js

2: Okay, I substituted your test for mine in the code I gave above. Same result. It's also there, at the bottom of the script in the link above.

**Comment by caleb531** [comment]
Hmm, I'm running out of ideas. Can you please run this code on FF mobile and tell me which alert it shows?

```js
var $canvas = $('canvas');

$canvas.drawArc({
  fillStyle: '#6c3',
  x: 100, y: 100,
  radius: 50
});

$canvas.on('touchstart', function(event) {
  
  var touches = event.originalEvent.changedTouches;
  
  if (touches) {
    
   	alert('Supports changedTouches');
    
  } else {
   
    alert('Does not support changedTouches');
    
  }
  
});
```

**Comment by caleb531** [comment]
@mikegogulski any update on trying the above code?
