### ISSUE TITLE
Setting cursor url doesn't work

### ISSUE THREAD

**Issue by r0fls** [caleb531/jcanvas#263]
This is probably just user error, but I don't see anything in the docs. When I do:

```
cursors: {
                mouseover: "url('../some/path.png')",
},  
```

Nothing shows up, though the url is correct and also this does work:

```
cursors: {
                mouseover: "pointer",
},  
```

Is there a different URL syntax?

**Comment by caleb531** [comment]
Your syntax is correct. Any valid CSS `cursor` value is accepted.

I would first check the console to ensure that a 404 isn't being thrown—I suspect your relative path may not be pointing where you think. Because the `cursors` property applies a CSS `cursor` to the `<canvas>` element, and because that `<canvas>` element resides in your HTML document, the cursor path will be relative to your HTML document.

**Comment by r0fls** [comment]
@caleb531 thank you for the fast response, you are awesome. I did try the full path, which was  `"url('http://localhost:3000/assets/cursor.png')"` in my case, and it still didn't work :( I know the image is there, because it loads in my browser and I don't see any 404s in the inspector. However I don't see the image being loaded there either...

**Comment by r0fls** [comment]
Is there anything I need to take into consideration if this is the index 0 image, and there are other layers on top with different cursors?

**Comment by caleb531** [comment]
Potentially. Could you please send me a screenshot of what that stack of layers looks like on the canvas?

**Comment by r0fls** [comment]
I think the problem was that I wasn't using valid css:

This worked:
```
       cursors: {
                mouseover: "url(../assets/cursor.png), auto",
            },  
```

This didn't

```
       cursors: {
                mouseover: "url(../assets/cursor.png)",
            },  
```

Thanks again for your help and for writing this library. I'm closing this issue, but I think an example using a URL in the docs would be helpful :) Are those open source? I can add it if they are...

**Comment by caleb531** [comment]
Great! I suppose I need to relearn the syntax. I haven't used image CSS cursors in quite some time.

And yes, the website are all of the documentation are now completely open source. See:
https://github.com/caleb531/jcanvas-website/tree/master/_core_docs
