### ISSUE TITLE
How to put an image mask by other Image ?

### ISSUE THREAD

**Issue by uknowzheng** [caleb531/jcanvas#270]
![theme_icon_widget_memory_mask](https://cloud.githubusercontent.com/assets/4647461/22728635/13bf3af2-ee1a-11e6-8695-1436f3f4fdf4.png)
A Image
![default_icon](https://cloud.githubusercontent.com/assets/4647461/22728636/13cd8648-ee1a-11e6-970e-0e672e1a7060.png)
B Image
I want to use A to mask B Image（In same Size weight and Height），how can i do(use addLayer())？

**Comment by caleb531** [comment]
You can't really use an *image* as a mask in jCanvas. But you *can* use a jCanvas path as a mask (using `drawPath` with `mask: true`). Therefore, I would recommend recreating the shape in *Image A* as a path, and then using that path to mask *Image B*:

```js
$('canvas')
.drawPath({
  layer: true,
  mask: true,
  fillStyle: '#000',
  closed: true,
  x: 160, y: 150,
  // Top petal
  p1: {
    type: 'arc',
    x: 0, y: -50,
    start: -90, end: 90,
    radius: 50
  },
  // Right petal
  p2: {
    type: 'arc',
    x: 50, y: 0,
    start: 0, end: 180,
    radius: 50
  },
  // Bottom petal
  p3: {
    type: 'arc',
    x: 0, y: 50,
    start: 90, end: 270,
    radius: 50
  },
  // Left petal
  p4: {
    type: 'arc',
    x: -50, y: 0,
    start: 180, end: 360,
    radius: 50
  }
})
.drawImage({
  layer: true,
  source: 'images/fish.jpg',
  x: 150, y: 150
})
.restoreCanvas();
```

**Comment by uknowzheng** [comment]
$.jCanvas.extend({
    name: 'drawMaskImage',
    type: 'maskImage',
    props: {
        maskUrl: ''
    },
    fn: function (ctx, params) {
        var p = params;
        var imagecanvas = document.createElement('canvas');
        var imagecontext = imagecanvas.getContext('2d');
        var newImg = document.createElement('img');
        newImg.src = p.source;
        newImg.onload = function () {
            var width = p.width;
            var height = p.height;
            var mask = document.createElement('img');
            mask.src = p.maskUrl;
            mask.onload = function () {
                imagecanvas.width = width;
                imagecanvas.height = height;
                imagecontext.drawImage(mask, 0, 0, width, height);
                imagecontext.globalCompositeOperation = 'source-in';
                imagecontext.drawImage(newImg, 0, 0, width, height);
                newImg.src = imagecanvas.toDataURL();

                ctx.drawImage(newImg, p.x, p.y, width, height);
                $.jCanvas.detectEvents(this, ctx, p);
                // Check for jCanvas events
                // Close path and configure masking
            }
        }
    }
});

**Comment by caleb531** [comment]
@uknowzheng, I see your `extend()` code, but I don't know why you are posting it. Is it not working for you? Do you have any further questions? :)

**Comment by uknowzheng** [comment]
Yes，I have a question。I want to use custom types, and use Layer to layout, but found that the type of expansion can not be in accordance with the normal order to draw. @caleb531

**Comment by caleb531** [comment]
Hmm, I see. That's a much trickier to solve. I was originally able to make it work for images (`type: 'image'`), but extending that capability to custom types would require some unpleasant rewriting that may take a bit of time.

My only suggestion at this point would be to preload the mask image object before drawing any layers.

**Comment by uknowzheng** [comment]
yes，you are right @caleb531
