### ISSUE TITLE
How i Can able to remove $('#abc').drawArc({ });  with for loop

### ISSUE THREAD

**Issue by BharatGK** [caleb531/jcanvas#272]
Hey,

I have drawn some drawArc({}) and i need to remove drawn point, how i can do that?
Is there any function that i can able to call from angularjs?

OR
How i can remove drawArc({}) without page refresh?
Please do suggest!

**Comment by caleb531** [comment]
Are you asking how you can remove the entire arc from the canvas? Could you please provide the code you are using? (whatever you are able to provide would help)

**Comment by BharatGK** [comment]
Hey caleb531,

I am drawing arc on canvas with for loop like:

for(i=0;i<3;i++)
$('canvas')
.drawArc({
	draggable: true,
	fillStyle: 'red',
	x: 15, y: 15,
	radius: 15,
	dragstart: function() {
	// code to run when dragging starts
	},
	drag: function(layer) {
	// code to run as layer is being dragged
	},
	dragstop: function(layer) {
	// code to run when dragging stops
	}
});

I have to remove all drawn arc without page reload, how i can do that..
BTW thanks for reply.!

**Comment by caleb531** [comment]
I see. :) To clarify: do you want to hide the arcs temporarily (with the intent to show them again later) or do you want to remove them permanently from the canvas? (I ask because it determines which solution I recommend for your particular use case)

Caleb

**Comment by BharatGK** [comment]
I want to remove permanently because i am redrawing it

**Comment by caleb531** [comment]
Got it. In that case, I would recommend assigning a layer group to your arc layers (via the `groups` property), and then using `removeLayerGroup` later remove all layers in that group. See my example below; you can easily see the effect if you run it in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/).

```js
var $canvas = $('canvas');
for (i = 0; i < 3; i++) {
  $canvas.drawArc({
    draggable: true,
    groups: ['myarcs'],
    fillStyle: 'red',
    x: 30 * (i + 1), y: 30 * (i + 1),
    radius: 15,
    dragstart: function() {
      // code to run when dragging starts
    },
    drag: function(layer) {
      // code to run as layer is being dragged
    },
    dragstop: function(layer) {
      // code to run when dragging stops
    }
  });
}
setTimeout(function() {
  $canvas.removeLayerGroup('myarcs');
  $canvas.drawLayers();
}, 1000);
```

**Comment by BharatGK** [comment]
@caleb531 
Thanks a lot man.!
Will try and let u know 
Thanks keep building!

**Comment by BharatGK** [comment]
@caleb531 
Thanks. It working fine...

One more, can i set containment to arc, means it should not be hide under border.
![containment](https://cloud.githubusercontent.com/assets/20225402/23034794/f8b55734-f4a2-11e6-8815-520092cad209.PNG)

**Comment by caleb531** [comment]
Absolutely! Confining the layer to a particular region can be done by overriding `layer.x` and `layer.y` within the `drag` event callback for that layer. See the example below, where the layer is completely restricted to the boundaries of the canvas. As always, you can run this example in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/).

```js
$('canvas').drawArc({
  draggable: true,
  fillStyle: '#c33',
  x: 100, y: 100,
  radius: 50,
  drag: function(layer) {
    // Set boundary at left edge of canvas
    layer.x = Math.max(layer.radius, layer.x);
    // Set boundary at right edge of canvas
    layer.x = Math.min(layer.x, layer.canvas.width - layer.radius);
    // Set boundary at top edge of canvas
    layer.y = Math.max(layer.radius, layer.y);
    // Set boundary at bottom edge of canvas
    layer.y = Math.min(layer.y, layer.canvas.height - layer.radius);
  }
});
```

**Comment by BharatGK** [comment]
thanks @caleb531,
for your Usain Bolt response.
You made my day as well as night.
thanks

**Comment by BharatGK** [comment]
Hey  caleb531,

Can i set title on $canvas.drawArc so i can identify which drawArc for certain text.
Like:
![title on drawn arc](https://cloud.githubusercontent.com/assets/20225402/23152117/c57bd632-f825-11e6-87d1-b006d913c4e7.PNG)
