### ISSUE TITLE
Can i set title on $canvas.drawArc?

### ISSUE THREAD

**Issue by BharatGK** [caleb531/jcanvas#273]
Hey caleb531,

Can i set title on $canvas.drawArc so i can identify which drawArc for certain text.
Like:
![title on drawn arc](https://cloud.githubusercontent.com/assets/20225402/23161935/07ce0efc-f852-11e6-872a-06e5d2f46ba7.PNG)

**Comment by caleb531** [comment]
The way to add text labels in jCanvas is to use `drawText` to add a text layer ([docs here](https://projects.calebevans.me/jcanvas/docs/text/)). If the arc is draggable, then you can utilize [drag groups](https://projects.calebevans.me/jcanvas/docs/draggableLayers/#drag-groups) to ensure that the text moves with the arc when dragged (or vice versa).

**Comment by BharatGK** [comment]
Hey Caleb531,

Can i set text to hover, means whenever i point it, then and then only text will appear?

**Comment by caleb531** [comment]
Sure! Use `setLayer` combined with the `visible` property to hide the text initially, only showing the text when the user has moused over the circle:

```js
$('canvas')
.drawArc({
  layer: true,
  fillStyle: '#9cf',
  strokeStyle: '#000',
  strokeWidth: 4,
  x: 180, y: 150,
  radius: 70,
  mouseover: function(layer) {
    $(this).setLayer('myText', {
      visible: true
    });
  },
  mouseout: function(layer) {
    $(this).setLayer('myText', {
      visible: false
    });
  }
})
.drawText({
  layer: true,
  visible: false,
  name: 'myText',
  fillStyle: '#36c',
  strokeWidth: 2,
  x: 180, y: 150,
  fontSize: '36pt',
  fontFamily: 'Verdana, sans-serif',
  text: 'Hello'
});
```

**Comment by BharatGK** [comment]
Hey caleb531,
Thanks for response. But there are some issues:

1. I have to show text on hover with multiple arc
So if hover on first arc(A), text will showing on second arc(B). Like:
![issue1](https://cloud.githubusercontent.com/assets/20225402/23248698/c3cf4d80-f9c6-11e6-8e84-e9f854a9t6072.png)

2. Text is not draggable,
When i drag arc from one position to another, text remains on start position means text is not draggable.
Like:
![issue2](https://cloud.githubusercontent.com/assets/20225402/23248748/02c14214-f9c7-11e6-8c35-3fde54ef7bea.png)

Please do suggest!
Thanks

**Comment by caleb531** [comment]
1. You can place the text wherever you want—it doesn't need to necessarily be over an arc.

2. Check out [drag groups](https://projects.calebevans.me/jcanvas/docs/draggableLayers/#drag-groups), a jCanvas feature intended to solve that exact problem
