### ISSUE TITLE
The element will still appear even I clearCanvas

### ISSUE THREAD

**Issue by zxd882002** [caleb531/jcanvas#274]
Hi caleb531,

I am using JCanvas on my project. However, I find the following issue.

Here is the code

```js
$(document).ready(function () {
            $('#metroCanvas').draw({
                layer: true,
                draggable: true,
                groups: ['Metros'],
                dragGroups: ['Metros'],
                type: 'text',
                strokeStyle: 'black',
                strokeWidth: 1,
                fontSize: 4,
                fontFamily: 'SimSun',
                text: "test",
                x: 100,
                y: 100
            });
            $('#metroCanvas').clearCanvas();
        })
```

I use the jquery and jcanvas verison:
```html
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.0.0.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jcanvas/16.7.3/jcanvas.min.js"></script>
```

and body only contain this canvas:
```html
<div>
    <canvas id="metroCanvas"></canvas>
</div>
```
I debug it and find after calling the clearCanvas(), the 'test' string will disappear. However when the mouse move inside the canvas. The 'test' string will appear again.

Do you know why it will appear again? How to fix it?

**Comment by caleb531** [comment]
You're not the only one who's asked this question, which is why I mention this in the jCanvas documentation [(see this section for the clearCanvas docs](https://projects.calebevans.me/jcanvas/docs/clearCanvas/#a-note-about-layers)).

**Comment by zxd882002** [comment]
Thank you for your quick feedback. I add the removeLayers() and then clearCanvas(), it will be not shown now.

**Comment by caleb531** [comment]
Don't use `clearCanvas()` at all. Calling `clearCanvas()` is useless when you draw anything with `layer: true`, because it will inevitably be redrawn later. If you want to redraw the canvas after removing layers, call `drawLayers()` instead.
