### ISSUE TITLE
Draggable to permitted zones

### ISSUE THREAD

**Issue by karimun** [caleb531/jcanvas#275]
Hello caleb531,
is it possible to define "zones" in the canvas for allowing layers to be moved ("dropped") only into these?

My approach would be to initially define such "permitted zones" by drawRect() with layer: true, intangible=true
Then I would do coordinate comprisons in the dragstop function to evaluate if the dragged layer is "inside" of a "permitted zone".

Is this the most elegant way to achieve it or have I missed a dedicated API function that already cares of "permitted zones"? Maybe you could also post an example on how you would do the mentioned coordinate comparison. Thank you

**Comment by caleb531** [comment]
Nope, there's no special jCanvas API for that—the `dragstop` approach you've described is exactly what I would recommend.

The coordinate comparison depends on the kind of layers you are interacting with. If they are mere rectangular shapes (rectangle, image, _etc._), then the algorithm depends on if you have `fromCenter: false` or not. You also need to consider if the draggable layer must be fully within the boundaries of its zone, or if some partial portion of the rectangle can be outside of the zone as long as some percentage is within the zone. The algorithm you use greatly depends on these factors.

**Comment by karimun** [comment]
Hello celeb531,
I came up with following code:
---------------------------------------------

`// Draw the DropZone

$('canvas').addLayer({'name':'dropzone', type:'rectangle', intangible:true, x:200, y:300,width:100, height:100, strokeStyle:'#000', strokeWidth:1, fillStyle:'transparent'}).drawLayers();

// Draw the draggable Element

var x_init = 100;
var y_init = 100;

$('canvas').addLayer({
'name':'dropme', type:'rectangle', draggable:true, x:x_init, y:y_init, width:100, height:100, fillStyle:'#f00',

data: {x_init:x_init, y_init:y_init},

drag: function(layer) {
dropzone = $('canvas').getLayer('dropzone');
if(dropzone.intersects){layer.x = dropzone.x; layer.y = dropzone.y;}
},

dragstop: function(layer){
dropzone = $('canvas').getLayer('dropzone');
if(!dropzone.intersects){layer.x = layer.data.x_init; layer.y = layer.data.y_init;}
}

}).drawLayers();`

---------------------------
Is there no other way but calling getLayer('dropzone') inside drag?
My project will have multiple dropzones, so I would need to additionally loop through an DropzoneArray ..

**Comment by caleb531** [comment]
Calling `getLayer` within `drag` like that will be extremely inefficient because `getLayer` will be called with the same value for every pixel you drag the layer. I would recommend instead that you store `getLayer('dragzone')` into a variable *outside of* the `drag` callback.

Even more, since you say you will have multiple dropzones, I would encourage you to utilize a feature in jCanvas called layer groups (see [here](https://projects.calebevans.me/jcanvas/docs/addLayers/#grouping-layers) and [here](https://projects.calebevans.me/jcanvas/docs/retrieveLayers/#retrieving-layer-groups)). Then, you can loop over your retrieved layer groups array within your `drag` callback. That's really the best way to do this.

**Comment by karimun** [comment]
Success, I think ..

// Define the Dropzones Group as Variable:

$dropzones = $('canvas').getLayers(function(layer){return (layer.groups.indexOf("dropzone") !== -1);});

// The Live Action:

drag: function(layer){

if($dropzones.length > 0){ for(var AyKey in $dropzones) {
if($dropzones[AyKey]['intersects'] === true){ layer.x = $dropzones[AyKey].x; layer.y = $dropzones[AyKey].y; }
}}
} // drag

dragstop: function(layer){

var flag_PointerOnDropZone = false;
if($dropzones.length > 0){ for(var AyKey in $dropzones) {
if($dropzones[AyKey]['intersects'] === true){var flag_PointerOnDropZone = true; break;}
}}
if(!flag_PointerOnDropZone){layer.x = layer.data.x_init; layer.y = layer.data.y_init;}

} // dragstop

.. works for me. Being much more into PHP, I was not even conscious about defining variables outside in this scenario, but its the only solution that makes sense. Thanks!
