### ISSUE TITLE
No way to tell if drawLayers has finished

### ISSUE THREAD

**Issue by r0fls** [caleb531/jcanvas#277]
Would you accept a PR that adds another function, i.e. `willDrawLayers` (or some other name) that returns a promise to draw the layers? Right now there is no way to tell if this function has finished, which has resulted in an issue for me. Otherwise, does `drawLayers` currently support callbacks?  Let me know if you need further information describing my situation.

**Comment by caleb531** [comment]
Hi, @r0fls. `drawLayers` runs synchronously, so you should always be able to tell when it finished. Are you trying to run `drawLayers` asynchronously? What is your specific use case?

**Comment by r0fls** [comment]
Basically I'm copying the canvas, then drawing some more stuff on the new copied canvas, then calling `drawLayers`. Finally, converting that canvas to a dataURL, but the dataURL doesn't contain the updates after drawing on the new canvas. Here is some sample code:

```javascript
function copyCanvas() {
          var canvas = document.createElement("canvas");
          canvas.setAttribute('id', 'pdf-canvas');
          var destCtx = canvas.getContext('2d');
          var sourceCanvas = document.getElementById('drawingboard-canvas');
          destCtx.drawImage(sourceCanvas, 0, 0); 

          $("#pdf-canvas").setLayerGroup('some_group', {
                  color: red,
          }); 
          $("#pdf-canvas").setLayer('some_layer', {
                  color: blue, 
          }); 

          $("#pdf-canvas").drawLayers();
          var dataURL = canvas.toDataURL();
          return {
                  image: dataURL,
                  width: 500 
          }   
 }   
```

**Comment by caleb531** [comment]
Well, I don't know how accurate your sample code is compared to your actual code, but I can only judge what I see:

1. There is no `color` property in jCanvas; perhaps you meant `fillStyle` or `strokeStyle`?
2. This is merely an efficiency concern, but if you already have access to the DOM element `canvas`, then you don't need to call `$('#pdf-canvas')`. Just reference `$(canvas)` (and perhaps store it in a variable for easy reuse) like so:  
```js
var $canvas = $(canvas);
$canvas.setLayerGroup('some_group', {
  // ...
```

Also, now that I think about it, are any of your jCanvas layers images? Images in jCanvas are actually drawn asynchronously, and `drawLayers()` is told to wait for images to load before drawing successive layers. Maybe this is causing your issue?

**Comment by r0fls** [comment]
@caleb531 sorry i'm not actually setting the color, poor example. Safe to say it is a valid jcanvas property (namely opacity).

**Comment by r0fls** [comment]
@caleb531 Also yes that sounds like the issue, there are some images being drawn.

**Comment by caleb531** [comment]
Alright, I've made a few tweaks to add support for a `complete` callback to `drawLayers`, which runs when all layers have finished drawing.

Here's the basic usage:

```js
$myCanvas.drawLayers({
  complete: function() {
    // code here runs when all layers have finished drawing
  }
});
```

You can download the updated jCanvas build below. Please try it and let me know if it solves your particular issue. :)

[jcanvas.js.zip](https://github.com/caleb531/jcanvas/files/836895/jcanvas.js.zip)

**Comment by r0fls** [comment]
Awesome, thank you! I'll try this out later today and let you know how it goes.

**Comment by r0fls** [comment]
@caleb531 I still haven't gotten this working but it's partially because the new canvas is not copying correctly. Debugging within drawlayers, I see `this` is showing as the below for the original canvas:

```
[canvas#original-canvas.background.jpg]
```

However for the copied canvas it shows as:

```
j…y.fn.init {context: document, selector: "#new-canvas"}
```

I'm using the same way of selecting them (with jQuery), but the context within `drawLayers` is different:

```
$("#new-canvas").drawLayers()
$("#old-canvas").drawLayers()
```

Do you know what could be causing this? I'm basically using the above snippet to copy the original canvas.

**Comment by caleb531** [comment]
@r0fls I'm surprised, and in disbelief. Could you please show me the statement(s) you ran for each output snippet in your comment?

**Comment by r0fls** [comment]
@caleb531 it turns out the issue is actually that copying the canvas (as shown above) doesn't copy the layers. So, modifying them wasn't doing anything... I'm still trying to initialize the old layers onto the new canvas, but feel free to close this issue out if you like since it's seeming to be unrelated to that issue.

Thank you.

**Comment by caleb531** [comment]
Nah, it's still related. :)

jCanvas stores its data for each canvas element as jQuery data (set using `$.data`). I believe jQuery's [clone()](https://api.jquery.com/clone/) method will copy this data if you specify the appropriate arguments (see the `withDataAndEvents` and `deepWithDataAndEvents` parameters in the aforementioned method docs).

**Comment by r0fls** [comment]
That did the trick. There was no async issue, it was just simply not copying the jCanvas data so I couldn't modify it and `drawLayers` hence had nothing to draw. Thanks again!
