### ISSUE TITLE
drawImage fails with SRCSET

### ISSUE THREAD

**Issue by stefan-scholl** [caleb531/jcanvas#279]
https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L3966 checks for src property. But some responsive themes could use property srcset instead of src. Now the "else" part is executed, because source.src is an empty string.

But as img elements (at least on Firefox 52) don't have a match() function, it crashes at https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L3977

Sorry, no test case. I'm not using jCanvas. I've found this while debugging a third party product that uses jCanvas v15.10.08. But the code still looks like it would fail with an empty source.src.

**Comment by caleb531** [comment]
In my experience, `src` must be present, regardless of the presence of `srcset`. [The spec affirms this](http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset) (emphasis mine):

> **The src attribute *must* be present**, and must contain a valid non-empty URL potentially surrounded by spaces referencing a non-interactive, optionally animated, image resource that is neither paged nor scripted.
> 
> **The srcset attribute *may* also be present**. If present, its value must consist of one or more image candidate strings, each separated from the next by a U+002C COMMA character (,). If an image candidate string contains no descriptors and no space characters after the URL, the following image candidate string, if there is one, must begin with one or more space characters.

More practically, `src` serves as a fallback if `srcset` is unsupported by the browser (and sure enough, even IE 11 does not currently support `srcset`). See http://caniuse.com/#search=srcset

You should contact the developer of the third-party product you're using to see if this can be fixed on their end, or see if you can fix it yourself if you have access to the code.
