### ISSUE TITLE
Question: is there any recipe to do an inverse fill?

### ISSUE THREAD

**Issue by r0fls** [caleb531/jcanvas#280]
What I'm trying to do is fill an area outside of a circle. Of course the obvious solution is to set the entire canvas background, then draw a new `fillStyle` arc within that. However this is all happening over an existing image, so I'm not sure how to remove the overlaying background within the arc, if that makes sense...  🤔

**Comment by caleb531** [comment]
jCanvas supports a special `compositing` property (which maps to the native canvas `globalCompositeOperation` property). It sounds like exactly the kind of behavior you need:

https://projects.calebevans.me/jcanvas/docs/properties/#compositing
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by r0fls** [comment]
Works like a charm. Thanks once again!
