### ISSUE TITLE
Handle Plugin: How to limit handle dragging/moving

### ISSUE THREAD

**Issue by botorabi** [caleb531/jcanvas#282]
Hi caleb,

first of all, big thanks for the wonderful work. I learned to love jCanvas.

I am trying to use a polygon for selecting an area on a canvas. It has 8 sides and handles on each corner (by using the Handles plugin). Everything works fine, except a small issue: it is possible to drag the corner handles outside of the canvas. I would like to limit the corner dragging to inner area of the canvas. The same is true also for my elipse which has handles for resizing it.

What is the best way to achieve such limiting of handle dragging to the canvas area?

Btw: the major problem exists on smartphones handling with touch events. On Desktop, while handling mouse events the embedding canvas limits the events, so the problem is less tedious (although I would prefer to further limit the area to say 90% of inner area).

**Comment by caleb531** [comment]
Hi. @botorabi.

Sorry I haven't gotten to you sooner, but I just wanted to let you know that this is currently not possible, but it should be after I make a few tweaks to Handles. I will try to modify the build and share some example code tomorrow. :)

Caleb

**Comment by botorabi** [comment]
Hi @caleb531

_>  I will try to modify the Handles source and share some example code tomorrow. :)_

It sounds great, thank you.

**Comment by caleb531** [comment]
Okay, @botorabi, check out the `handle-drag` branch on this repository. I've updated `jcanvas.js` with new `constrainDragX` and `constrainDragY` properties.

The following example contains the handles to the explicit boundaries of the canvas using these new properties.

```js
$('canvas').addLayer({
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10,
    constrainDragX: function(layer, x) {
      x = Math.max(layer.radius, x);
      x = Math.min(x, $(this).width() - layer.radius);
      return x;
    },
    constrainDragY: function(layer, y) {
      y = Math.max(layer.radius, y);
      y = Math.min(y, $(this).height() - layer.radius);
      return y;
    }
  }
})
.drawLayers();
```

Let me know if this works for you, or if you have any other questions, @botorabi. :)
Caleb

**Comment by botorabi** [comment]
Hi caleb,

I have tested the solution in branch handle-drag. I can confirm that it works fine, thx for the extension!

One thing I have seen is that the new version (in comparision to version v16.07.03) got a few new lines of code, which may be the reason why I am no longer able to draggmove an image layer. I my app there are a couple of layers: background (gray color), image (which should be dragmovable), and two ellipse and polygon layers with handles. The following lines (in new code prevent me to dragmove the image layer:

`
// Determine if the given coordinates are in the current path
if ( ctx.isPointInStroke && layer.closed === false && layer.fillStyle === 'transparent' ) {
    intersects = ctx.isPointInStroke( x, y );
} else {
    intersects = ctx.isPointInPath( x, y ) || ( ctx.isPointInStroke && ctx.isPointInStroke( x, y ) );
}
`

In previous version the code looked like this:

`intersects = ctx.isPointInPath( x, y ) || ( ctx.isPointInStroke && ctx.isPointInStroke( x, y ) );`

Maybe I have to consider something in my layer parameters, I will check that in detail. However, it may be that the new code indeed introduces an issue with image layer dragging.

@caleb531 I thank you again for the great work. I will publish my project soon, so you could see yourself what I use jCanvas for :-)

**Comment by caleb531** [comment]
Nothing wrong with your code—this is absolutely my fault. :P

The condition I added isn't specific enough—images technically aren't closed and don't have fills, so that condition evaluates to true when it should only do so for path layers with the same parameters. However, I don't want to make the condition much more specific because it's just additional complexity with behavior that varies from browser to browser (*e.g.* IE doesn't support `isPointInStroke` at all). Therefore, I am decidedly reverting that change.

I have also merged `handle-drag` into `master` since I am content with the `constrainDragX` and `constrainDragY` properties. However, I won't be pushing a new release yet—I'm still working on some big changes to the jCanvas build setup, and I'd like to finish those before declaring the next release (see the `build` branch if you're curious). Regardless, feel free to grab the latest build off of `master`.

**Comment by botorabi** [comment]
Great, now everything works fine. I have also managed to introduce a move-checker -- using the same mechanism -- for the polygon and ellipse which prevents the entire geometry moving out of the canvas while dragging.

I am looking forward to further explore the possibilities with jCanvas in my app.

Big Thanks
boto

**Comment by botorabi** [comment]
Hi @caleb531 

as I had promissed before, here is the web app, which was developed using jCanvas. It went online today.

  https://www.ifue-haartransplantation.de/hairassist/

Again, big thanks for the great work, I enjoy it much.

In the next project, the quadratic curves will be used to model eyebrows. I am excited to see what I can do with jCanvas.

I have already done some experiments and know of a feature which would help much: if you have several control points in a quadratic and you have guids (handles) for forming the curves then it is possible that curve discontinuities happen on nodes if you do not line up both control points in a line. Now it comes: it would be great to have an option for control points which care about the two control points around it and line them always up when one of them is moved. This option is something similar to "Cusp" and "Smooth" Nodes in Inkscape. Here is an explantion for Inkscape:

> A node can be made cusp (Shift+C), which means its two handles can move independently at any angle to each other; smooth (Shift+S), which means its handles are always on the same straight line (collinear); 

Cheers
boto

**Comment by caleb531** [comment]
@botorabi Hmmmm, so if I understand correctly, "Smooth" is when the line that connects each pair of control points is parallel with the line that connects each pair of start/end points? (like so):

![bezier-normal](https://cloud.githubusercontent.com/assets/872474/26694418/2ab5bc5e-46bc-11e7-899f-db4c0a402e20.png)

![bezier-rotated](https://cloud.githubusercontent.com/assets/872474/26694419/2ce3c354-46bc-11e7-9b9a-267ae5d38d70.png)

**Comment by caleb531** [comment]
On second thought, what I just described is akin to just rotating the entire drawing, which is probably not what you mean. If you could please clarify or provide some sort of video/animation, oy would help me a great deal.

**Comment by botorabi** [comment]
Take a look on the image. The node N is smooth if C1, C2, and N lie in on a line, otherwise N is cusp (following the terminology of Inkscape). The mentioned option (when enabled) would automatically make all those points to lie on a line while one of C1 or C2 or N is moved. Thus you ensure that the node N is smooth.

![jcanvas-quadratic](https://cloud.githubusercontent.com/assets/11502867/26719591/6b57d48a-4785-11e7-91ac-e73b95c82a9d.png)

**Comment by caleb531** [comment]
@botorabi I see. Sorry to say, but that's a bit more sophisticated than what I'd be willing to implement for Handles at this time. It will surely add more complexity and is also likely to degrade performance.

**Comment by botorabi** [comment]
Hi @caleb531 No problem, i will start some experiments and let you know about the results.
