### ISSUE TITLE
Reset the aspect ratio to which the image is constrained when changing image

### ISSUE THREAD

**Issue by tompare** [caleb531/jcanvas#284]
Hello,
I have installed your plugin with which I have been working a few months and it makes canvas quite more easy to be used.
I have created a layer image with associated handles. The time I want to change the image, by clicking on an outside div, even when I update the sizes of the layer image, handles do not change its original size. Which means that if I try to resize the new image, it does not keep its original shape.

    h =  img.height;
    w =  img.width;
    y=$("#c"+v2).getLayer('dsny').y;
    x=$("#c"+v2).getLayer('dsny').x;

    $("#c"+v2).getLayer('dsny').source=img;
    $("#c"+v2).getLayer('dsny').height=h;
    $("#c"+v2).getLayer('dsny').width=w;

    $("#c"+v2).getLayer('el').x= x + (w / 2),
    $("#c"+v2).getLayer('el').y= y - (h / 2),
    $("#c"+v2).getLayer('ir').x= x - (w / 2),
    $("#c"+v2).getLayer('ir').y= y - (h / 2);
    
    $("#c"+v2).triggerLayerEvent('dsny','dragstart');
    $("#c"+v2).triggerLayerEvent('dsny','drag');
    $("#c"+v2).triggerLayerEvent('dsny','dragstop');
            
    $("#c"+v2).drawLayers();

I have also tried removing handles from that layer but I have not found the way to recreate it again.

    var handle;
    if ( $("#c"+v2).getLayer('dsny')._handles ) {

        for ( h = 0; h < $("#c"+v2).getLayer('dsny')._handles.length; h ++ ) {
            handle = $("#c"+v2).getLayer('dsny')._handles[h];
            $("#c"+v2).removeLayer( handle );
        }

        $("#c"+v2).getLayer('dsny')._handles.length = 0;

        $("#c"+v2).drawLayers();

        $("#c"+v2).getLayer('dsny')._handles={
            type: 'arc',
            fillStyle: '#fff',
            strokeStyle: '#f00',
            strokeWidth: 1,
            bringToFront: true,
            radius: 10
        };

        $("#c"+v2).drawLayers();
    }

Is there any way to reset the original sizes that handles takes into account when resizing or I need to delete and create again the layer image and all it's content?

Thank you,
Dani

**Comment by caleb531** [comment]
Yes, the aspect ratio can be reset by setting the layer's `aspectRatio` property to `null` (for this is what jCanvas Handles is setting internally).

```js
layer.aspectRatio = null;
```

**Comment by tompare** [comment]
Hello @caleb531,

Thank you for answering.
I have tried what you said and it does not work at all. If I add `$("#c"+v2).getLayer('dsny').aspectRatio=null;` before the `drawLayers`, the time I try to resize the new image, the layer image disappears.
I have also tried to set it to null when creating the layer which seems to work the same as it did before,  maintaining the aspectRatio from the first image.
To clarify it, this is the code I have for adding the image. It creates de layer image when entering the if and changes the src, width and height when not.

    if(!$('.dsny'+v2).hasClass('dsnsel')){
        var imgrot = new Image();
        imgrot.src = 'js/rotar.png';
        imgrot.onload = function () {
        var imgeli = new Image();
        imgeli.src = 'js/eliminar.png';
        imgeli.onload = function () {
        var img = new Image();
        img.src = 'imgs/disenyos/'+v1+'.png';
        img.onload = function () {
        h = widthh*img.height/600;
        w = widthh*img.width/600;
        $("#c"+v2).drawImage({
            name: 'dsny',
            type: 'image',
            layer: true,
            draggable: true,
            bringToFront: true,
            source: img,
            x: x,
            y: y,
            height: h,
            width: w,
            fromCenter: true,
            resizeFromCenter: false,
            constrainProportions: true,
            //aspectRatio: null,
            cursors: {
                mouseover: 'grab',
                mousedown: 'grabbing',
                mouseup: 'grab'
            },
            dragstart: function (pr) {
                dragg[v2] = false;
                $(this).getLayer('dsny').opacity = 0.6;
                oldy = pr.eventY;
                oldx = pr.eventX;
                oldye = $(this).getLayer('el').y;
                oldxe = $(this).getLayer('el').x;
                oldyr = $(this).getLayer('ir').y;
                oldxr = $(this).getLayer('ir').x;
            },
            drag: function (pr) {
                $(this).getLayer('ir').y = pr.eventY - oldy + oldyr;
                $(this).getLayer('ir').x = pr.eventX - oldx + oldxr;
                $(this).getLayer('el').y = pr.eventY - oldy + oldye;
                $(this).getLayer('el').x = pr.eventX - oldx + oldxe;
                moving(v2,$("#c"+v2).getLayer('dsny'));
                colorear(v2);
            },
            dragstop: function (pr) {
                dragg[v2] = true;
                $(this).getLayer('dsny').opacity = 1;
            },
            handlePlacement: 'sides',
            handle: {
                type: 'arc',
                fillStyle: '#fff',
                strokeStyle: '#f00',
                strokeWidth: 1,
                bringToFront: true,
                radius: 10
            },
            handlestart: function () {
                dragg[v2] = false;
            },
            handlemove: function () {
                $(this).getLayer('ir').y = $(this).getLayer('dsny').y - ($(this).getLayer('dsny').height / 2);
                $(this).getLayer('ir').x = $(this).getLayer('dsny').x - ($(this).getLayer('dsny').width / 2);
                $(this).getLayer('el').y = $(this).getLayer('dsny').y - ($(this).getLayer('dsny').height / 2);
                $(this).getLayer('el').x = $(this).getLayer('dsny').x + ($(this).getLayer('dsny').width / 2);
                moving(v2,$("#c"+v2).getLayer('dsny'));
                colorear(v2);
            },
            handlestop: function(){
                dragg[v2] = true;
            }
        }).drawImage({
            name: 'ir',
            layer: true,
            draggable: true,
            bringToFront: true,
            x: x - (w / 2),
            y: y - (h / 2),
            width: 20,
            height: 20,
            type: 'image',
            source: 'js/rotar.png',
            fromCenter: true,
            cursors: {
                mouseover: 'col-resize',
                mousedown: 'col-resize',
                mouseup: 'col-resize'
            },
            dragstart: function (pr) {
                dragg[v2] = false;
                oldy = $(this).getLayer('ir').y;
                oldx = $(this).getLayer('ir').x;
                $(this).getLayer('ir').y = oldy;
                $(this).getLayer('ir').x = oldx;
                $(this).getLayer('dsny').rotate = pr.eventX - oldx;
            },
            drag: function (pr) {
                $(this).getLayer('ir').y = oldy;
                $(this).getLayer('ir').x = oldx;
                $(this).getLayer('dsny').rotate = pr.eventX - oldx;
            },
            dragstop: function (pr) {
                dragg[v2] = true;
            }
        }).drawImage({
            name: 'el',
            layer: true,
            bringToFront: true,
            x: x + (w / 2),
            y: y - (h / 2),
            width: 20,
            height: 20,
            type: 'image',
            source: 'js/eliminar.png',
            fromCenter: true,
            mousedown: function (){
                dragg[v2] = false;
                quitaDiseno(v2);
            },
            mouseup: function (){
                dragg[v2] = true;
            },
            touchstart: function (){
                dragg[v2] = false;
                quitaDiseno(v2);
                dragg[v2] = true;
            },
            cursors: {
                mouseover: 'pointer',
                mousedown: 'pointer',
                mouseup: 'pointer'
            }
        }).drawLayers();
        
        colorear(v2);
        calcular();
        
        };};};
    }else{
        console.log('hello moto');
        var img = new Image();
        img.src = 'imgs/disenyos/'+v1+'.png';
        img.onload = function () {
            console.log(img.height);
            elh = img.height;
            elw = img.width;
            h = widthh*elh/600;
            w = widthh*elw/600;
            y=$("#c"+v2).getLayer('dsny').y;
            x=$("#c"+v2).getLayer('dsny').x;

            $("#c"+v2).getLayer('dsny').source=img;
            $("#c"+v2).getLayer('dsny').height=h;
            $("#c"+v2).getLayer('dsny').width=w;
            
            $("#c"+v2).getLayer('el').x= x + (w / 2),
            $("#c"+v2).getLayer('el').y= y - (h / 2),
            $("#c"+v2).getLayer('ir').x= x - (w / 2),
            $("#c"+v2).getLayer('ir').y= y - (h / 2);
    
            $("#c"+v2).triggerLayerEvent('dsny','dragstart');
            $("#c"+v2).triggerLayerEvent('dsny','drag');
            $("#c"+v2).triggerLayerEvent('dsny','dragstop');
            
            //$("#c"+v2).getLayer('dsny').aspectRatio=null;
            $("#c"+v2).drawLayers();
            
            moving(v2,$("#c"+v2).getLayer('dsny'));
            colorear(v2);
            calcular();
        };
    }

Thank you again for your time,
Dani

**Comment by caleb531** [comment]
Oh, my apologies. I just realized that the aspectRatio only gets set on instantiation of the handles, meaning if you set it to `null` as I originally suggested, it will never get set to the proper ratio. Therefore, try setting the aspect ratio to the image's new width divided by its new height.

**Comment by tompare** [comment]
Yes, this is what ended up doing.
I edited my answer.

It worked, thank you for helping me
I did not understand which the aspectRatio function was at all.

Thank you again,
Dani
