### ISSUE TITLE
Small hang when start dragging on mobile devices

### ISSUE THREAD

**Issue by botorabi** [caleb531/jcanvas#285]
Hi @caleb531 
I have observed something which is a bit tedious on mobile devices. When dragging a layer -- say an ellipse or polygon -- with handles on a mobile device, the first a few millimeters of dragging the layer seems often to hang abit, then the layer can be moved smoothly without any hangs. It is only the initial phase of dragging, which often -- but not always -- seem to hang a bit. I have tested also the handle plugin examples, the same problem occured also there.

Before I dive into the sources, I wanted to ask you. Do you already know anything about this issue? Any measures or workarounds to avoid that?

It is some kind of importat for my app, because the dragging mechanism is used to place some geometry for marking some location -- such as a coin -- on an image. A precise geometry placing and resizing for such marking feature is crucial to the app.

Any help is highly welcome :-)

Cheers
boto

**Comment by caleb531** [comment]
Hi, @botorabi. Does the issue occur for draggable layers *without* handles?

Caleb

**Comment by botorabi** [comment]
After testing more, I can see that it also happens to layers without handles, e.g. an image layer. The image has a small size of 512 x 512.

More info about two devices which show this effect: Samsung Galaxy S4 and Nexus 6 running Chrome.

On an iPhone6 Plus with Safari the effect is almost negligible.

boto

**Comment by caleb531** [comment]
Frankly, I'm not sure what can be done about that initial lag at this point. jCanvas performs a lot of work behind the scenes to make dragging work properly. Moreover, considering that this is effectively a performance issue which can only be reproduced on some mobile devices, it would be rather difficult to debug.

To be sure, I tested [this first docs example of draggable layers](https://projects.calebevans.me/jcanvas/docs/draggableLayers/#basic-usage) on my phone (iPhone 6S Safari). I do notice some initial lag when I drag normally with my finger, but the lag quickly dissipates. For what it's worth, if this lag in itself is unsatisfactory, the initial lag is practically imperceptible if I drag slowly with my finger, and so I can still achieve a precise position.

**Comment by botorabi** [comment]
Hi @caleb531 

thank you for your inventigation. I would close this issue then and if I find somehting to fix this then I let you know.
