### ISSUE TITLE
Unable to drag a background image

### ISSUE THREAD

**Issue by stccorp** [caleb531/jcanvas#288]
Hello,

I am using jcanvas to load a background image and then draw shapes on top. BUT
let say my image is 1024 x 768  But I dont want to make my canvas that big. Let say I only want 320 x 240

I have 2 choices 
1. resize the picture
2. maintain the picture size  and allow to drag the picture inside the canvas

I want to try #2. I made the layers dragable but nothing happen.  I just see a croped version of my image
but the background does not move.

Any Ideas?

```js
$('#myCanvas').drawImage({
        source: 'http://localhost/myimage.png',
        fromCenter:false,
        x: 0, y: 0,
        layer: true,
        draggable: true,
        load: drawShapes
    });
```

drawShapes just draws rectangles from an array like
arr[] new Seat(x,y,width,height);
```

**Comment by caleb531** [comment]
If I understand your intent correctly, you actually have a third choice: use the cropping feature for jCanvas images ([docs here](https://projects.calebevans.me/jcanvas/docs/images/#cropping)). I recommend this option for your case. Please try it and let me know how it works for you.

**Comment by caleb531** [comment]
@stccorp any update on this issue? Have you tried what I suggested above?
