### ISSUE TITLE
Is it possible to click on a text?

### ISSUE THREAD

**Issue by YeltsinReyes** [caleb531/jcanvas#290]
I'm trying to do this and it doesn't work!

```js
$('canvas').drawText({
  fillStyle: '#9cf',
  strokeStyle: '#25a',
  strokeWidth: 2,
  x: 150, y: 400,
  fontSize: 48,
  fontFamily: 'Verdana, sans-serif',
  text: 'Hello',
  layer: true,
  click: function(layer) {
    alert('click');
  }
});
```

**Comment by caleb531** [comment]
You're absolutely right. Even the drawText examples in the documentation are terribly screwy.

I will definitely look into this right away—please bear with me.

**Comment by caleb531** [comment]
@YeltsinReyes found the problem, and just pushed a fix. Please grab the latest `jcanvas.js` or `jcanvas.min.js` off of the master branch:

https://github.com/caleb531/jcanvas/blob/master/dist/jcanvas.js
https://github.com/caleb531/jcanvas/blob/master/dist/min/jcanvas.min.js

**Comment by YeltsinReyes** [comment]
@caleb531 Thank you very much for your quick solution, now works very well!
