### ISSUE TITLE
Rendering Video

### ISSUE THREAD

**Issue by adityakumar9111** [caleb531/jcanvas#291]
I want rendering video inside canvas by jcanvas. Any idea??

**Comment by caleb531** [comment]
@adityakumar9111 jCanvas currently has no native method for it, but it's easily implemented via the native canvas API (http://html5doctor.com/video-canvas-magic/), which is easy to turn into a custom jCanvas method via the Plugin API (https://projects.calebevans.me/jcanvas/docs/extending/).
