### ISSUE TITLE
Touch problem in mobile devices

### ISSUE THREAD

**Issue by adrianhergim** [caleb531/jcanvas#293]
Hi, 

First of all congratulations for your plugin, i find it very useful for my current project. 

I am having a little problem with the plugin in mobile devices. On the PC I have the canvas and I am using the layer system to do some animations when I click some figures, handling it with the mouse down, mouse up events, and everything works correctly. However, on the mobile phone, it seems that the touch is disabled on the canvas, I can’t even zoom or drag to move around the website if I touch on the canvas zone.

Do you have any idea why this might happen?.

I am using jqueryv3.1.1 and jCanvas v20.1.1. I have the canvas inside a boostrap grid. Without using your plugin the touch seems to work again on the canvas.

Thanks in advance.

**Comment by caleb531** [comment]
Hi, @adrianhergim. I'd be happy to help, but I need to more from you:

1. What web browser /are you using on your PC?
2. What web browser / OS are you using on your phone?
3. Can you please provide the code you are using?

Thanks,
Caleb

**Comment by adrianhergim** [comment]
Sure:
1. On the PC it works with Firefox and Chorme
2. I tried two diferent devices one with android 6.0.1 and the other one with andorid 4.2.2, I used Firefox/Chrome in both of them and neither works. However, the exemple code for Touch Events from the jcanvas documentation works correctly on both.
3. I don't know if all my code well be helpful, but here is the part I am having problems with:

`
     $('canvas').drawRect({
	layer: true,
	name: 'station_5',
	fillStyle: '#2A5ABB',
	strokeStyle: '#000',
	x: 1*square_size, y: 4*square_size,
	width: square_size,
	height: square_size,
	fromCenter: false,
	 mousedown: function(layer) {
    // Animate layer when moused on or touched
              $(this).animateLayer('station_5', {
              fillStyle: '#EE8115',
               scale: 1.5
               }, 250);
        },
       mouseup: function(layer) {
    // Animate layer when moused off or touch ends
             $(this).animateLayer('station_5', {
             fillStyle: '#36c',
             scale: 1
             }, 250);
             $('#formulario1 #end_station').val(5);
            }
       });
`

**Comment by caleb531** [comment]
Are you setting a CSS `width` and/or `height` on the canvas? Because that is a common source of problems. The HTML5 can only be resized via its `width` and `height` HTML attributes.

Caleb

**Comment by adrianhergim** [comment]
Yeah I was using CSS becouse I wanted the canvas to be responsive, always having the same number of pixels but not occuping the same space on the screen (for mobile/PC version), but It seems that mess up the coordinate system of the canvas. If I make its size fixed it works perfectly on the mobile, but I lose the responsivness. I will try a different approach.

Thanks for everything!

Adrian

**Comment by caleb531** [comment]
As I said, you'll need to modify the canvas's `width` and `height` *attributes*. Try something like this:

```js
$(window).on('resize', function () {
  $('canvas').prop({
    width: window.innerWidth,
    height: window.innerHeight
  });
});
```

**Comment by adrianhergim** [comment]
That resizes to the window size rather than the column size. At the end I went with this and it work perfectly:

```javascript
  var container = document.getElementById('canvas_div');
  var cs = getComputedStyle(container);

  var width = parseInt(cs.getPropertyValue('width'), 10);
  $('#canvas').attr("width", width-40);
  $('#canvas').attr("height", (width-40)/2);
  
  scale_factor=(width-40)/800;
  
  $('canvas').scaleCanvas({
  layer: true,
	name: 'scale1',
	scale: scale_factor
	});
```
Thanks!!
