### ISSUE TITLE
setLayers and Image Color Change

### ISSUE THREAD

**Issue by ubergeekzone** [caleb531/jcanvas#294]
I am trying to change the color of an image

````
canvas.setLayers('layerName', {
   soruce: lay.soruce,
   rotate:10,
}, function(layer) {
   $(this).setPixels({
      x: layer.x, y: layer.y,
      width: layer.width, height: layer.height,
      each: function(px) {
         px.r = 255 - px.r;
         px.g = 255 - px.g;
         px.b = 255 - px.b;
         }
    });
}).drawLayers();
````

does not seem by firing? I think I am doing this wrong.. any help would be appreciated.

**Comment by caleb531** [comment]
`lay.soruce` looks like a typo (should be `lay.source`). Is that from your original code, or do you think that was a mistake when writing that code snippet in this issue?

**Comment by ubergeekzone** [comment]
i've got it semi working with this code, but only part of the image is being inverted.. 

```
canvas.setLayer(form.name, {
                                type: "image",
                                soruce: lay.soruce,
								load:function(layer) {
                                    $(this).setPixels({
                                        x: lay.x, y: lay.y,
                                        width: lay.width, height: lay.height,
                                        // loop through each pixel
                                        each: function(px) {
                                            px.r = 255 - px.r;
                                            px.g = 255 - px.g;
                                            px.b = 255 - px.b;
                                        }
                                    });
                                }
                            }).drawLayers();
```

**Comment by ubergeekzone** [comment]
Might help if I explain what I am trying to do. 

I have a color picker and I am setting the color, I need to change the color of the image based upon my color picker value. This has to be done after images are loaded on start.

**Comment by ubergeekzone** [comment]
Seems to be a width and height issue in the setPixels, I am setting the width and height to the image I want to change the color on. What am I doing wrong? :face_with_head_bandage:

**Comment by caleb531** [comment]
At second glance, it looks like you are also trying to rotating the image (based on your original code).

`setPixels()` in itself is not layer-aware; it doesn't invert the pixels for a particular layer, but rather whatever pixels are within the rectangular region you defined when you call the method (`x`, `y`, `width`, `height`). Furthermore, `setPixels()` can't be rotated with the `rotate` property. To rotate the region of inverted pixels, you need to use the `rotateCanvas()` method ([docs here](https://projects.calebevans.me/jcanvas/docs/rotateCanvas/)).

I suspect something like this should work:

```js
var lay = listLayer(form.name);
canvas.setLayer(form.name, {
    type: "image",
    source: lay.source,
    load:function(layer) {
        $(this)
        .rotateCanvas({
            rotate: 10
            x: lay.x, y: lay.y
        })
        .setPixels({
            x: lay.x, y: lay.y,
            width: lay.width, height: lay.height,
            // loop through each pixel
            each: function(px) {
                px.r = 255 - px.r;
                px.g = 255 - px.g;
                px.b = 255 - px.b;
            }
        })
        .restoreCanvas();
    }
}).drawLayers();
```

**Comment by ubergeekzone** [comment]
hmm, ok.. still only inverting half of my image..

**Comment by caleb531** [comment]
@ubergeekzone Could you please provide a screenshot of what you're seeing?

**Comment by ubergeekzone** [comment]
current code.
<img width="765" alt="screen shot 2017-08-08 at 6 22 03 pm" src="https://user-images.githubusercontent.com/6809045/29097196-8c4511a6-7c66-11e7-931e-70b5d13e8ff7.png">

```
var lay = listLayer(form.name);


						if(valid_hex == true) {
                            canvas.setLayer(form.name, {
                                type: "image",
                                soruce: lay.soruce,
								load:function(layer) {
                                    $(this).setPixels({
                                        x: lay.x, y: lay.y,
                                        width: canvas.attr('width'), height: canvas.attr('height'),
                                        // loop through each pixel
                                        each: function(px) {
                                            px.r = 255 - px.r;
                                            px.g = 255 - px.g;
                                            px.b = 255 - px.b;
                                        }
                                    });
                                }
                            }).drawLayers();
						}
```

**Comment by caleb531** [comment]
I realized just now that `setPixels` *does* support `rotate`, so forget my earlier comment.

After further testing, I have discovered (using my own example) that `setPixels` doesn't appear to be positioning correctly. I am investigating the issue now, and will get back to you with further details of what I find.

**Comment by ubergeekzone** [comment]
Awesome, At least the issue is now known. Do you know how I can replace an image source?

**Comment by caleb531** [comment]
You can replace an image source just as you are already doing—using `setLayer` and the `source` property:

```js
canvas.setLayer({
  source: myNewSource,
  ...
});
```

**Comment by ubergeekzone** [comment]
not working for me...

**Comment by caleb531** [comment]
Just to confirm: you will need to call `drawLayers()` after `setLayer()` in order for the source change to take effect visually. Did you do that?

**Comment by ubergeekzone** [comment]
ok, source issue fixed.

**Comment by caleb531** [comment]
Alright, I just pushed https://github.com/caleb531/jcanvas/commit/b22706ed748a9641bf174f6f54a50587ae4bf930 with a fix (currently, only `jcanvas.js` is updated). Turns out `setPixels()` was not respecting a canvas scaled by `detectPixelRatio()`, so if you were viewing the canvas on a high-PPI device (like retina display iPhones or Macs), the manipulated pixels would be mispositioned.

@ubergeekzone, please try it out and let me know how it works for you.

**Comment by ubergeekzone** [comment]
Beautiful, Works like a charm!!! Thank you!! One last thing.

Could you explain how this works to me. What if I wanted to replace the color of an image rather than tint it?

```
 each: function(px) {
 px.r = 255 - px.r;
px.g = 255 - px.g;
px.b = 255 - px.b;
}
```

**Comment by caleb531** [comment]
The callback you pass to the `each()` function receives a `px` object as its only argument. This `px` object contains `r`, `g`, and `b` properties (respectively red, green, and blue). Each value ranges from 0 (e.g. no red) to 255 (e.g. bright red).

The example I gave above (and in the docs) is actually inverting the colors, not merely tinting them. I assume you want to replace colors *similar to* the color you've chosen, but not exactly (since your field contains several shades of green, or even the same shade but with minor variations).

I'm not an expert on manipulating RGB colors, but I would check out:
https://stackoverflow.com/questions/6615002/given-an-rgb-value-how-do-i-create-a-tint-or-shade

I hope that helps, at least. :)

**Comment by ubergeekzone** [comment]
If I wanted to change the colors for just the 2 red borders that are its own layer, How would I go about doing this?

<img width="330" alt="screen shot 2017-08-08 at 8 05 20 pm" src="https://user-images.githubusercontent.com/6809045/29099707-036a84ba-7c75-11e7-9833-9ad6e56e6279.png">

**Comment by caleb531** [comment]
I might go about it by checking if `px.r` is greater than `px.g` and `px.b` (indicating that this particular pixel has more red in it than green or blue).

```js
if (px.r > px.g && px.r > px.b) {
  // this pixel should be red, more or less
}
```

**Comment by ubergeekzone** [comment]
I am lost... This would not be done using a mask?

**Comment by ubergeekzone** [comment]
got it! thanks!

**Comment by caleb531** [comment]
@ubergeekzone Great! I think I can close this issue, then—but let me know if there's anything else you need. :)
