### ISSUE TITLE
Image Masking Not Working as Should

### ISSUE THREAD

**Issue by ubergeekzone** [caleb531/jcanvas#295]
I do not think the image masking is working as it should. 

I have 3 images.  I am trying to replace the wood border with the gray image. 

```
var canvas = $("canvas");

    canvas.drawImage({
        name:"board",
        source: "2x3-P3N-100-78G_0d794e6a-d4f5-4fe3-9631-af9bba6d5c15_1024x1024.jpg",
        fromCenter: true,
        index:0,
        x: (canvas.attr("width")) / 2, y: (canvas.attr("height")) / 2,
        scale: 0.5
    }).

    drawImage({
        name:"mask",
        source: "mask.png",
        fromCenter: true,
        mask: true,
        x: (canvas.attr("width")) / 2, y: (canvas.attr("height")) / 2,
        scale: 0.5
    }).
    drawImage({
        name:"gray",
        source: "gray.jpeg",
        fromCenter: true,
        x: (canvas.attr("width")) / 2, y: (canvas.attr("height")) / 2,
    });
```

![2x3-p3n-100-78g_0d794e6a-d4f5-4fe3-9631-af9bba6d5c15_1024x1024](https://user-images.githubusercontent.com/6809045/29280015-a63e1d8e-80e7-11e7-9523-ff25066ba807.jpg)
![gray](https://user-images.githubusercontent.com/6809045/29280014-a637175a-80e7-11e7-996d-2b93b7bda09e.jpeg)
![mask](https://user-images.githubusercontent.com/6809045/29280017-a6a01a16-80e7-11e7-89fc-4135e40bf2ef.png)

**Comment by caleb531** [comment]
@ubergeekzone Sorry to say, using an image as a mask in jCanvas doesn't work the way you expect. An image mask in jCanvas would only cause the masked shapes to be clipped at the boundary of the image.

``js
$('canvas')
.addLayer({
  type: 'image',
  mask: true,
  source: 'images/fish.jpg',
  x: 150, y: 150
})
.addLayer({
  type: 'arc',
  fillStyle: '#c33',
  mask: true,
  x: 80, y: 200,
  radius: 50
})
.addLayer({
  type: 'restore'
})
.drawLayers();
```

<img width="725" alt="screen shot 2017-08-16 at 8 20 29 pm" src="https://user-images.githubusercontent.com/872474/29394618-6c7cd4c0-82c0-11e7-8985-ca140a1f9ebd.png">
