### ISSUE TITLE
Is there an API for viewing the pixel colors specified in the page? I can not find it

### ISSUE THREAD

**Issue by Klay-Clam** [caleb531/jcanvas#296]
Hi,buddy~I'm using your plugin to make a project，now，I need a function to get the pixel colors specified in the web page.What can I do by this plugin?
Is there an API for viewing the pixel colors specified in the page? I can not find it！

**Comment by caleb531** [comment]
If you wish to get the pixel data as a means of manipulating the pixel colors, you can use the jCanvas `setPixels()` method ([docs here](https://projects.calebevans.me/jcanvas/docs/pixelManipulation/)). If you want to simply get the pixel data without manipulating pixels, you might as well just use the native canvas `getImageData()` method ([tutorial here](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas)).

**Comment by Klay-Clam** [comment]
Got it .
