### ISSUE TITLE
Draggable images masked by their transparent pixels

### ISSUE THREAD

**Issue by Hyphen-ated** [caleb531/jcanvas#297]
jCanvas lets me drag images around on the canvas. The clickable area for each image is a rectangle. 

When I have two images stacked on top of each other, and I click on a location where the top image is fully transparent and the bottom image is visible, right now this starts dragging the top image. In my application, I want this to start dragging the bottom image instead. (the highest image where the clicked pixel is not fully transparent)

Is jCanvas able to do this?

Manually creating a mask out of primitive shapes doesn't help, because I'm dealing with arbitrary images.

**Comment by caleb531** [comment]
jCanvas does not support any kind of pixel detection on images. If you want to do something like this, you would need to use a native canvas method like [getImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData), and if you encounter a transparent pixel, propagate the layer event to the lower layer.

You can get the lower image layer by checking the `layer.intersects` property, which determines if the layer is currently intersecting with the cursor. You could do this by iterating through all layers *after* the layer you're currently dragging:

```js
var layers = $myCanvas.getLayers();
var layersAfterCurrent = layers.slice(currentImageLayer.index + 1);
// Now, loop over layersAfterCurrent and do stuff
// ...
```

The first layer whose `intersects` property is `true` will be the layer you want to propagate the events to.

**Comment by Hyphen-ated** [comment]
Thanks for the reply!

I found that the library "easelJS" has the behavior I want by default, and it seems somewhat easier to switch to that.
