### ISSUE TITLE
Pixel Manipulation Question

### ISSUE THREAD

**Issue by ubergeekzone** [caleb531/jcanvas#298]
You helped me a few weeks ago with an issue of changing a color of 2 images. I am having a similar issue again. 

The football field image is using this code to change the area in blue and the red border. 

```
if (px.r > px.g && px.r > px.b ) {
   px.r = rgb.red;
   px.g = rgb.green;
   px.b = rgb.blue;
}
```
![background-field](https://user-images.githubusercontent.com/6809045/30068980-6b7c43d6-922d-11e7-99b0-79f47f3761a3.png)

**Layers of Football Field** 

![background](https://user-images.githubusercontent.com/6809045/30069387-a0d6cc26-922e-11e7-86c2-6a8d9a204118.png)

![top-bottom](https://user-images.githubusercontent.com/6809045/30069396-a6de4ab8-922e-11e7-8a66-e011961ace33.png)

**Now I have this image, which is a transparent image with blue.** 

![primary-color](https://user-images.githubusercontent.com/6809045/30069032-95c056aa-922d-11e7-88cb-22957943187c.png)

Each image is on its own layer, These 2 images are not used together they are separate on their own product. My code is setup in a function that is called on the fly see below. 

```
canvas.setLayer(layerName, {
   type: "image",
   load: function(layer) {
      $(this).setPixels({
         x: lay.x,
         y: lay.y,
         width: lay.width,
         height: lay.height,
         each: function(px) {
            if (px.r > px.g && px.r > px.b ) {
               px.r = rgb.red;
               px.g = rgb.green;
               px.b = rgb.blue;
            }
         }
      });
   }
}).drawLayers();
```
I think my question is how do determine in my code how to support color changing of these images.

**Comment by caleb531** [comment]
Where are `rgb.red`, `rgb.green`, and `rgb.blue` defined?

**Comment by ubergeekzone** [comment]
```
function getRGB(str) {
   var match = str.match(/rgba?\((\d{1,3}), ?(\d{1,3}), ?(\d{1,3})\)?(?:, ?(\d(?:\.\d?))\))?/);
   return match ? {
      red: match[1],
      green: match[2],
      blue: match[3]
   } : {};
}
var rgb = getRGB(color);
```

**Comment by ubergeekzone** [comment]
Caleb,
  Any update on this issue?

**Comment by caleb531** [comment]
My apologies—I suppose I don't understand your initial question. Could you please clarify what you expect to happen, and what's happening instead?

**Comment by ubergeekzone** [comment]
@caleb531 Is there a way I could just ignore transparent pixels?

**Comment by caleb531** [comment]
Yep—there's actually a `px.a` property on the `px` object which represents the alpha value. A value of `0` means completely transparent; a value of `1` means fully opaque. So you can check `px.a === 0` to check for fully transparent pixels.

**Comment by ubergeekzone** [comment]
@caleb531 that did not work as planned.

```
if(px.a === 0) {
} else {
   px.r = rgb.red;
   px.g = rgb.green;
   px.b = rgb.blue;
}
```

It still adds the color to the transparent area.

**Comment by caleb531** [comment]
@ubergeekzone that only works for pixels that are completely transparent? Are the pixels you're working with completely transparent, or is there some slight opacity/color?

**Comment by ubergeekzone** [comment]
![lines](https://user-images.githubusercontent.com/6809045/30551301-11b8c596-9c68-11e7-8df6-dc2bc374f4da.png)

@caleb531 see image above.

**Comment by ubergeekzone** [comment]
@caleb531 the issue is this

I have 2 color swatches where I can pick colors to change the images, each image is on its own layer.  but if I pick a certain color it will not update the other layer when a new color is picked. 

Not quite sure what I am doing wrong.

**Comment by caleb531** [comment]
@ubergeekzone Keep in mind that `setPixels()` is not layer-specific. If you have, say, a white rectangle drawn below your transparent-pixel image on the canvas, then `setPixels()` will see those white pixels instead of transparent ones.

I don't know if that helps, but it's worth noting.

**Comment by ubergeekzone** [comment]
@caleb531 hmm, good to know. not quite my issue. Go here https://shop.prolinetailgating.com/apps/board-app and click on High School Sports pick either the 2nd or 3rd board and play between the Primary Color and 2ndary Color swatches. You will see the exact issue and maybe have some insight on what I could do to fix this.

**Comment by ubergeekzone** [comment]
@caleb531 any luck?

**Comment by caleb531** [comment]
@ubergeekzone Sorry, but I won't be able to continue investigating this issue until tonight (i.e. in about 10 hours). I work full time now. ;)

**Comment by ubergeekzone** [comment]
@caleb531 cool, no problem. I understand. Thanks for taking the time to help. I will keep an eye out for feedback.

**Comment by ubergeekzone** [comment]
@caleb531 any luck?

**Comment by caleb531** [comment]
@ubergeekzone Gah, so sorry. Something came up and I totally forgot about this. Let me try to help you now. Thanks for giving me a nudge.

After, further investigation *facepalm*. If you want to set transparent pixels, you need to set `px.a` to `255` otherwise the pixel will still be transparent regardless of other color values.

```js
$canvas.setPixels({
    x: layer.x,
    y: layer.y,
    width: layer.width,
    height: layer.height,
    each: function(px) {
        if (px.a === 0) {
            px.r = 0;
            px.g = 0;
            px.b = 255;
            px.a = 255; // this line is the key
        }
    }
});
```

**Comment by ubergeekzone** [comment]
@caleb531 I will try this tomorrow and update you. ty

**Comment by ubergeekzone** [comment]
@caleb531 still did not solve my issue.

**Comment by caleb531** [comment]
@ubergeekzone It should definitely work, but to be fair, I should have provided the example I wrote to confirm this. Please download the ZIP below, try it out, and see what you can learn from it. I'm using the exact image you provided me.

[jcanvas-setpixels.zip](https://github.com/caleb531/jcanvas/files/1339182/jcanvas-setpixels.zip)
