### ISSUE TITLE
Layer index not restored after drag with bringToFront?

### ISSUE THREAD

**Issue by rhewitt** [caleb531/jcanvas#299]
Hi and thank you for this awesome plugin! I'm just now trying it out so apologies if I've missed something, but I ran into a quirk that, for me at least, was a bug. I created a dragGroup with two overlapping rectangles and set bringToFront=true on both. 

I want the cursor to be different on each rectangle and wanted my second rectangle's cursor to show in the overlap. That was the case at load, but after dragging, I found that the first rectangle's cursor had taken over the overlap area -- even when not dragging. That's the quirk, or (for me) bug.

I tried saving and resetting layer.index at dragstop, but that did not fix the problem. Looking at the code, I see that the layers array is modifed at the start of a drag operation when bringToFront==true:
```
if (layer.bringToFront) {
     // Remove layer from its original position
     layers.splice(layer.index, 1);
     // Bring layer to front
     // push() returns the new array length
     layer.index = layers.push(layer);
}
```

But it appears the original ordering is not restored when the drag operation completes. Based on that, I added the following workaround to the first rectangle, which fixed my problem:
```
mouseover:  function(layer) {
  if( !('index' in layer.data) || layer.data.index === null ) {
    layer.data.index = layer.index;
  }
},
dragstop: function(layer) {
  theCanvas.moveLayer(layer.name, layer.data.index);
},
```

The workaround solves my problem but seems inelegant. What do you think of restoring layer ordering after dragging?

**Comment by caleb531** [comment]
Hey @rhewitt. Are you able to reproduce this unexpected behavior [in the jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/)?

**Comment by rhewitt** [comment]
Sorry for the delay. Yes, I can create it there. My use case is perhaps unusual, but here's a different example to illustrate what I'm talking about (code below, i don't see a way to save a sandbox experiment):
```
// Drag the yellow to make a blank face
$('canvas').drawArc({
  name: 'theFace',
  
  draggable: true,
  groups: ['smiley'],
  dragGroups: ['smiley'],
  bringToFront: true, 
  cursors: {
    mouseover: 'move',
  },
  mouseover:  function(layer) {
    if( !('index' in layer.data) || layer.data.index === null ) {
      layer.data.index = layer.index;
    }
  },
  dragstop: function(layer) {
    // this will not restore the face
    layer.index = layer.data.index;
    
    // comment out line above and
    // uncomment below to restore face
    //$('canvas').moveLayer(layer.name, layer.data.index);
  },

  fillStyle: 'gold',
  x: 100, y: 100,
  radius: 50
}).drawArc({
  draggable: true,
  groups: ['smiley'],
  dragGroups: ['smiley'],
  bringToFront: true, 
  
  fillStyle: 'black',
  x: 80, y: 90,
  radius: 5
}).drawArc({
  draggable: true,
  groups: ['smiley'],
  dragGroups: ['smiley'],
  bringToFront: true, 

  fillStyle: 'black',
  x: 120, y: 90,
  radius: 5
}).drawArc({
  draggable: true,
  groups: ['smiley'],
  dragGroups: ['smiley'],
  bringToFront: true, 

  strokeStyle: '#000',
  strokeWidth: 5,
  x: 100, y: 95,
  radius: 40,
  start: 140,
  end: 220,
});
```

**Comment by caleb531** [comment]
I see. Well, I can offer you a few ideas to solve this:

- Remove `bringToFront: true` completely and implement it yourself (the way you need it to work)
- Create a custom jCanvas type (see [the docs here](https://projects.calebevans.me/jcanvas/docs/extending/)) and make pass `bringToFront: true` to the whole drawing when you call it (as long as you're using `params.x` and `params.y` in the right places, that should work just fine
