### ISSUE TITLE
Assistance: Upgrade from v13.06 to latest

### ISSUE THREAD

**Issue by rivimey** [caleb531/jcanvas#300]
Hi, I want to update an app using jcanvas 13.06.26 to a more recent, pref. latest version. Are there any upgrade instructions or known 'gotchas' available?

If I just try using v20, there are errors, at least, in layer selection and ordering. The old code uses draw primitives using "group" to define layer membership (I think: not my code) and then getLayerGroup to retrieve the items thus tagged. In v13 this works; in v20 the getLG returns null. The result is that although the items are displayed the app cannot interact with them.

I did try with v15.2.7 (oldest on cloudflare) but this seems to exhibit the same behaviour as v20, so I'm thinking there was a change between v13 and v15.

**Comment by caleb531** [comment]
Hey, @rivimey. Off the top of my head, the `group` property is now deprecated in favor of the `groups` array. See https://projects.calebevans.me/jcanvas/docs/addLayers/#grouping-layers

Try `groups` and let me know what happens.
Caleb

**Comment by rivimey** [comment]
Thanks, Caleb, that does seem to help, though I would suggest "deprecated" should be "unsupported"! :)
Can you think of any other changes I might look out for?

**Comment by caleb531** [comment]
@rivimey Err, yes, unsupported. I initially deprecated it when I added `groups` (meaning I indicated that you shouldn't use `group` anymore), but I later removed it when enough time had passed.

I can't think of any other major changes off the top of my head. If your application is functioning properly, then I'd say don't worry about it. Therefore, I'm closing this issue, but please let me know if any new issues crop up.
