### ISSUE TITLE
Text doesn't draw subscripts

### ISSUE THREAD

**Issue by r0fls** [caleb531/jcanvas#301]
Is there a way to draw text with super/subscripts? Here's an example:

```javascript
$('canvas').drawText({
  fillStyle: '#9cf',
  strokeStyle: '#25a',
  strokeWidth: 2,
  x: 150, y: 100,
  fontSize: 18,
  fontFamily: 'Verdana, sans-serif',
  text: 'Hello' + 'world'.sup()
});
```

It doesn't render the HTML and results in `<sup>world</sup>`.

**Comment by caleb531** [comment]
Unfortunately, HTML5 provides no means of rendering HTML or formatting text as superscript/subscript. jCanvas does not provide this functionality either. It is something you need to implement yourself.

Fortunately, I'll try not to leave you hanging. See https://stackoverflow.com/questions/8326191/html5-canvas-subscript-and-superscript
