### ISSUE TITLE
How to draw border around image?

### ISSUE THREAD

**Issue by bhnbhushanTPL** [caleb531/jcanvas#302]
I want a border around my image, 

```
$('canvas').drawImage({
  source: 'images/fish.jpg',
  x: 150, y: 150,
  strokeStyle: '#009c56',
  strokeWidth: 1,
});
```

the above code does not create border around image? How to do it?

**Comment by caleb531** [comment]
@bhnbhushanTPL That is currently not possible. You must use two separate layers (image and rectangle):

```js
$('canvas')
.drawRect({
  x: 150, y: 150,
  width: 220, height: 138
  strokeStyle: '#009c56',
  strokeWidth: 1,
})
.drawImage({
  source: 'images/fish.jpg',
  x: 150, y: 150
});
```

If you don't want to duplicate the x/y/width/height of your image for the stroke rectangle, you can use the `load` callback to draw the image before drawing your stroke:


```js
$('canvas')
.drawImage({
  source: 'images/fish.jpg',
  x: 150, y: 150,
  load: function(image) {
    .drawRect({
      x: image.x, y: image.y,
      width: image.width, height: image.height
      strokeStyle: '#009c56',
      strokeWidth: 1
    })
  }
});
```

If you need your image to be draggable, check out [Drag Groups](https://projects.calebevans.me/jcanvas/docs/draggableLayers/#drag-groups).

Caleb

**Comment by bhnbhushanTPL** [comment]
@caleb531 Thank You.
