### ISSUE TITLE
Visibility not being triggered on layer

### ISSUE THREAD

**Issue by ViliusVaitiek** [caleb531/jcanvas#303]
I'm trying to set visibility of a certain layer to true/false , but the affect is not being shown visibly, however if we log the layer object the value `visible` does change. 

We have discovered that for some reason, if we trigger mouseout event the visibly state changes visibly.

I have reproduced the problem on jsfiddle

[https://jsfiddle.net/n05a5s75/](url)

**Comment by caleb531** [comment]
Per the docs, you need to redraw the canvas via `drawLayers()` after you set a layer property. See https://projects.calebevans.me/jcanvas/docs/manipulateLayers/#setting-layer-properties
