### ISSUE TITLE
Resize canvas with fromCenter = false and constrainProportions = true

### ISSUE THREAD

**Issue by anolek** [caleb531/jcanvas#306]
Hi,

First of all, thanks for jCanvas, it is very useful and easy to use,

While using the handles plugin,
I found an issue (i think) when you use jCanvas handle and you set "fromCenter" to false.

When resizing from the top left or the bottom left, well, it also "drag" the rectangle, here is a gif animated showing the issue : 

![2017-10-11_11-09-17](https://user-images.githubusercontent.com/1519946/31431678-a881b514-ae74-11e7-88e0-b767f7ce197e.gif)

And here is an exemple code where you can reproduce this issue on https://projects.calebevans.me/jcanvas/sandbox/

```
$('canvas').addLayer({
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  handle: {
    type: 'rectangle',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    width: 20, height: 20,
    cornerRadius: 3
  },
  constrainProportions: true,
  resizeFromCenter: false,
  fromCenter: false
})
.drawLayers();
```

If it's not a bug and it is the expected behavior, then sorry, i didn't find anything on the doc :( 

(Note: if it's a bug, i can try to send a PR, for now, as a workaround i just let fromCenter to true and calculate the coordinate manually)

Thanks !

**Comment by caleb531** [comment]
It's completely my fault. Handles does not currently support fromCenter: false, nor have I indicated the lack of support in the docs (though I'll make a note to do that soon). resizeFromCenter:false is as close as you'll get. Sorry I can't offer a better solution at this time.

Caleb

**Comment by anolek** [comment]
Thanks, and don't worry !

After looking at it, i found a simple solution, but i didn't test all the case (yet) to check if it will break something or not.

When i have done checking it, can i send a PR ? :)

**Comment by caleb531** [comment]
@anolek Of course! PRs are always welcome :)
