### ISSUE TITLE
Canvas flickers after attaching mouse events

### ISSUE THREAD

**Issue by jimd33463** [caleb531/jcanvas#311]
If you copy/paste the below into the 'sandbox' (the sandbox featured on the jcanvas website) the canvas flickers when you mouse over it.  My actual code is more complex, but you can see this issue even with this simple example.  The problem is resolved when I remove all the mouse event.  This happens only in recent versions of IE.

There is a note on the jCanvas website that may be related, but I don't understand how to implement it:

"Internet Explorer 9 has a bug which prevents images from drawing on the canvas if they have not loaded. To fix this, use an existing <img> DOM element as the value for the source property."

Could someone provide an example?  I need the image path to be variable.  Just to experiment, I hard-coded my image in the html with an image tag. Then changed the layer source to the following:  source: $('#backgroundImage').attr('src'),  The image shows up, but still has the flicker issue.

Steps to reproduce:
1. go to Sandbox:  https://projects.calebevans.me/jcanvas/sandbox/
2. copy/paste the code below into the Sandbox and run
3. reload the page, but immediately mouse over the canvas

$('canvas').addLayer({
  type: 'image',
  source: 'images/fish.jpg',
  x: 150, y: 150,
  mouseover: function(layer){
    console.log("mouseover");
  }
}).drawLayers();

**Comment by caleb531** [comment]
@jimd33463 You can try something like this:

```js
$('canvas').addLayer({
  type: 'image',
  source: $('#backgroundImage')[0]
  x: 150, y: 150,
  mouseover: function(layer){
    console.log("mouseover");
  }
}).drawLayers();

// later, as needed...
$('#backgroundImage').attr('src', myVariableImagePath);
$('canvas').drawLayers();
```
