### ISSUE TITLE
Cannot draw in very large canvas FireFox vs Chrome

### ISSUE THREAD

**Issue by awenger63** [caleb531/jcanvas#312]
Hi, I test your jcanvas and it was very interresting to use it, but in my case, I would use it in a very large canvas with zoom process.
I redraw (.drawLayers()) a simple arc (radius 10) on the rigth side of a big canvas (when zoom process increase width canvas, x value of the layer too, but HTML page just see one part of the canvas). In this case, the issue beginnig appear on the rigth side because value are bigger. When I increase width, and when is like 17000px, redraw arc after x~= 16300, the circle disapear ! It's look like jcanvas calculate some value are too big for redraw. 
`$('#canvas').addLayer({
        type: 'arc',
        name: 'name',
        fillStyle: 'yellow',
        strokeStyle: 'red',
        strokeWidth: 1,
        rounded: true,
        closed: true,
        x: (Here it increase at each step) , y: 100,
        radius: 5,
        draggable: true,
        drag: function (layer) {
$('#canvas').setLayer('name', {x: layer.x+1}).drawLayers();
         }
    }).drawLayers();`

To see issue, I implemented drag on the Layer and move it pixel by pixel, See here the result before it totaly disapear : 

![image](https://user-images.githubusercontent.com/16153617/33477362-b1144cbc-d685-11e7-9b2d-27705f9d0f9e.png)

Any idea to solve this issue ?
Thanks a lot

**Comment by caleb531** [comment]
@awenger63 So you are changing the width of the canvas when some user event occurs? How are you changing the width? I ask because changing the CSS width using `.css('width', myWidth)`or `.width(myWidth)` can be problematic. The correct way to set the width is `.attr('width', myWidth)`. 

If this is not what you are doing, then what do you mean by zooming the canvas? How are you zooming the canvas?

**Comment by awenger63** [comment]
Hi caleb531,  thanks you for your answer.
You're rigth, user action (zoom) change widht of the canvas. I do this change using `.attr('width', value);` to be sure that attribute's update not only css rendered.

**Comment by caleb531** [comment]
Oh, I think I see the problem now.

It's because you are increasing the arc's `x` by 1 within your `drag` callback. Why are you doing it this way? The `x` coordinate will surely increase exponentially, leading your arc to go offscreen because the x value becomes so large.

**Comment by awenger63** [comment]
Yes, I think it's something like that, but how I can increase x value. Is there a limit to draw something in a canvas ?

**Comment by caleb531** [comment]
@awenger63 Well, you should not be incrementing `layer.x` in your `drag` callback at all. If you just the layer to move with your mouse as you drag it, just omit the `drag` callback altogether, as `draggable: true` will already handle that just fine.

I don't know if you meant something more specific, but if so, please clarify.

**Comment by awenger63** [comment]
Hi Caleb531, 
Thanks you for your time.
It's not a draggable issue but a canvas and x size problem with ALL drawings. See code beelow to reproduce : 
`<div>
            <canvas id="canvas" width="16583" heigth="100" style="position: absolute; right: 0px;"></canvas>
            </div>`

`$('canvas').addLayer({
        type: 'arc',
        fillStyle: 'yellow',
        strokeStyle: 'red',
        strokeWidth: 1,
        rounded: true,
        closed: true,
        x: 16380, y:30,
        radius: 5}).drawLayers();`

You can test it with rectangle or other after 16380 pixels it impossible to draw anything !

To answer about specific use I need : I would like a user can identify a point with highly precision on a picture. For that, he can zoom it and drag a circle at the right position. But when picture zoom (canvas) are more than 16583px, I lost the circle and other draw, so it's impossible to the user to drag anything on this part after this position !
Hope this can help you to understand and find where the size became an issue.

**Comment by caleb531** [comment]
@awenger63 Thank you for explaining what you are trying to achieve, because I believe you are going about it the wrong way. I would not recommend having a canvas so large. It will eats tons of memory and become unwieldy because you have so many pixels to work with. The canvas should never be any larger than the user's viewport (window).

I say this with confidence because I have struggled with a similar design issue in the past for my [Grapher](https://projects.calebevans.me/grapher/) application. I am rendering mathematical equations on a graph which is virtually infinite in size, and I want the user to be able to examine the graph at any point in this infinite space.

When I first wrote the app, the canvas size was over 4000 pixels in width and height, with the canvas container clipped to hide most of it within a 480x480 space. However, having a canvas this large proved to be enormous and slow. I later redesigned the app to have the canvas be the size of the container (only 480x480), using canvas translate to pan around as the user desired.

Take a look at:
https://projects.calebevans.me/jcanvas/docs/translateCanvas/#layers
https://projects.calebevans.me/jcanvas/docs/scaleCanvas/#layers

Also remember that you can draw shapes on the canvas that at x=16000px, even if the canvas isn't that wide. They won't be visible initially, but if you translate the canvas with a method like translateCanvas(), you'll be able to see them.

I've written up an example below of how to pan the entire canvas by clicking and dragging. You can test it in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/). I've hidden some shapes to the left and to the right, which you can only see by clicking and dragging the canvas.

```js
var $canvas = $('canvas');

// Initial variables
var panX = 0
var panY = 0;
var startX;
var startY;
var isPanning;

// Create a layer for panning the canvas
$canvas.translateCanvas({
  layer: true,
  name: 'pan'
});

// Draw some random shapes
$canvas.drawPolygon({
  layer: true,
  fillStyle: '#36c',
  x: -100, y: 200,
  radius: 50,
  sides: 3
});
$canvas.drawArc({
  layer: true,
  fillStyle: '#6c3',
  x: 150, y: 140,
  radius: 50
});
$canvas.drawRect({
  layer: true,
  fillStyle: '#c33',
  x: 400, y: 100,
  width: 100, height: 100
});

// This is essential for restoring translate on each draw
$canvas.restoreCanvas({
  layer: true,
  name: 'restore'
});

// Add panning behavior to canvas
$canvas.on('mousedown', function (event) {
  startX = event.offsetX - panX;
  startY = event.offsetY - panY;
  isPanning = true;
});
$canvas.on('mousemove', function (event) {
  if (isPanning) {
    panX = event.offsetX - startX;
    panY = event.offsetY - startY;
    console.log(panX);
    console.log(panY);
    $canvas.setLayer('pan', {
      translateX: panX,
      translateY: panY
    });
    $canvas.drawLayers();
  }
});
$canvas.on('mouseup', function (event) {
  isPanning = false;
});

```

**Comment by awenger63** [comment]
@caleb531 Hi, Sorry for the delay, I'm working on the better way to use jcanvas in my case.
Thanks a lot for your great explanation, example and for your Sandbox ! 
I test your solution on it whith big x value and it could be a workarround of the issue. 
In my case I pluging your jcanvas solution on other component where the zoom is implemented. So, the diffulty is to translate when zoom is apply and which value I need to use for the translation, because it's an other component ...
During my test I found a new element : the issue exist on FireFox, 58.0 but not in Chrome 63.0.3239.132 ! It should be nice to have same result ... Do you have any idea of FireFox limit, bug or release ? Do you think is it possible to inform or log this type of issue on her side ?

**Comment by caleb531** [comment]
@awenger63 It's hard to say since you haven't provided your latest code. Regardless, I realized that it would probably be helpful if I extended my above translation example to support zooming.

How is the zoom in your application controlled? Via a button, or something like mouse interaction (e.g. click to zoom at this point)?

**Comment by awenger63** [comment]
@caleb531 Sorry for the delay, I work also on other issues in my project.
Original zoom version of the component had been realise with a slider. But I have
Implemented it in my application by the mouse event 'wheel'. I've got a var zoomLevel initialised on the load and I increase/decrease it depend of wheelDelta. Then I send this value to the component like a slider value ! After this change, I update all jcanvas layer to replace it on the right place depend of zoom action (see partial pseudocode algorithm here)

> var zoomLevel = 1;
    this.container.addEventListener('wheel', function (e) {
        var deltaY = 0;
        const zoomLimit = 100;
        const sizeMaxFireFox = 16200; //Issue Jcanvas
        e.preventDefault();
        if (e.deltaY) { // FireFox 17+ (IE9+, Chrome 31+?)
            deltaY = e.deltaY;
        } else if (e.wheelDelta) {
            deltaY = -e.wheelDelta;
        }
        // Update the bg size:
        if (deltaY < 0) {
            if (zoomLevel < zoomLimit) {
                parentCanvas.zoom(zoomLevel += 2);
                if (parentCanvas.drawer.wrapper.scrollWidth > sizeMaxFireFox && navigator.userAgent.indexOf("Firefox") !== -1) {
                    parentCanvas.zoom(zoomLevel -= 2);
                    return; // pas de repositionnement !
                }
            }
        } else {
            if (zoomLevel > 1) {
                $('#jcanvas').attr('width', (parentCanvas.width - zoomRatio));  <-- need reduce it before reduce parent canvas !
                parentCanvas.zoom(zoomLevel -= 2);
            }
        }
        updateJcanvasAndHisLayer();
    });

Is this what you need ?
If you need more, I would like time to realise a completed exemple for you.

On this solution, I would like to find how add also event for touchpad. I had making test 'touchmove' without success.
Thanks for your advice

**Comment by caleb531** [comment]
@awenger63 That helps a bit. I'll try to get you a comprehensive example this weekend, if you're able to wait until then.

**Comment by awenger63** [comment]
@caleb531 Yes, I can ;-)

**Comment by caleb531** [comment]
@awenger63 Just thought you'd like to know: I'm working on your comprehensive pan/zoom example right now. I'm building it as a comprehensive demo repository that can serve as a de-facto way to implement pan/zoom in jCanvas. I still have work to do, so hang tight.

**Comment by caleb531** [comment]
@awenger63 This is a more challenging problem than I anticipated, and I still don't have it quite right, but it works (more or less) if the scale increment is `*= 2` or `/= 2`.

Attached below is a ZIP of my latest work. It's an npm project, so you'll need to `npm install`.

I know it's not ideal, but when I figure this out definitively, I will let you know.

Caleb

[jcanvas-panzoom-demo.zip](https://github.com/caleb531/jcanvas/files/1734315/jcanvas-panzoom-demo.zip)

**Comment by awenger63** [comment]
@caleb531 Good work, zoom apply on mouse position for all component. This can be great for zooming jcanvas component. But in my case, I apply the zoom to the container and I replace jcanvas component to the rigth position (x,y) like your translation example without zoom it. To be honest the parent component is a wavesurfer.js where zoom is implemented. I will send you a better example by video or code, just wait, I will adapted something.

**Comment by caleb531** [comment]
@awenger63 Okay, I figured out the proper math, and it works perfectly as I desire. Please see my demo repository for the full example. Please refer to that instead:
https://github.com/caleb531/jcanvas-panzoom-demo

I'm not sure I understand what you mean. I know my example using click for zoom rather than mouse wheel, but the way this is written should make mouse wheel zoom easily integrate-able. Could you please clarify what is lacking here?

Thanks,
Caleb

**Comment by awenger63** [comment]
@caleb531 Sorry for my english, perhaps it's the reason of your misunderstand ? 
Remember : 

> To answer about specific use I need : I would like a user can identify a point with highly precision on a picture. For that, he can zoom it and drag a circle at the right position. But when picture zoom (canvas) are more than 16583px, I lost the circle and other draw, so it's impossible to the user to drag anything on this part after this position !

What i would like to say it is  : When I zoom the picture (waveform) , I need to draw or move a jcanvas layer on a right position without change is dimension only replace it on the rigth (x,y) position. But if zoom is bigger, canvas is bigger too, and drawing doesn't work after 16380px.
It's for that your first suggestion to translate the layer when picture zoom increase could be a solution. Just need to redefine the coordinated.
Your last suggestion in your example, is it to zoom the layer in same time of the canvas. this is very usefull for zooming all the jcanvas drawing and the same canvas and it could be interessant to have a new property on jcanvas layer to said if it's increase with the zoom value or only translate it with same visual dimension on screen.
Hope this clarify my purpose. I really want to send you a real example...

**Comment by awenger63** [comment]
@caleb531 To resume

- This issues #312 it's not a jcanvas issue but a browser and canvas element issue. It exist some restriction see for example [https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element](url)
 you can test with this code on different browser (Chrome OK, Firefox KO). So I think it could be close and I need to find a solution like you suggest to translate draw or draw in multiple canvas ...

`<canvas id="canvas" width="16583" heigth="100" style="position: absolute; right: 0px;"/>`

`<script type="text/javascript">`
    `var ctx = document.getElementById('canvas').getContext("2d");`
    `ctx.fillStyle = "blue";`
    `ctx.fillRect(16380,40,10,10);`
`</script>`

- Our discussion about zoom process for jcanvas element can be done in your panzoom repository [https://github.com/caleb531/jcanvas-panzoom-demo](url) to futur jcanvas release. I have suggest wheel implementation in your code by pull request. To be complete I think it will be great to add a new layer property or something like this to define if it include inside zooming process or not in same canvas. What do you think ?

Thanks for your work.
regards.

**Comment by caleb531** [comment]
Thanks, @awenger63. I saw your pull request and will be reviewing it today. I will be closing this issue now, given everything you have said.
