### ISSUE TITLE
the text disppearing when cursor move into canvas

### ISSUE THREAD

**Issue by qingxin2016** [caleb531/jcanvas#313]
when move cursor into canvas the text disappering in the canvas.
the code is below,how to fix id.
```js
$('canvas').drawRect({
                    layer: true,
                    draggable: true,
                    groups: ['shapes'],
                    dragGroups: ['shapes'],
                    fillStyle: statusColor,
                    x: x,
                    y: y,
                    width: 200, //494
                    height: 28, //70
                    data: {
                        name: title,
                        info: status
                    }
                })
                .drawText({
                    layer: true,
                    name: 'title',
                    fillStyle: '#fff',
                    strokeWidth: 1,
                    x: x,
                    y: y,
                    groups: ['shapes'],
                    dragGroups: ['shapes'],
                    fontSize: '12pt',
                    fontFamily: 'Helvetica',
                    text: title
                })
                .drawLayer();
```

**Comment by caleb531** [comment]
@qingxin2016 I am not seeing the text disappearing when I test your code in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/). What browser are you using?

This is the code I am testing with (same as yours, but with the missing variables defined):

```js
var statusColor = 'green';
var title = 'Title';
var status = 'Status';
var x = 150;
var y = 100;

$('canvas').drawRect({
  layer: true,
  draggable: true,
  groups: ['shapes'],
  dragGroups: ['shapes'],
  fillStyle: statusColor,
  x: x,
  y: y,
  width: 200, //494
  height: 28, //70
  data: {
    name: title,
    info: status
  }
})
.drawText({
  layer: true,
  name: 'title',
  fillStyle: '#fff',
  strokeWidth: 1,
  x: x,
  y: y,
  groups: ['shapes'],
  dragGroups: ['shapes'],
  fontSize: '12pt',
  fontFamily: 'Helvetica',
  text: title
})
.drawLayer();
```

**Comment by qingxin2016** [comment]
thank you,i have fixed it.Now i meet new issue.
on the canvas, i need to draw 10 rects,At the front of  rects,need draw text.
for the text and the color of rects,i use ajax every 1000ms to get the data.
But after 2min,i found the browser is broken down.(the rect and text text can be draggabled,i use chrome browser).
is there good way to fix it?

**Comment by qingxin2016** [comment]
Now i add Rect layer click event,when i am dragging layer ,i don't want to acitive click event,how to do it?

**Comment by qingxin2016** [comment]
when i use draw() function to draw native canvas method,can i use groups and dagggroup properties with it?

**Comment by caleb531** [comment]
@qingxin2016 

The way I would accomplish detecting a click-that-is-not-a-drag is to use flag variables combined with `dragstart` and `dragstop` callbacks:

```js
click: function() {
  if (!this.isDragging) {
    // your code goes here
  }
},
dragstart: function() {
  this.isDragging = true;
},
dragstop: function() {
  this.isDragging = false;
}
```

You can't use `groups`/`dragGroups` with `draw()` by itself, but you should certainly be able to if you create a custom jCanvas method using the Plugin API. See the drawHeart example from the docs:
https://projects.calebevans.me/jcanvas/docs/extending/#example-drawheart
