### ISSUE TITLE
handle plugin problem

### ISSUE THREAD

**Issue by jiawen-Bees360** [caleb531/jcanvas#316]
I am using handle plugin. I am wondering if I can dynamically make a layer resizable.  
I tried
```
this.$canvas.setLayers({ handle: undefined });
```
But it's not working.

**Comment by jiawen-Bees360** [comment]
Well, strange thing.
I change it to 
```
this.$canvas.setLayers({ handle: **null** });
```
It working perfectly.

**Comment by jiawen-Bees360** [comment]
But anyway I have to say that you are doing a nice job on jcanvas. thanks :+1:

**Comment by caleb531** [comment]
@jiawen-Bees360 I probably have a not-so-smart check against `null` only in the code, when I should be checking against any bottom value (`undefined` included). But glad you figured that out—I'll be closing this issue now.
