### ISSUE TITLE
draggable property is always true

### ISSUE THREAD

**Issue by nawataster** [caleb531/jcanvas#317]
During layer creation the **draggable** property always set to **true** value (even if you try to set it to false) if dragGroups property is defined. You should perform `$("canvas").setLayer(layer, {draggable: false}).drawLayers();` additionally to set it to false.

**Comment by caleb531** [comment]
Hi, @nawataster. I see exactly what you mean. However, I'm not inclined to change this because doing so might break jCanvas code that assumes layers with `dragGroups` are implicitly draggable (i.e. without `draggable: true`).

Is your `setLayer` snippet still sufficient as a workaround for you?
