### ISSUE TITLE
drawLayers() need a callback

### ISSUE THREAD

**Issue by kamilic** [caleb531/jcanvas#319]
Hi.
When a layer group contains image layer(s), the behaviour of drawLayers() is not a really synchronous operation.  

in this situation
```javascript
$canvasContainImageLayer.drawLayers();
var base64 = $canvasContainImageLayer.getCanvasImage('jpeg'); 
// not an expected result when image isn't fully loaded.
```

in https://github.com/caleb531/jcanvas/blob/master/dist/jcanvas.js#L1499
```javascript
// Allow image layers to load before drawing successive layers
if (layer._method === $.fn.drawImage && layer.visible) {
    isImageLayer = true;
    break;
}
```

Pause the drawing process and wait for onload() to continue the process by using the following code snippet.  

in https://github.com/caleb531/jcanvas/blob/master/dist/jcanvas.js#L4011
```javascript
// Otherwise, draw image when it loads
img.onload = onload(canvas, ctx, data, params, layer);
// Fix onload() bug in IE9
img.src = img.src;
```

It seems as an asynchronous opertion , so i think that we need a callback to tell outside when the process is ended. 

in https://github.com/caleb531/jcanvas/issues/277
You provided a special version that contains a callback. 
I think it is a good solution to solve this problem, but it isn't found in the latest version. 

Do you have consideration to add this feature into the future release?

**Comment by caleb531** [comment]
@kamilic I honestly don't know why the `drawLayers()` `complete` callback never made it into an official release. I will integrate my changes from #277 this weekend, and comment back with the details on how to download the new build.

My development process is much better than it used to be, so you can be sure this change will be merged into master after I confirm it works for you. Expect an update from me sometime Saturday (or Sunday at the very latest).

**Comment by caleb531** [comment]
@kamilic All done! Please download `jcanvas.js` from the [drawlayers-improvements](https://github.com/caleb531/jcanvas/tree/drawlayers-improvements) branch. I've provided an example below, which you can run in the [jCanvas Sandbox](https://projects.calebevans.localhost/jcanvas/sandbox/).

Once you've tested this and confirmed that this works for you, then I will push these changes as an official release.

```js
$('canvas').addLayer({
  type: 'image',
  source: 'images/fish.jpg',
  x: 150, y: 150,
  width: 200, height: 125
})
.addLayer({
  type: 'arc',
  fillStyle: '#69f',
  strokeStyle: '#000',
  strokeWidth: 2,
  x: 250, y: 100,
  radius: 50
})
// Redraw layers to ensure correct ordering
.drawLayers({
  complete: function() {
    console.log('done!');
  }
});

```

Caleb

**Comment by kamilic** [comment]
Hi, caleb.
Sorry for the late reply.
It works for me, thank you so much !
I will waiting for the official release. :p

**Comment by kamilic** [comment]
oops.
A problem is detected.
When mouse move out of canvas,  callback complete() will be fired again.

**Comment by caleb531** [comment]
@kamilic Okay, I just pushed a potential fix; could you try downloading again please and let me know how it works for you?
https://github.com/caleb531/jcanvas/tree/drawlayers-improvements

**Comment by kamilic** [comment]
Cool!
I think it's time to merge it into the official release.
thank you, caleb.

**Comment by caleb531** [comment]
@kamilic Great! I'll push an official release this weekend.

Caleb

**Comment by caleb531** [comment]
@kamilic I just pushed jCanvas v20.2.0 fixing this issue. Enjoy! Let me know if you find any problems.

-Caleb
