### ISSUE TITLE
draggable event on second drawText not working

### ISSUE THREAD

**Issue by gwenferre** [caleb531/jcanvas#321]
Hello everyone! First, sorry for my english, i hope i would be clear.

I have to create a little painter with JCanvas where the user would be able to add rectangles, ellipses, texts or lines on canvas. I have an issue with the drawText function which is the only element draggable. When i add a first draggable text, i unbind the events on the canvas at first (if the user have previously add a line or more) and it works fine:

```
      let canvas = $('#canvas');
        canvas.unbind();
        canvas.drawText({
                layer: true,
                name: 'draw'+numLayers,
                groups: ['draw'+numLayers],
                x: 30, y: 30,
                fillStyle: colorPicker,
                fontSize: '20pt',
                fontFamily: 'Arial',
                text: texte,
                draggable: true,
                fromCenter: false,
                bringToFront: true,
         }); 
````

But when i have to add a second text, it unbinds events on canvas one more time (i had to) and the draggable event doesn't work anymore, even for the new text. When i don't add canvas.unbind() it works fine but it's a problem if the user use drawLine before: when he drags the layer, it would make lines in the same time.

Thanks for your help :)

**Comment by caleb531** [comment]
Hi, @gwenferre. Sorry for my late response. I am pretty sure your problem is unbinding events in the first place. Why are you unbinding the canvas events before drawing?

**Comment by gwenferre** [comment]
Hello @caleb531 , no problem, thanks for your time! 
If, in the first time, I draw a line for example and after i have to to draw a rectangle, I have to unbind the canvas events because it will draw a line and a rectangle in the same time. I hope I am clear.

**Comment by caleb531** [comment]
> I have to unbind the canvas events because it will draw a line and a rectangle in the same time

"In the same time"? What do you mean? I apologize that this isn't making sense to me—language is hard.

If you want to delete an existing layer, you can use `removeLayer()` and then call `drawLayers()` again. If you want to change a property on an existing layer, use `setLayer()`:
https://projects.calebevans.me/jcanvas/docs/manipulateLayers/

**Comment by caleb531** [comment]
@gwenferre Any update?

**Comment by caleb531** [comment]
@gwenferre I'm closing this issue unless you are still experiencing problems.
