### ISSUE TITLE
Line mouseover event triggered issue

### ISSUE THREAD

**Issue by shenxrs** [caleb531/jcanvas#322]
Using the drawLine method, when the point is more than two, the mouse enters a polygon that is surrounded by multiple points and triggers the mousever event, even if the line is not closed, and not triggered online.

**Comment by caleb531** [comment]
@shenxrs This is not currently possible as-is. The only way you could achieve this currently is to draw out all sides of the desired path as a `drawLine` path in itself, which should have about twice as many points and would be closed.
