### ISSUE TITLE
Mouse Events do not work on Ellipses

### ISSUE THREAD

**Issue by Tjommel** [caleb531/jcanvas#323]
// Hover over the circle
$('canvas').drawEllipse({
  fillStyle: "#9966ff",
  x: 100,
  y: 100,
  width: 50,
  height: 50,
  mouseover: function(layer) {
    console.log("OVER");
  },
  mouseout: function(layer) {
    console.log("OUT");
  }
});

This does not work

**Comment by caleb531** [comment]
@Tjommel Mouse events are only applicable to jCanvas layers. Set `layer: true` on your ellipse and you'll be good to go.

```js
// Hover over the circle
$('canvas').drawEllipse({
layer: true,
fillStyle: "#9966ff",
x: 100,
y: 100,
width: 50,
height: 50,
mouseover: function(layer) {
console.log("OVER");
},
mouseout: function(layer) {
console.log("OUT");
}
});
```
