### ISSUE TITLE
jQuery.fn.bind() is deprecated in jquery 3.2.1

### ISSUE THREAD

**Issue by BlueAndi** [caleb531/jcanvas#324]
The jquery-migrate lib must be used, to support jquery 3.2.1, because jQuery.fn.bind() is deprecated.

Is it planned to update the source, so jquery-migrate won't be necessary anymore?

**Comment by caleb531** [comment]
@BlueAndi According to the [jQuery 3.0 Upgrade Guide](https://jquery.com/upgrade-guide/3.0/#deprecated-bind-and-delegate), the `.bind()` method is deprecated, but not removed from the API. Therefore, could you please clarify why jquery-migrate is still required, even though `bind()`is still present in the API?

**Comment by BlueAndi** [comment]
It seems the jquery-migrate lib must not be used in case only the `jQuery.fn.bind()` is still used. The only advantage is that it points out, that `.bind()` is deprecated to the developer.
