### ISSUE TITLE
Infinite loop when trying to remove layers

### ISSUE THREAD

**Issue by jr-cologne** [caleb531/jcanvas#325]
Hi there!

First of all, thank you for your amazing work! I am really enjoying your library.

However, I have one problem in regards to removing layers.

Whenever I try to remove all layers which do not have a name, an infinite loop occurs.

Am I stupid or is this a bug? 😄 

I would appreciate any kind of help very much.

Here's my code:

```js
$('canvas').addLayer({
  type: 'arc',
  x: 100, y: 100,
  radius: 50,
  fillStyle: '#000',
  name: 'foo'
}).addLayer({
   type: 'rectangle',
   x: 100, y: 100,
   width: 100, height: 100,
   fillStyle: 'red'
}).removeLayers(function(layer) {
   return !layer.name;
}).drawLayers();
```

Thanks in advance!

Best regards from Germany,
@jr-cologne

**Comment by jr-cologne** [comment]
@caleb531 Seems to work for me.

Thanks for the quick fix! :)

**Comment by caleb531** [comment]
@jr-cologne I forgot to mention: I pushed out v21.0.1 with this fix about a week ago. Enjoy!
https://github.com/caleb531/jcanvas/releases/tag/v21.0.1

Caleb

**Comment by jr-cologne** [comment]
Yep, I've already noticed that. Thanks!
