### ISSUE TITLE
TypeScript Definition File

### ISSUE THREAD

**Issue by dotnetnoobie** [caleb531/jcanvas#326]
Would you consider making a TypeScript definition file?

**Comment by caleb531** [comment]
@dotnetnoobie Nope, I have no intention of introducing transpiled languages (like TypeScript) into jcanvas.

**Comment by dotnetnoobie** [comment]
Hi @caleb531 just out of interest is there any particular reason?
e.g. to much work or it's not really suited to jCanvas?

I am just learning about TypeScript and I have used jCanvas before which is very good and makes using the HTML Canvas very easy

**Comment by caleb531** [comment]
@dotnetnoobie A few reasons, in no particular order:

- I don't know TypeScript and haven't taken much interest in it
- It would require a substantial effort on my part to convert the codebase to TypeScript
- I'm not sure what direct benefit it would provide to the library—I suppose readability/write-ability, but I know JS well enough that I don't see that added benefit amounting to much anyway
- It's non-standard, and it's not the only transpiled language for JS; why choose TypeScript over CoffeeScript, for example? I would probably upgrade the library to utilize ES6 syntax (with Babel) sooner

I don't mean to shoot down your suggestion... well okay, maybe I am. :P But ultimately, the value doesn't justify the cost for me.

Anyway, that's my conviction. Also, thanks for your kind words about jCanvas. :)
Caleb

**Comment by dotnetnoobie** [comment]
@caleb531 thanks, I just wondered, I also think it would likely be a big investment of time and effort I only asked because I was playing around with jCanvas and tried to use it in TypeScript I found a third party definition file but I thin it's pretty old and it looks like they only worries about the bits they were interested in.

I am not really a Javascript person, but using jCanavs I have made a couple very good MEME makers in the past with not to much hassle which were able to make very cool looking memes with a pretty limited Javascript, jQuery knowledge/skills. It's definitely a very cool project
