### ISSUE TITLE
handle: x,y,width,height in handlemove

### ISSUE THREAD

**Issue by vitstradal** [caleb531/jcanvas#328]
This is not bug, but question:

Can I get `x`,`y`,`width`, `height`, in `handlemove(layer)`. Because `layer.x`, `layer.y`,... contains position of "handle"  (small cicrle or square) not whole area.

**Comment by vitstradal** [comment]
I figured it out, `layer.x` and `layer.y` is coordinates of center. Unless `fromCenter` is set to `false`.

**Comment by caleb531** [comment]
@vitstradal Yes, you are correct. Per the [Support page FAQ](https://projects.calebevans.me/jcanvas/support/):

> By default, jCanvas considers a shape’s center at its (x, y) position. You can change this behavior using the fromCenter property, which will measure a shape’s (x, y) from its top-left corner.
