### ISSUE TITLE
cursor properties

### ISSUE THREAD

**Issue by Ikes72000** [caleb531/jcanvas#329]
Hello,

I need to change cursor style when mouse is over a layer. In jCanvas documentation, it's indicated that we have to use the cursor property to do that.
I tried to do this, but it didn't work:

```
 $('#myCanvas').addLayer({
        type: 'arc',
        name: 'sunrise',
 	groups: ['dawnGroup2', 'dawnGroup3','dawnGroup4'],
	cursor: 'pointer',
       strokeStyle: '#FEE200',
       strokeWidth: 1,
       fillStyle: '#FEE200',
        x: 350, y: 200,
        radius: 5
})
```
How to use cursor property with a specific layer?

Thanks.

Ikes

**Comment by caleb531** [comment]
@Rowanism you are correct. I will fix that in the docs this weekend.
