### ISSUE TITLE
drawText aligning not working on mobile

### ISSUE THREAD

**Issue by qroft** [caleb531/jcanvas#330]
Thanks a lot for this plugin!
At the moment i am creating a hybrid app via Phonegap based on the Onsen UI.

When i use the align:'right' as option within a drawText object, on my Chrome browser everything looks awesome. But while checking it via the Phonegap App on my Android smartphone, the text is not right aligned.

**Comment by caleb531** [comment]
@qroft jCanvas is just using the native canvas `textAlign` property to make that happen. So I would recommend creating a small example using native canvas and `textAlign`, and testing on both Chrome and Phonegap+Android. If there's still a discrepancy, then it's a larger issue than jCanvas. If not, then it's a definite jCanvas bug.

If this sounds good to you, please let me know what you find. :)

**Comment by caleb531** [comment]
@qroft I'm closing this issue unless you are still experiencing problems.
