### ISSUE TITLE
Why jСanvas draws poor quality circle on small sizes of canvas?

### ISSUE THREAD

**Issue by iElizium** [caleb531/jcanvas#331]
Hello, thanks for jCanvas, I ran into such a problem: poor quality on canvas of small size

Comparison with konvajs:
[https://jsfiddle.net/zye92L8p/2/](https://jsfiddle.net/zye92L8p/2/)

This can be somehow corrected? What am I doing wrong?

**Comment by caleb531** [comment]
@iElizium I'm guessing you are using a device with a high-density display, such as a MacBook Pro with Retina Display. To support high-DPI devices, use the `detectPixelRatio` function. See the docs:

https://projects.calebevans.me/jcanvas/docs/detectPixelRatio/
