### ISSUE TITLE
jCanvas doesn't resize when using detectPixelRatio()

### ISSUE THREAD

**Issue by jeanschmitt** [caleb531/jcanvas#332]
When resizing canvas with :
`$('canvas').attr('width', $(window).width());`
for exemple, the canvas doesn't resize if we're using detectPixelRatio().

This is probably due to the css added by this function.

Manually changing the css width and height gives a weird effect, and after a draw call it returns to the original size

**Comment by caleb531** [comment]
@jeanschmitt What is your intent? Do you want the canvas width/height to change dynamically according to the viewport width? Or something else?
