### ISSUE TITLE
Doesn't seem to work with Meteor

### ISSUE THREAD

**Issue by marcoschwartz** [caleb531/jcanvas#337]
Hello,

I would like to use your library that looks awesome inside my Meteor (https://www.meteor.com/) project, but it doesn't seem to work.

I tried by importing the library via the CDN, and also by installing it via NPM and then importing it with import(). Both results in this error whenever I try to draw something:

TypeError: $.jCanvas is not a function

Any idea of what I could be doing wrong? Thanks!

**Comment by marcoschwartz** [comment]
@caleb531 Thanks for the quick answer! Sure, I basically installed it via NPM, then I import it in my project with:

`import 'jcanvas';`

After, that I tried to create a simple rectangle:

```
$.jCanvas('journey-schema').drawRect({
            strokeStyle: '#c33',
            strokeWidth: 4,
            x: 150,
            y: 100,
            width: 200,
            height: 100,
            cornerRadius: 10
        });
```

**Comment by caleb531** [comment]
@marcoschwartz Oh! I see your problem. `$.jCanvas` is not actually a function. Use `$()` instead of `$.jCanvas()`:

```js
$('journey-schema').drawRect({
            strokeStyle: '#c33',
            strokeWidth: 4,
            x: 150,
            y: 100,
            width: 200,
            height: 100,
            cornerRadius: 10
        });
```

**Comment by marcoschwartz** [comment]
Works now, thx! :)
