### ISSUE TITLE
about img index Top

### ISSUE THREAD

**Issue by LinCaster** [caleb531/jcanvas#338]
I need to put IMG on the top and cover other contents.     
But every time a new img is added, he will be covered by the new img.
The new img will continue to increase and he needs to run at the earliest. At the same time, at the top

Thank you for your help.

        canvas
	.addLayer({
		layer: true,
		type:'image',
		name:'men_left_1',
	  	source:'img/image/men_left_1.png',
	  	x:a,
	  	y:0,
	  	index:42,
	  	width:375*body,
	  	height:633*body,
	  	fromCenter:false,
	}).drawLayers();

this.click(function(){
       canvas.addLayer({
		layer: true,
		type:'image',
		name:'shou_12',
		groups: ['dh_4'],
		source:'img/image/shou_12.png',
		x:win*1.14,
		y:win*0.525,
		index:20,
		width:91*body,
		 height:70*body,
		fromCenter:false,
	}).drawLayers();
})

**Comment by nallias** [comment]
can you reproduce the problem with the sandbox https://projects.calebevans.me/jcanvas/sandbox/ ?

**Comment by LinCaster** [comment]
![image](https://user-images.githubusercontent.com/24221977/46800653-f9819480-cd8a-11e8-8254-a4a6db1364d5.png)
I want to be at the same time without changing the rendering order. Black covered in red top

**Comment by LinCaster** [comment]
> 你能用沙箱重现问题https://projects.calebevans.me/jcanvas/sandbox/吗？

![image](https://user-images.githubusercontent.com/24221977/46801042-136fa700-cd8c-11e8-8725-be7535658a2e.png)
我希望在不改变渲染顺序的情况下同时进行。黑色覆盖在红顶

**Comment by LinCaster** [comment]
> can you reproduce the problem with the sandbox https://projects.calebevans.me/jcanvas/sandbox/ ?

I want to be at the same time without changing the rendering order. Black on top of red

**Comment by LinCaster** [comment]
@nallias

**Comment by LinCaster** [comment]
@nallias @caleb531 
![image](https://user-images.githubusercontent.com/24221977/46802390-bf66c180-cd8f-11e8-972d-226de823c653.png)
I want to be at  without changing the rendering order. Black covered in red

**Comment by wschleter** [comment]
I believe you need to use layers to do this (add layer=true), and the index is not an arbitrary value, it is the index into the layers array. Had to use drawLayers to get it to take affect.
Also see moveLayers

$('canvas').drawArc({
  fillStyle: '#000',
  x: 100, y: 100,
  radius: 50,
  layer: true,
});

var abc = $('canvas').drawArc({
  fillStyle: '#f00',
  x: 150, y: 150,
  radius: 50,
  layer: true,
  index: 0   // index 0 is the bottommost layer
})
$('canvas').drawLayers();

**Comment by LinCaster** [comment]
@wschleter  Thank  My problem has been solved

**Comment by caleb531** [comment]
Thanks, @nallias and @wschleter, for helping to resolve this issue before I've even had a chance to look at it. The help is very much appreciated. :)
