### ISSUE TITLE
Issue when redrawing canvas

### ISSUE THREAD

**Issue by marcoschwartz** [caleb531/jcanvas#339]
Hello,

We managed to use your excellent library to make basic flowchart - like editor inside our app (the canvas is basically built according to data in our MongoDB database). However, I have a problem whenever I try to add / remove an element when the canvas is already initialised. What I do for example when removing an element is to redraw the whole canvas, but it produces a strange bug. Here is when you load the page (everything looks ok):

<img width="1058" alt="screenshot 2018-10-13 at 16 23 19" src="https://user-images.githubusercontent.com/1475795/46906478-6d937800-cf04-11e8-868a-82f17814aaff.png">

After deleting an element, here is how it looks like:

<img width="960" alt="screenshot 2018-10-13 at 16 23 26" src="https://user-images.githubusercontent.com/1475795/46906480-708e6880-cf04-11e8-9715-3612a73bcd33.png">

The element is actually still there (however removed from the database, and the function I use to draw the chart shouldn't take it), and it's weirdly compressed vertically. The only way to then fix it is to reload the page completely. I tried to play with clearCanvas(), but it doesn't do anything. Any idea on what I could be doing wrong?

**Comment by marcoschwartz** [comment]
I tried more things, especially doing a $('canvas').removeLayers(); before drawing again. That works, but only when not using $('canvas').detectPixelRatio() (I have a retina screen). If I use it, then it produces the weird result from above.

**Comment by caleb531** [comment]
@marcoschwartz Well, this is interesting! I have a few questions for you:

1. How often are you calling `detectPixelRatio`, and when?
2. Do you have any other code that scales the canvas?

**Comment by marcoschwartz** [comment]
1. Just once, after drawing all the different shapes
2. I think I actually found the issue - I did one of those at the start of my code:

```
$('canvas').prop({
        width: width
    });
```

Where width the is inner width of the current window (I want the canvas to be full screen). I think that's a scale operation right? I tried to remove it and indeed it fixes the issue. However now is there a way to make both work together ? :)

**Comment by caleb531** [comment]
@marcoschwartz You should be able to make it work, not to worry. Technically, `detectPixelRatio()` was designed to be called only once (to prevent compounded scaling by calling it multiple times), but you can work around that with something like the following code:

```js
// When you update the canvas dimensions via prop()
$myCanvas
  .data('scaled', false)
  .restoreCanvas()
  .saveCanvas();
  .detectPixelRatio()
  .prop({width: newWidth, height: newHeight})
```

Let me know how that works for you. It may require tweaking in your case to get working just right, but key is setting the canvas's internal `scaled` property to `false` (this allows you to call `detectPixelRatio` again using the new canvas dimensions this time).
