### ISSUE TITLE
moveLayer cannot move layer to top

### ISSUE THREAD

**Issue by skywalker999u** [caleb531/jcanvas#341]
I wish to create a layer for a button to be kept at the top of the canvas all the time.

from the code in moveLayer() at line 999 and 1003,
`layers.splice(index, 0, layer);`
`if (index < 0) { index = layers.length + index; }`
it is impossible to move an existing layer to top using moveLayer().
I can work around it using bringToFront + trigger drag event, but it is not sensible if user interaction is not required. 

example: assume the following canvas with 4 layers
bottom [A, B, C, D] top

desired order is [A, C, D, B]
using moveLayer('B', 0) will result in [B, A, C, D]
using moveLayer('B', -1) will result in [A, C, B, D]

**Comment by caleb531** [comment]
Hi @skywalker999u,

You should be able to call `moveLayer()` with the current number of layers. See the example below, which you should run in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/):

```js
var $canvas = $('canvas');

$canvas
.drawRect({
  layer: true,
  name: 'A',
  fillStyle: '#c33',
  x: 100, y: 100,
  width: 100, height: 100
})
.drawArc({
  layer: true,
  name: 'B',
  fillStyle: '#6c3',
  x: 120, y: 120,
  radius: 50
})
.drawPolygon({
  layer: true,
  name: 'C',
  fillStyle: '#36c',
  x: 140, y: 140,
  radius: 67,
  sides: 3
})
.drawPolygon({
  layer: true,
  name: 'D',
  fillStyle: '#c39',
  x: 160, y: 160,
  radius: 67,
  sides: 5
});

$canvas.moveLayer('B', $canvas.getLayers().length);
$canvas.drawLayers();
```
