### ISSUE TITLE
Handles not working properly after the canvas is resized

### ISSUE THREAD

**Issue by abid1208** [caleb531/jcanvas#344]
![tables](https://user-images.githubusercontent.com/11423616/55766591-c0eb1b00-5a8e-11e9-9e93-fd626ed57684.gif)

I have a canvas, of which I change the properties height and width dynamically. These are not the style height and width but the properties of canvas tag.
The handles stop working correctly after the resizing of the canvas is done. The handles rarely trigger the mouseover event and thus I cannot resize them.
However, if I do not change the canvas width and height dynamically, the handles work without issue.

**Comment by caleb531** [comment]
@abid1208 Are you using `detectPixelRatio` at all?

You may be able to use `saveCanvas()` and `restoreCanvas()` to restore the original canvas context after changing the dimensions.

```js
$myCanvas
    .saveCanvas()
    .prop({width: newWidth, height: newHeight})
    .restoreCanvas()
    .drawLayers();
```

**Comment by abid1208** [comment]
No, I am not using it now. Tried to use it and the results were same. I am setting the canvas dimensions manually through Javascript now.
Thanks I'll try to do what you have suggested

**Comment by abid1208** [comment]
So I tried, but unfortunately the behavior is the same. I forgot to mention before; instead of changing the size of canvas, I tried to add HTML `<canvas height="1000" width="1000"></canvas>`
 via .append() function to a div after the size of canvas was calculated. Same issue is being faced there as well

**Comment by abid1208** [comment]
So I've identified whats's actually happening. After the canvas is resized, all of the jcanvas layers are not working as expected. The handles and the rectangles as well.
The shapes are being displayed on the correct spot, but all of the mouse-over events are shifted a bit to the right by a percentage. The greater the X value of the center of the rectangle, the greater is the offset of the mouse events. 
Dragging is also affected by this. Below is the GIF to demonstrate my point
![MdV5jbNVo2](https://user-images.githubusercontent.com/11423616/55794818-b9079700-5adf-11e9-91c1-fb99fd66156c.gif)

**Comment by abid1208** [comment]
`$('canvas')
    .saveCanvas()
    .prop({width: 800, height: 1130})
    .restoreCanvas()
    .drawLayers();

// Add rectangle layer w/o drawing
$('canvas').addLayer({
  type: 'rectangle',
  draggable: true,
  fillStyle: '#fff',
  strokeStyle: '#c33',
  strokeWidth: 2,
  x: 160, y: 150,
  width: 150, height: 80,
  // Define handle properties
  handle: {
    type: 'arc',
    fillStyle: '#fff',
    strokeStyle: '#c33',
    strokeWidth: 2,
    radius: 10
  }
})
// Redraw layers to ensure handles are on top of rectangle
.drawLayers();
`

Code for replication in [sandbox](https://projects.calebevans.me/jcanvas/sandbox/)

**Comment by abid1208** [comment]
Yeah so the issue was, I was setting the width of the canvas larger than its parent Div. I wasn't subtracting the padding of Parent Div while calculating the size of the canvas.
Now it's working great. Thanks for your support and great work on the library. Cheers!

**Comment by caleb531** [comment]
@abid1208 Ah, the joys of the CSS box model. ;) Glad you were able to get it working. I will close this issue; if you encounter any further issues, feel free to create a new issue.
