### ISSUE TITLE
Handle plugin missing basic feature - Text

### ISSUE THREAD

**Issue by Roinoss** [caleb531/jcanvas#346]
I think handle plugin should have option to use text in handle.

**Comment by caleb531** [comment]
@Roinoss The handles that jCanvas creates are not designed to be very big (they're really meant for dragging, after all). What text did you envision placing inside of a handle?

**Comment by Roinoss** [comment]
Anything what app user wants to add. Something like it this link: https://codepen.io/mflorian/pen/aqmvOJ?editors=0010#0 with FabricJS. But after checking somethings, im more sadly: jCanvas isn't a thing that i need as it miss to lot small features. I'll probably just take Fabrics. 
Anyway, thanks for answers.
I will miss this lib documentation with sandbox included.

**Comment by Roinoss** [comment]
-
