### ISSUE TITLE
How to add space between the characters in text

### ISSUE THREAD

**Issue by sarvjeetsingh315** [caleb531/jcanvas#348]
Hello Caleb,
Can you please help me how to add space between the characters in string in canvas? Functionality likewise tracking in MS word.
Thanks

**Comment by caleb531** [comment]
@sarvjeetsingh315 There is no way to adjust letter spacing for regular text (only [arc text](https://www.bleepingcomputer.com/news/security/linux-kernel-prior-to-508-vulnerable-to-remote-code-execution/)).

The most you can do is add spaces between each character of the string; jCanvas _will_ preserve any and all additional whitespace you add between characters. For example, try this example in the [jCanvas Sandbox](https://projects.calebevans.me/jcanvas/sandbox/):

```ja
$('canvas').drawText({
  fillStyle: '#9cf',
  strokeStyle: '#25a',
  strokeWidth: 2,
  x: 160, y: 100,
  fontSize: 48,
  fontFamily: 'Verdana, sans-serif',
  text: 'H   e   l   l   o'
});
```
