### ISSUE TITLE
Replacement for a deprecated method: $.jCanvas()

### ISSUE THREAD

**Issue by ing4prg** [caleb531/jcanvas#349]
In a previous version I have used this syntax to predefine a style for multiple drawings:

$.jCanvas();
$.jCanvas({ strokeStyle:color, strokeWidth:1, rounded:true });

Is there another syntax to replace this deprecated method? When draw multiple lines, it is easier to have some styles predefined.

Thanks!

**Comment by caleb531** [comment]
@ing4prg My only recommendation would be to use `$.extend`:

```js
var defaults = {
  strokeWidth: 1,
  rounded: true
};
$('#my-canvas').drawLine($.extend({
  strokeStyle: 'red'
}, defaults));
```
