### ISSUE TITLE
Submitting a project to the Gallery

### ISSUE THREAD

**Issue by LokeshBabuTG** [caleb531/jcanvas#360]
I would like to submit my project for the Gallery

"Psychro Chart"

This is a psychrometry charter built entirely with jcanvas

[URL](https://lokeshbabutg.github.io/psychroChart)

**Comment by caleb531** [comment]
@LokeshBabuTG Thanks for the submission! I've added the chart (which looks pretty cool, BTW) to the Gallery!

https://projects.calebevans.me/jcanvas/gallery/

![Screen Shot 2020-12-02 at 8 56 32 AM](https://user-images.githubusercontent.com/872474/100904861-4bf70100-347c-11eb-80f8-c90369298b3d.png)

**Comment by LokeshBabuTG** [comment]
Thanks
