### ISSUE TITLE
Handles can't vanish like a layer

### ISSUE THREAD

**Issue by nico-apps** [caleb531/jcanvas#367]
Using the handles API for my Whiteboard application is really great, as it makes the application not as hard to control. Sadly, it doesn't look like you can use them like a layer. 
I tried to name it like a layer in order to delete them later on (`name: "handles"`) but only one handle in the top left appears. 
I tried using `index: 1` and removing it, but it only removed one button.
After adding more code to remove more layer indexes, I managed to remove more buttons, but never all of them for some reason.
Does somebody know what is going on? Is there even a way to remove it, or is it actually impossible?

Thanks in advance

**Comment by caleb531** [comment]
@nico-apps All handles are in fact layers, and they are stored on the parent layer in a special `_handles` array. For example, if your parent layer is a rectangle and stored in a variable called `myRect`, you can access the handles like so:

```js
myRect._handles
```

From this point, you can iterate through that array and do whatever:

```
myRect._handles.forEach(function (handle) {
    $myCanvas.setLayer(handle, {
        ...
    });
});
```

**Comment by nico-apps** [comment]
Thank you @caleb531 , that worked!
