### ISSUE TITLE
multi-touch - future

### ISSUE THREAD

**Issue by shimbala** [caleb531/jcanvas#371]
Hi,

just wondering, do you have any plans to integrate multi-touch function/event?

Cheers, Erik

**Comment by caleb531** [comment]
@shimbala Sorry to say, but I do not currently plan to add support for multi-touch. It can get pretty complicated to implement, and I have never decided how I want to approach it (plus, it'd be a ton of work either way).

**Comment by shimbala** [comment]
@caleb531 Thank you.

I was trying to integrate [this logic](https://konvajs.org/docs/sandbox/Multi-touch_Scale_Stage.html) (touchmove event) on draggable image. I was, let say 95% satisfied.
When scale changed, x and y position were not calculated correctly, so image was "jumpy".

Maybe this is good starting point.
