### ISSUE TITLE
Animating Multiple Layers

### ISSUE THREAD

**Issue by onorinbejasus** [caleb531/jcanvas#82]
There seems to be an issue with the animating of multiple layers. The flag that assures that multiple redraw loops does not seem to fire:

``` javascript
// Prevent multiple redraw loops
if (!data.animating || data.animated === layer) {
        // Redraw layers on last frame
    $canvas.drawLayers();
}
```

This is true for both chaining of animations calls and animating entire groups.

**Comment by Wilzi** [comment]
Hi Caleb,

I think I have an issue with animating multiple layers too.
My sample code is down below. If I increase the maxCircleNumber value to around 100 after the animation my browser freezes for some seconds.
I need to animate around 100-300 circles at the same time with different max radius values.
Could you please help me with this issue?

http://calebevans.me/projects/jcanvas/sandbox/?code=dmFyIG1heENpcmNsZU51bWJlciA9IDcwOwoKdmFyICRjYW52YXMgPSAkKCJjYW52YXMiKSwKICAgIHcgPSAkY2FudmFzLndpZHRoKCksCiAgICBoID0gJGNhbnZhcy5oZWlnaHQoKTsKCmZ1bmN0aW9uIHJhbmQobWluLCBtYXgpIHsKICByZXR1cm4gTWF0aC5yYW5kb20oKSAqIChtYXggLSBtaW4pICsgbWluOwp9Cgpmb3IodmFyIGk9MDtpPG1heENpcmNsZU51bWJlcjtpKyspewogIAogIHZhciByID0gcmFuZCh3LzUsMTApLAogICAgICB4ID0gcmFuZCh3LHIpLAogICAgICB5ID0gcmFuZChoLHIpOwogIAogICRjYW52YXMuZHJhd0FyYyh7CiAgICAgIGxheWVyOiB0cnVlLAogICAgICBncm91cHM6IFsnY2lyY2xlcyddLAogICAgICBmaWxsU3R5bGU6ICJncmVlbiIsCiAgICAgIHg6IHgsIHk6IHksCiAgICAgIHJhZGl1czogMCwKICAgICAgZGF0YTogewogICAgICAgIG1heFJhZGl1czogcgogICAgICB9CiAgfSk7Cn0KCiRjYW52YXMuYW5pbWF0ZUxheWVyR3JvdXAoJ2NpcmNsZXMnLCB7CglyYWRpdXM6IGZ1bmN0aW9uKGxheWVyKXsKCQlyZXR1cm4gbGF5ZXIuZGF0YS5tYXhSYWRpdXM7Cgl9Cn0sIDI1MDAsICdzd2luZycpOw==

Thanks,
Adam

**Comment by caleb531** [comment]
@Wilzi: that might not be feasible. jCanvas can only handle so much at once, especially when dealing with animation (because animation is an expensive operation). However, testing your example within Chrome 40, I am able to animate 100 circles without lag.

The underlying architecture of jCanvas prevents it from being as scalable as I'd like it to be. However, the underlying architecture also makes jCanvas as easy-to-use as it currently is, and thus this becomes a "pick your poison" decision.

Caleb

**Comment by Wilzi** [comment]
@caleb531 Thanks for your response. I've figure out the problem is with jQuery.animate's complete function. If I call it only on the last layer on the group it's animating smoothly :) Otherwise it's called on every layer and freezes the browser without any animation.

**Comment by caleb531** [comment]
Ah, yes, that's a bit tricker. However, if you keep track of which layers have finished their animations (and thus infer how many layers are still animating), then you can logically determine when the last animation has finished.
